export const changelogEntries = [
  {
    version: "v2.2.0",
    date: "2026-06-11",
    title: "Publiczne strony, pytania i poprawki online",
    changes: [
      "Dodano publiczne strony informacyjne: o grze, jak grac, tryby gry, regulamin, polityke prywatnosci i kontakt.",
      "Dodano stopke z linkami oraz sekcje informacyjna z FAQ na stronie glownej.",
      "Przygotowano bezpieczna strukture pod Google AdSense tylko na stronach informacyjnych.",
      "Rozszerzono pule pytan i hasel w trybach Inne pytanie, Impostor i Kim jestem.",
      "Dodano liczniki uzycia kategorii w pokojach, zeby gracze widzieli ryzyko powtorek.",
      "Naprawiono wyniki glosowania na stronie glownej, zeby pokazywaly zsumowane glosy.",
      "Poprawiono licznik online, aby nie zawyzal martwych polaczen.",
    ],
  },
  {
    version: "v2.1.0",
    date: "2026-06-05",
    title: "Poprawki wygody, pokoi i kosmetyków",
    changes: [
      "Dodano głębokie linki do prywatnych pokoi i bezpośrednie zapraszanie linkiem.",
      "Dodano realny voice chat WebRTC w trybie Kim jestem.",
      "Dodano licznik online w górnym pasku i skrócono go do formatu X online.",
      "Dodano przełącznik animacji w katalogu kosmetyków, żeby katalog mniej lagował.",
      "Poprawiono układ i logikę ustawień w Kim jestem, w tym grę do 1 trafienia.",
      "Dodano nowe skiny cukierków i dopracowano stół w Zatrutym cukierku.",
      "Rozbudowano i poprawiono efekty kosmetyków wygranej, przegranej, idle oraz nicków.",
      "Dodano ostatnią szansę impostora na zgadnięcie hasła po głosowaniu.",
      "Poprawiono statystyki, kick z pokoju, pola tekstowe i obsługę daty urodzenia.",
      "Dodano przygotowanie strony pod reklamy Google.",
      "Poprawiono kompatybilność mobilną i kilka problemów z rerenderem UI.",
    ],
  },
  {
    version: "v2.0.0",
    date: "2026-06-04",
    title: "Duża aktualizacja gier i profilu",
    changes: [
      "Dodano ósmy tryb: Zatruty cukierek!",
      "Dodano i rozbudowano kosmetyki: ramki, aury, cukierki oraz animacje idle, wygranej i przegranej.",
      "Dodano katalog kosmetyków i wygodniejsze przewijanie garderoby.",
      "Dodano questy daily i weekly z nagrodami.",
      "Dodano więcej nagród za level i automatyczne odbieranie zaległych nagród.",
      "Dodano wybór kategorii w kolejnych trybach oraz minimalny wybór kilku kategorii tam, gdzie ma to sens.",
      "Rozszerzono pule pytań i haseł w trybach imprezowych.",
      "Dodano tagi trybów: Popularne, Nowe i Nowe pytania.",
      "Dodano filtry trybów w menu głównym.",
      "Dodano ostrzeżenia i oznaczenia 18+ dla pokojów oraz kategorii.",
      "Dodano zgłaszanie graczy, inbox konta i podstawowe narzędzia administracyjne.",
      "Poprawiono błędy synchronizacji, podskakiwania UI i kasowania wpisywanych odpowiedzi przy rerenderze.",
      "Poprawiono kilka błędów w Impostorze, Kim jestem i Zatrutym cukierku.",
    ],
  },
];

export const latestChangelog = changelogEntries[0];
