import { escapeHtml } from "./utils.js?v=20260613-2";

export const familyDefaults={rounds:5,answerTime:30,turnMode:"afterAnswer",topSize:10,scoring:"one"};
const baseQuestionBank=[
  ["Wymień najpopularniejsze owoce.",[["jabłko",35],["banan",25],["truskawka",18],["pomarańcza",12],["gruszka",7],["winogrono",3]]],
  ["Co ludzie robią rano?",[["myją zęby",30],["piją kawę",25],["jedzą śniadanie",20],["biorą prysznic",14],["ubierają się",7],["sprawdzają telefon",4]]],
  ["Wymień coś, co zabierasz na wakacje.",[["walizka",30],["telefon",22],["krem z filtrem",18],["strój kąpielowy",14],["pieniądze",10],["aparat",6]]],
  ["Popularne sporty.",[["piłka nożna",32],["siatkówka",20],["koszykówka",16],["tenis",12],["pływanie",11],["lekkoatletyka",9]]],
  ["Co można znaleźć w lodówce?",[["mleko",28],["ser",22],["warzywa",18],["jajka",14],["wędlinę",10],["jogurt",8]]],
  ["Wymień zwierzęta domowe.",[["pies",35],["kot",32],["rybki",12],["chomik",9],["królik",7],["papuga",5]]],
  ["Co robisz w weekend?",[["odpoczywam",28],["spotykam się ze znajomymi",24],["gram",18],["oglądam film",14],["sprzątam",9],["uprawiam sport",7]]],
  ["Popularne smaki lodów.",[["waniliowy",27],["czekoladowy",25],["truskawkowy",20],["śmietankowy",14],["miętowy",8],["pistacjowy",6]]],
  ["Wymień coś czerwonego.",[["serce",25],["jabłko",22],["pomidor",20],["róża",15],["krew",10],["samochód",8]]],
  ["Co znajduje się w szkolnym plecaku?",[["zeszyt",28],["długopis",24],["książka",18],["lunch",12],["ołówek",10],["telefon",8]]],
  ["Wymień popularne napoje.",[["woda",32],["kawa",24],["herbata",18],["sok",12],["cola",9],["lemoniada",5]]],
  ["Co robisz przed snem?",[["myję zęby",30],["korzystam z telefonu",25],["przebieram się",18],["czytam",12],["gaszę światło",9],["piję wodę",6]]],
  ["Wymień rzeczy potrzebne na plaży.",[["ręcznik",27],["krem",24],["strój kąpielowy",20],["parasol",13],["okulary",10],["piłka",6]]],
  ["Popularne gry planszowe.",[["Monopoly",28],["chińczyk",22],["Scrabble",18],["warcaby",13],["szachy",11],["Dobble",8]]],
  ["Co może być słodkie?",[["czekolada",30],["cukierek",24],["ciasto",20],["lody",14],["miód",8],["owoce",4]]],
  ["Wymień kolory.",[["niebieski",24],["czerwony",22],["zielony",18],["żółty",15],["czarny",12],["fioletowy",9]]]
].map(([prompt,answers])=>({prompt,answers}));
const rankedQuestion=(prompt,names)=>({prompt,answers:names.map((name,index)=>[name,Math.max(1,30-index)])});
const topQuestions=[
  ["Wymień marki telefonów.","Samsung,Apple,Xiaomi,Huawei,Nokia,Motorola,OnePlus,Google Pixel,Realme,Oppo,Honor,Sony,LG,Asus,ZTE,Tecno,Infinix,Alcatel,HTC,Lenovo,BlackBerry,Nothing,Meizu,Microsoft Lumia,Cat,Doogee,Sharp,Poco,Vivo,Vertu"],
  ["Wymień marki samochodów.","Toyota,Volkswagen,BMW,Mercedes,Audi,Ford,Skoda,Renault,Opel,Fiat,Hyundai,Kia,Volvo,Honda,Nissan,Peugeot,Chevrolet,Tesla,Subaru,Mazda,Jeep,Land Rover,Porsche,Lexus,Seat,Citroen,Dacia,Mitsubishi,Suzuki,Alfa Romeo"],
  ["Wymień marki ubrań.","Nike,Adidas,Puma,Reebok,New Balance,Gucci,Zara,H&M,Reserved,Levi's,Calvin Klein,Tommy Hilfiger,Prada,Versace,Armani,Lacoste,Converse,Under Armour,Decathlon,Uniqlo,The North Face,Vans,Wrangler,Dior,Bershka,Pull&Bear,Diesel,Champion,Timberland,Guess"],
  ["Wymień popularne gry.","Minecraft,Fortnite,Roblox,The Sims,GTA,Among Us,Counter-Strike,League of Legends,Call of Duty,FIFA,Mario Kart,Pokémon,Minecraft Dungeons,Valorant,Overwatch,World of Warcraft,The Witcher,Red Dead Redemption,Assassin's Creed,Tetris,Clash Royale,Brawl Stars,EA Sports FC,God of War,Skyrim,Super Mario,Animal Crossing,Far Cry,Grand Theft Auto Online,Among Us"],
  ["Wymień napoje.","woda,kawa,herbata,cola,sok,lemoniada,piwo,wino,energetyk,mleko,kakao,napój izotoniczny,oranżada,kompot,whisky,wódka,rum,szampan,napój gazowany,kefir,maślanka,drink,gin,tonik,kombucha,yerba mate,espresso,cappuccino,ice tea,smoothie"],
  ["Wymień kraje.","Polska,Niemcy,Francja,Włochy,Hiszpania,Stany Zjednoczone,Wielka Brytania,Japonia,Chiny,Brazylia,Kanada,Australia,Indie,Meksyk,Norwegia,Szwecja,Holandia,Portugalia,Grecja,Turcja,Czechy,Ukraina,Austria,Egipt,Argentyna,Chorwacja,Finlandia,Irlandia,Islandia,Nowa Zelandia"],
  ["Wymień miasta.","Warszawa,Nowy Jork,Londyn,Paryż,Berlin,Rzym,Tokio,Kraków,Los Angeles,Madryt,Barcelona,Praga,Wiedeń,Dubaj,Amsterdam,Chicago,San Francisco,Waszyngton,Sydney,Bruksela,Łódź,Wrocław,Pekin,Moskwa,Seul,Miami,Monachium,Oslo,Ateny,Lizbona"],
  ["Wymień piłkarzy.","Robert Lewandowski,Lionel Messi,Cristiano Ronaldo,Kylian Mbappé,Neymar,Erling Haaland,Kevin De Bruyne,Mohamed Salah,Luka Modrić,Harry Kane,Karim Benzema,Virgil van Dijk,Antoine Griezmann,Paul Pogba,Andrés Iniesta,Xavi,Wayne Rooney,Zlatan Ibrahimović,David Beckham,Manuel Neuer,Thibaut Courtois,Pedri,Jude Bellingham,Vinícius Júnior,Ronaldinho,Pele,Diego Maradona,Robert Pirès,Thierry Henry,Andrea Pirlo"],
  ["Wymień youtuberów lub twórców internetowych.","MrBeast,PewDiePie,Markiplier,Dude Perfect,Karol Friz Wiśniewski,ReZigiusz,Blowek,Stuu,QueQuality,Friz,Lexy,Medusa,Boxdel,Isamu,DisStream,Jacksepticeye,Dream,DanTDM,Logan Paul,KSI,Casey Neistat,Veritasium,Marques Brownlee,Jakub Żulczyk,Abstrachuje,GENZIE,Team X,SA Wardęga,Natsu,Multi"],
  ["Wymień zwierzęta.","pies,kot,koń,lew,tygrys,słoń,żyrafa,małpa,królik,szczur,żaba,wąż,krokodyl,rekin,delfin,wieloryb,pingwin,orzeł,łabędź,kurczak,krowa,świnia,owca,koza,lis,wilk,niedźwiedź,panda,koala,żółw"],
  ["Wymień filmy.","Titanic,Avatar,Shrek,Król Lew,Harry Potter,Star Wars,Avengers,Matrix,Gladiator,Ojciec chrzestny,Jurassic Park,Incepcja,Interstellar,Kevin sam w domu,Forrest Gump,Rocky,Terminator,Spider-Man,Iron Man,Deadpool,Kraina lodu,Minionki,Piraci z Karaibów,Transformers,To,Diuna,Top Gun,Akademia Pana Kleksa,Jak wytresować smoka,Kung Fu Panda"],
  ["Wymień seriale.","Gra o tron,Przyjaciele,Dom z papieru,Stranger Things,The Office,Wednesday,Breaking Bad,The Walking Dead,Simpsonowie,Świat według Kiepskich,Na dobre i na złe,Barwy szczęścia,The Crown,Peaky Blinders,Sherlock,Dark,The Last of Us,Wednesday,Bridgerton,Friends,South Park,Dr House,Lost,Chirurdzy,Better Call Saul,The Boys,Wiedźmin,Black Mirror,Big Bang Theory,How I Met Your Mother"],
  ["Wymień firmy.","Microsoft,Apple,Google,Amazon,Samsung,Meta,Tesla,Coca-Cola,McDonald's,Netflix,Disney,Intel,IBM,Sony,Toyota,Volkswagen,Adidas,Nike,Oracle,Adobe,Spotify,Uber,Airbnb,Shell,Starbucks,PayPal,Pepsi,LG,Siemens,Bosch"],
  ["Wymień sklepy.","Biedronka,Lidl,Żabka,Carrefour,Kaufland,Auchan,Allegro,Amazon,Empik,Media Markt,RTV Euro AGD,Decathlon,IKEA,Castorama,Leroy Merlin,Rossmann,Hebe,Reserved,H&M,Zara,Action,Netto,Dino,Dealz,CCC,Martes Sport,OBI,Selgros,Stokrotka,Orlen"],
  ["Wymień fast foody.","McDonald's,KFC,Burger King,Subway,Domino's,Pizza Hut,Starbucks,Żabka,North Fish,Max Premium Burgers,Pasibus,Doner Kebab,Mr Hamburger,Five Guys,Wendy's,Taco Bell,Papa John's,Little Caesars,Quick,Telepizza,Da Grasso,Green Way,Sphinx,Thai Wok,Chinkalnia,Express Doner,Street Food,Food Truck,Burger King Express,Chicken King"]
].map(([prompt,names])=>rankedQuestion(prompt,names.split(",")));
const questionBank=[...baseQuestionBank,...topQuestions];
const normalize=text=>String(text||"").toLocaleLowerCase("pl-PL").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[ąćęłńóśźż]/g,c=>({ą:"a",ć:"c",ę:"e",ł:"l",ń:"n",ó:"o",ś:"s",ź:"z",ż:"z"}[c]||c)).replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim();
const phaseEnd=seconds=>Date.now()+Math.max(10,Number(seconds)||30)*1000;
export function createFamilyGame(players,settings={}){const rounds=Math.max(1,Math.min(20,Number(settings.rounds)||5)),topSize=Math.max(5,Math.min(30,Number(settings.topSize)||10)),order=[...players],pool=questionBank.filter(question=>question.answers.length>=topSize);return {mode:"family",phase:"wheel",round:1,rounds,topSize,scoring:settings.scoring==="higher"||settings.scoring==="lower"?settings.scoring:"one",answerTime:Number(settings.answerTime)||30,turnMode:settings.turnMode==="untilWrong"?"untilWrong":"afterAnswer",players:order,questions:[...(pool.length?pool:questionBank)].sort(()=>Math.random()-.5).slice(0,rounds).map(question=>({...question,answers:question.answers.slice(0,topSize)})),currentUid:order[Math.floor(Math.random()*order.length)],revealed:[],scores:Object.fromEntries(order.map(uid=>[uid,0])),answers:[],wrong:false,phaseEndsAt:Date.now()+2200};}
function nextPlayer(game){const index=game.players.indexOf(game.currentUid);game.currentUid=game.players[(index+1)%game.players.length];}
function startRound(game){game.round+=1;game.questions[game.round-1]=game.questions[game.round-1]||questionBank[Math.floor(Math.random()*questionBank.length)];game.revealed=[];game.answers=[];game.wrong=false;game.currentUid=game.players[Math.floor(Math.random()*game.players.length)];game.phase="wheel";game.phaseEndsAt=Date.now()+2200;}
function nextRound(game){if(game.round>=game.rounds){game.phase="result";game.finished=true;return;}startRound(game);}
export const FamilyEngine={answer(game,uid,text){if(game.phase!=="answer"||game.currentUid!==uid)return "To nie jest Twoja kolej.";const value=normalize(text);if(!value)return "Wpisz odpowiedź.";const question=game.questions[game.round-1],hit=question.answers.findIndex(([answer])=>normalize(answer)===value);game.answers.push({uid,text:value,hit});if(hit>=0&&!game.revealed.includes(hit)){game.revealed.push(hit);const points=game.scoring==="one"?1:game.scoring==="higher"?question.answers[hit][1]:game.topSize-hit;game.scores[uid]=(game.scores[uid]||0)+points;if(game.revealed.length>=question.answers.length){nextRound(game);return;}if(game.turnMode==="afterAnswer")nextPlayer(game);game.wrong=false;}else{game.wrong=true;nextPlayer(game);} },timeout(game){if(game.phase==="wheel"){game.phase="answer";game.phaseEndsAt=phaseEnd(game.answerTime);return;}if(game.phase!=="answer")return;game.wrong=true;nextPlayer(game);game.phaseEndsAt=phaseEnd(game.answerTime);},next(game){startRound(game);}};
function answerRows(game,question){return question.answers.map(([answer,points],index)=>`<div class="family-answer-row ${game.revealed.includes(index)?"is-revealed":""}"><b>${index+1}.</b><span>${game.revealed.includes(index)?escapeHtml(answer):"???"}</span><strong>${game.revealed.includes(index)?points:""}</strong></div>`).join("");}
export function renderFamilyGame(root,{room,accounts,currentUser},actions){const game=room.game;if(game.phase==="result"){const ranking=Object.entries(game.scores).sort(([,a],[,b])=>b-a).map(([uid,score],i)=>`<div class="family-rank-row"><b>${i+1}. ${escapeHtml(accounts[uid]?.nick||"Gracz")}</b><strong>${score} pkt</strong></div>`).join("");root.innerHTML=`<main class="page family-page"><section class="panel family-panel center"><p class="eyebrow">FAMILIADA · PODIUM</p><h1>Wyniki końcowe</h1><div class="family-ranking">${ranking}</div><button class="primary" id="family-room">Wróć do lobby</button></section></main>`;root.querySelector("#family-room").addEventListener("click",actions.returnToRoom);return;}const q=game.questions[game.round-1],expected={phase:game.phase,phaseEndsAt:game.phaseEndsAt};if(game.phase==="wheel"){root.innerHTML=`<main class="page family-page enter"><section class="panel family-panel center"><p class="eyebrow">FAMILIADA · RUNDA ${game.round}/${game.rounds}</p><div class="family-wheel"><span>?</span></div><h1>Losujemy gracza...</h1><p class="muted">Koło fortuny wybiera pierwszą osobę.</p></section></main>`;}else{root.innerHTML=`<main class="page family-page enter"><section class="panel family-panel"><p class="eyebrow">FAMILIADA · RUNDA ${game.round}/${game.rounds}</p><h1>${escapeHtml(q.prompt)}</h1><div class="family-board">${answerRows(game,q)}</div><p class="family-turn">${game.currentUid===currentUser?"Twoja kolej":"Kolej: "+escapeHtml(accounts[game.currentUid]?.nick||"Gracz")}</p>${game.wrong?'<div class="family-miss">X · Nie ma tego na tablicy</div>':""}<form id="family-answer" class="family-form"><input id="family-input" placeholder="Wpisz odpowiedź" autocomplete="off" ${game.currentUid===currentUser?"":"disabled"}><button class="primary" ${game.currentUid===currentUser?"":"disabled"}>Odpowiedz</button></form><div class="family-scores">${Object.entries(game.scores).map(([uid,score])=>`<span>${escapeHtml(accounts[uid]?.nick||"Gracz")}: <b>${score}</b></span>`).join("")}</div></section></main>`;root.querySelector("#family-answer")?.addEventListener("submit",event=>{event.preventDefault();actions.familyAnswer(root.querySelector("#family-input").value,expected);});}if(game.phase!=="result"){renderFamilyGame.countdown=setTimeout(()=>actions.familyTimeout(expected),Math.max(100,game.phaseEndsAt-Date.now()+50));}}
export function renderFamilyLobbySettings(room,isHost){const s=room.settings||familyDefaults;return `<div class="family-settings"><label>Liczba rund <input data-family-setting="rounds" type="number" min="1" max="20" value="${s.rounds||5}" ${isHost?"":"disabled"}></label><label>Czas odpowiedzi <input data-family-setting="answerTime" type="number" min="10" max="180" value="${s.answerTime||30}" ${isHost?"":"disabled"}> s</label><label>Sposób zmiany gracza <select data-family-setting="turnMode" ${isHost?"":"disabled"}><option value="afterAnswer" ${s.turnMode!=="untilWrong"?"selected":""}>Po każdej odpowiedzi</option><option value="untilWrong" ${s.turnMode==="untilWrong"?"selected":""}>Dopóki się nie pomyli</option></select></label></div>`;}
export function stopFamilyTimer(){clearTimeout(renderFamilyGame.countdown);}

function ensureFamilyRoundState(game) {
  if (!game || typeof game !== "object") return game;
  if (!Array.isArray(game.revealed)) game.revealed = [];
  if (!Array.isArray(game.answers)) game.answers = [];
  if (!game.scores || typeof game.scores !== "object" || Array.isArray(game.scores)) game.scores = {};
  return game;
}

const familyAnswer = FamilyEngine.answer;
FamilyEngine.answer = (game, uid, text) => familyAnswer(ensureFamilyRoundState(game), uid, text);
const familyTimeout = FamilyEngine.timeout;
FamilyEngine.timeout = game => familyTimeout(ensureFamilyRoundState(game));
const familyNext = FamilyEngine.next;
FamilyEngine.next = game => familyNext(ensureFamilyRoundState(game));
const renderFamilyGameBase = renderFamilyGame;
renderFamilyGame = (root, context, actions) => {
  ensureFamilyRoundState(context?.room?.game);
  return renderFamilyGameBase(root, context, actions);
};
export function renderFamilyLobbySettingsV2(room,isHost){const s=room.settings||familyDefaults;const sizes=[5,10,15,20,25,30];return `<div class="family-settings"><label>Liczba rund <input data-family-setting="rounds" type="number" min="1" max="20" value="${s.rounds||5}" ${isHost?"":"disabled"}></label><label>Czas odpowiedzi <input data-family-setting="answerTime" type="number" min="10" max="180" value="${s.answerTime||30}" ${isHost?"":"disabled"}> s</label><label>Ranking <select data-family-setting="topSize" ${isHost?"":"disabled"}>${sizes.map(value=>`<option value="${value}" ${Number(s.topSize||10)===value?"selected":""}>Top ${value}</option>`).join("")}</select></label><label>Punktacja <select data-family-setting="scoring" ${isHost?"":"disabled"}><option value="one" ${s.scoring!=="higher"&&s.scoring!=="lower"?"selected":""}>Każda poprawna = 1</option><option value="higher" ${s.scoring==="higher"?"selected":""}>Wyżej = więcej punktów</option><option value="lower" ${s.scoring==="lower"?"selected":""}>Niżej = więcej punktów</option></select></label><label>Sposób zmiany gracza <select data-family-setting="turnMode" ${isHost?"":"disabled"}><option value="afterAnswer" ${s.turnMode!=="untilWrong"?"selected":""}>Po każdej odpowiedzi</option><option value="untilWrong" ${s.turnMode==="untilWrong"?"selected":""}>Dopóki się nie pomyli</option></select></label><p class="tiny">Zbyt długie rankingi są automatycznie pomijane, jeśli pytanie nie ma tylu sensownych odpowiedzi.</p></div>`;}
