import { renderGame } from "./game.js?v=20260612-1";
import { impostorDefaults, renderImpostorGameStable as renderImpostorGame } from "./impostor.js?v=20260605-5";
import { identityDefaults, renderIdentityGame } from "./identity.js?v=20260605-7";
import { otherQuestionDefaults, renderOtherQuestionGame } from "./otherQuestion.js?v=20260605-4";
import { renderWouldYouRather } from "./wouldYouRather.js?v=20260612-1";
import { mostLikelyDefaults, renderMostLikelyGame } from "./mostLikely.js?v=20260612-1";
import { friendshipDefaults, renderFriendshipTestGame } from "./friendshipTest.js?v=20260605-1";
import { poisonCandyDefaults, renderPoisonCandyGame } from "./poisonCandy.js?v=20260605-6";
import { bombDefaults, renderBombGame } from "./bomb.js?v=20260621-1";
import { closestTruthDefaults, renderClosestTruthGame } from "./closestTruth.js?v=20260612-3";
import { rankingDefaults, renderRankingGame } from "./ranking.js?v=20260612-2";
import { fiveSecondsDefaults, renderFiveSecondsGame } from "./fiveSeconds.js?v=20260612-2";
import { clockDefaults, renderClockGame } from "./clock.js?v=20260613-1";
import { pokemonDefaults, renderPokemonGame } from "./pokemon.js?v=20260804-15";
import { wavelengthDefaults, renderWavelengthGame } from "./wavelength.js?v=20260804-1";
import { quizDefaults, renderQuizGame } from "./quiz.js?v=20260804-2";
import { mathematicsDefaults, renderMathematicsGame } from "./mathematics.js?v=20260804-1";
import { markerDefaults, renderMarkerGame } from "./marker.js?v=20260804-1";
import { sequenceDefaults, renderSequenceGame } from "./sequence.js?v=20260804-1";
import { familyDefaults, renderFamilyGame } from "./family.js?v=20260804-1";
import { wordChainDefaults, renderWordChainGame } from "./wordChain.js?v=20260804-5";

export const gamesRegistry = {
  udowodnij: {
    id: "udowodnij",
    name: "Udowodnij!",
    description: "Licytuj liczbę odpowiedzi, podbijaj stawkę i sprawdzaj, kto tylko blefuje.",
    help: ["Gracz deklaruje, ile poprawnych odpowiedzi poda na temat.", "Kolejni gracze podbijają wynik albo sprawdzają deklarację.", "Sprawdzany gracz wpisuje odpowiedzi przed końcem czasu.", "Da radę - wygrywa rundę. Nie da rady - przegrywa rundę."],
    allowReports: true,
    players: "2-8 osób",
    minPlayers: 2,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "⚡",
    art: "prove",
    featured: true,
    render: renderGame,
    defaultSettings: { answerTime: 30 },
  },
  impostor: {
    id: "impostor",
    name: "Impostor",
    description: "Jedna osoba nie zna sekretnego hasła. Rozmawiajcie i znajdźcie impostora.",
    help: ["Większość graczy dostaje to samo słowo, impostor inne albo gorszą podpowiedź.", "Po kolei piszecie wskazówki tak, żeby nie zdradzić słowa zbyt łatwo.", "Po rundach głosujecie, kto jest impostorem.", "Obywatele wygrywają, gdy wyrzucą impostora. Impostor wygrywa, gdy się ukryje."],
    allowReports: true,
    players: "3-8 osób",
    minPlayers: 3,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "🕵️",
    art: "impostor",
    audience: "everyone",
    badges: ["popular"],
    render: renderImpostorGame,
    defaultSettings: impostorDefaults,
  },
  "kim-jestem": {
    id: "kim-jestem",
    name: "Kim jestem?",
    description: "Odgadnij swoją postać, zadając znajomym pytania, na które odpowiedzą tak lub nie.",
    help: ["Każdy widzi hasła innych graczy, ale nie swoje.", "W swojej turze zadajesz pytanie albo próbujesz zgadnąć, kim jesteś.", "Reszta odpowiada zgodnie z ustawieniami pokoju.", "Gra kończy się po rundach albo gdy gracze zdobędą wymagane trafienia."],
    allowReports: true,
    players: "2-10 osób",
    minPlayers: 2,
    maxPlayers: 10,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "❓",
    art: "identity",
    audience: "everyone",
    badges: ["popular", "newQuestions"],
    render: renderIdentityGame,
    defaultSettings: identityDefaults,
  },
  "inne-pytanie": {
    id: "inne-pytanie",
    name: "Inne pytanie",
    description: "Odpowiedz tak, żeby pasować do grupy, ale uważaj: ktoś dostał zupełnie inne pytanie.",
    help: ["Prawie wszyscy dostają jedno pytanie, jedna osoba inne.", "Każdy pisze odpowiedź tak, żeby brzmiała naturalnie.", "Czytacie odpowiedzi i głosujecie, kto miał inne pytanie.", "Grupa wygrywa, gdy złapie tę osobę. Osoba z innym pytaniem wygrywa, gdy się ukryje."],
    allowReports: true,
    players: "3-10 osób",
    minPlayers: 3,
    maxPlayers: 10,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "🤔",
    art: "question",
    audience: "everyone",
    render: renderOtherQuestionGame,
    defaultSettings: otherQuestionDefaults,
  },
  "co-wolisz": {
    id: "co-wolisz",
    name: "Co wolisz?",
    description: "Wybieraj jedną z dwóch opcji i porównuj swoje odpowiedzi z innymi graczami.",
    adult: false,
    help: ["Dostajesz pytanie z dwiema opcjami.", "Wybierasz jedną odpowiedź.", "Od razu widzisz wynik głosowania.", "To tryb solo, bez pokoju."],
    players: "Tryb solo",
    minPlayers: 1,
    maxPlayers: 12,
    supportsLobby: false,
    supportsSolo: true,
    symbol: "⚖️",
    art: "choice",
    render: renderWouldYouRather,
    defaultSettings: {},
  },
  "kto-najpredzej": {
    id: "kto-najpredzej",
    name: "Kto najprędzej...?",
    description: "Głosujcie, kto z was najpewniej zrobi daną rzecz. Wyniki potrafią zaskoczyć.",
    adultBySettings: true,
    help: ["Pojawia się pytanie typu: kto najprędzej coś zrobi.", "Każdy głosuje na jednego gracza.", "Po rundzie widzicie wyniki i punkty.", "Tryb najlepiej działa w ekipie, która się zna."],
    allowReports: false,
    players: "2-8 osób",
    minPlayers: 2,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "☝",
    art: "vote",
    audience: "crew",
    render: renderMostLikelyGame,
    defaultSettings: mostLikelyDefaults,
  },
  "test-znajomosci": {
    id: "test-znajomosci",
    name: "Test znajomości",
    description: "Sprawdźcie, kto naprawdę zna ekipę najlepiej. Każda odpowiedź ma znaczenie.",
    help: ["Gracze odpowiadają na pytania o sobie.", "Potem reszta zgaduje, kto dał którą odpowiedź.", "Za trafienia wpadają punkty.", "Tryb wymaga znajomości graczy, więc najlepiej grać ze swoją ekipą."],
    allowReports: false,
    players: "3-8 osób",
    minPlayers: 3,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "❤️",
    art: "friends",
    audience: "crew",
    render: renderFriendshipTestGame,
    defaultSettings: friendshipDefaults,
  },
  "zatruty-cukierek": {
    id: "zatruty-cukierek",
    name: "Zatruty cukierek!",
    description: "Zatruj swoje cukierki po cichu, a potem jedzcie po kolei, az przy stole zostanie jedna osoba.",
    help: ["Każdy po cichu wybiera cukierki, które zatruwa.", "Potem gracze po kolei jedzą po jednym cukierku ze stołu.", "Nie możesz zjeść własnego zatrutego cukierka.", "Kto trafi na cudzy zatruty cukierek, odpada. Wygrywa ostatni żywy gracz."],
    allowReports: true,
    players: "2-8 osob",
    minPlayers: 2,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "🍬",
    art: "candy",
    audience: "everyone",
    badges: [],
    render: renderPoisonCandyGame,
    defaultSettings: poisonCandyDefaults,
  },
  bomba: {
    id: "bomba",
    name: "Bomba",
    description: "Podawajcie odpowiedzi po kolei, zanim ukryty timer wysadzi bombe na stole.",
    help: ["Host wybiera rundy, punkty, czas odpowiedzi i minimum trzy kategorie.", "Gra losuje kategorie, a gracze po kolei wpisuja odpowiedzi.", "Nie wolno powtarzac odpowiedzi ani oddawac pustej tury.", "Po wybuchu gracz z bomba przegrywa runde, a pozostali dostaja punkty."],
    allowReports: true,
    players: "2-8 osob",
    minPlayers: 2,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "💣",
    art: "bomb",
    audience: "crew",
    badges: [],
    render: renderBombGame,
    defaultSettings: bombDefaults,
  },
  "najblizej-prawdy": {
    id: "najblizej-prawdy",
    name: "Najbliżej prawdy",
    description: "Strzelajcie liczby i sprawdzajcie, kto byl najblizej prawdziwej odpowiedzi.",
    help: ["Gra pokazuje pytanie liczbowe z wybranej kategorii.", "Kazdy wpisuje jedna liczbe, bez podgladania odpowiedzi innych.", "Po komplecie odpowiedzi widzicie prawidlowa liczbe, roznice i ranking rundy.", "Najblizsza odpowiedz dostaje najwiecej punktow, kolejne miejsca mniej."],
    allowReports: true,
    players: "2-8 osob",
    minPlayers: 2,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "🎯",
    art: "truth",
    audience: "everyone",
    badges: [],
    render: renderClosestTruthGame,
    defaultSettings: closestTruthDefaults,
  },
  ranking: {
    id: "ranking",
    name: "Ranking",
    description: "Ukladajcie listy po swojemu i sprawdzajcie, kto mysli najbardziej jak grupa.",
    help: ["Kazdy dostaje te sama liste elementow.", "Przeciagacie elementy, ukladajac ranking od najlepszego do najslabszego.", "Po rundzie gra tworzy ranking grupowy ze srednich pozycji.", "Im bardziej twoja lista pasuje do grupowej, tym wiecej punktow dostajesz."],
    allowReports: true,
    players: "3-8 osob",
    minPlayers: 3,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "🏆",
    art: "ranking",
    audience: "crew",
    badges: [],
    render: renderRankingGame,
    defaultSettings: rankingDefaults,
  },
  "5-sekund": {
    id: "5-sekund",
    name: "5 sekund",
    description: "Masz kilka sekund, zeby wymienic trzy rzeczy z podanej kategorii.",
    help: ["Gra pokazuje zadanie typu: wymien 3 zwierzeta.", "Aktywny gracz ma 5, 10 albo 15 sekund na wpisanie odpowiedzi.", "Po czasie odpowiedz blokuje sie i tura przechodzi dalej.", "Pelna odpowiedz daje 3 punkty, czesciowa mniej."],
    allowReports: true,
    players: "2-8 osob",
    minPlayers: 2,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: false,
    symbol: "⏱️",
    art: "five",
    audience: "everyone",
    badges: [],
    render: renderFiveSecondsGame,
    defaultSettings: fiveSecondsDefaults,
  },
  zegar: {
    id: "zegar",
    name: "Zegar",
    description: "Wyczuj czas bez patrzenia na licznik i zatrzymaj zegar najblizej celu.",
    help: ["Gra losuje czas od 3 do 15 sekund.", "Kazdy widzi swoj stylowy zegar, ale nie widzi aktualnego czasu.", "Gdy czujesz, ze cel minal, naciskasz STOP.", "Po komplecie stopow widzicie wspolna os czasu i roznice od wyniku."],
    allowReports: true,
    players: "1-8 osob",
    minPlayers: 1,
    maxPlayers: 8,
    supportsLobby: true,
    supportsSolo: true,
    symbol: "⌚",
    art: "clock",
    audience: "everyone",
    badges: [],
    render: renderClockGame,
    defaultSettings: clockDefaults,
  },
  "pokemon-dex": {
    id: "pokemon-dex", name: "NAJBLIŻSZY NUMER POKEDEX", description: "Wpisz Pokémona z numerem jak najbliższym wylosowanemu celowi.", help: ["Gra losuje numer National Dex.", "Wpisz nazwę Pokémona, bez podawania numeru.", "Najmniejsza różnica wygrywa rundę."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"#", art:"pokemon-dex", audience:"pokemon", badges:["new"], render:renderPokemonGame, defaultSettings:pokemonDefaults["pokemon-dex"],
  },
  "pokemon-last-letter": {
    id: "pokemon-last-letter", name: "OSTATNIA LITERA", description: "Budujcie łańcuch Pokémonów, pilnując ostatniej litery.", help: ["Pierwszy gracz podaje dowolnego Pokémona.", "Następny musi zacząć od ostatniej litery poprzedniej nazwy.", "Powtórki są niedozwolone."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"↗", art:"pokemon-letter", audience:"pokemon", badges:["new"], render:renderPokemonGame, defaultSettings:pokemonDefaults["pokemon-last-letter"],
  },
  "pokemon-evolution": {
    id: "pokemon-evolution", name: "EVOLUTION RACE", description: "Znajdź kolejną lub końcową ewolucję szybciej od innych.", help: ["Gra pokazuje bazowego Pokémona.", "Wpisz nazwę Pokémona z tej samej linii ewolucji.", "Każda odpowiedź ma limit czasu."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"↻", art:"pokemon-evolution", audience:"pokemon", badges:["new"], render:renderPokemonGame, defaultSettings:pokemonDefaults["pokemon-evolution"],
  },
  "pokemon-auction": {
    id: "pokemon-auction", name: "LICYTACJA TEAMU", description: "Licytuj Pokémony i zbuduj drużynę z najwyższym BST.", help: ["Każdy gracz dostaje ten sam budżet.", "Pokémony są wystawiane po kolei, a każda oferta ma limit czasu.", "BST zostaje ujawnione dopiero po zakończeniu aukcji."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"$", art:"pokemon-auction", audience:"pokemon", badges:["new"], render:renderPokemonGame, defaultSettings:pokemonDefaults["pokemon-auction"],
  },
  "pokemon-types": {
    id: "pokemon-types", name: "TYPY NA START", description: "Wybierzcie typy i znajdźcie Pokémona pasującego do kombinacji.", help: ["Każdy gracz wybiera jeden typ.", "Po ujawnieniu kombinacji wpisujecie poprawnego Pokémona.", "Brakująca kombinacja odblokowuje ponowny wybór."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"✦", art:"pokemon-types", audience:"pokemon", badges:["new"], render:renderPokemonGame, defaultSettings:pokemonDefaults["pokemon-types"],
  },
  "pokemon-match-type": {
    id: "pokemon-match-type", name: "DOPASUJ TYP", description: "Rozpoznaj wszystkie typy pokazanego Pokémona szybciej od innych.", help: ["Wszyscy widzą tego samego Pokémona.", "Zaznacz wszystkie jego typy.", "Błędna odpowiedź zabiera serce."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"◈", art:"pokemon-types", audience:"pokemon", badges:["new"], render:renderPokemonGame, defaultSettings:pokemonDefaults["pokemon-match-type"],
  },
  wavelength: {
    id: "wavelength", name: "WAVELENGTH", description: "Naprowadź ekipę na ukryty punkt między dwoma przeciwieństwami.", help: ["Opisujący widzi ukryty cel i podaje jedno słowo lub krótkie zdanie.", "Pozostali wspólnie ustawiają wskaźnik na skali.", "Host zatwierdza ustawienie, a wynik zależy od odległości od celu."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"◌", art:"wavelength", audience:"everyone", badges:["new"], render:renderWavelengthGame, defaultSettings:wavelengthDefaults,
  },
  quiz: {
    id: "quiz", name: "QUIZ", description: "Sprawdźcie wiedzę w trybie Casual albo zmierzcie się w teleturniejowej rywalizacji.", help: ["Najpierw wybierzcie wariant Casual albo Rywalizacja.", "Casual pozwala hostowi ustawić liczbę i czas pytań.", "Rywalizacja dobiera graczy do szybkiego meczu 2–4 osób."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"?", art:"quiz", audience:"everyone", badges:["new"], render:renderQuizGame, defaultSettings:quizDefaults,
  },
  mathematics: {
    id: "mathematics", name: "MATEMATYKA", description: "Rozwiązujcie proceduralnie generowane zadania i ścigajcie się o poprawne odpowiedzi.", help: ["Host wybiera liczbę pytań, czas, sposób odpowiedzi i typy zadań.", "Pytania rosną z poziomem trudności wraz z numerem pytania.", "Pierwsza poprawna odpowiedź daje punkt."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"∑", art:"mathematics", audience:"everyone", badges:["new"], render:renderMathematicsGame, defaultSettings:mathematicsDefaults,
  },
  marker: {
    id: "marker", name: "MARKER", description: "Znajdź liczby na wspólnej planszy i zakreśl je szybciej od przeciwnika.", help: ["Wybierz liczbę na wspólnej planszy.", "Przeciwnik szuka liczby, a Ty pokrywasz własne pole markerem.", "System sprawdza faktyczne pokrycie pola, więc samo kliknięcie nie wystarczy."], allowReports:true, players:"2 osoby", minPlayers:2, maxPlayers:2, supportsLobby:true, supportsSolo:false, symbol:"✎", art:"marker", audience:"everyone", badges:["new"], render:renderMarkerGame, defaultSettings:markerDefaults,
  },
  sequence: {
    id: "sequence", name: "ZGADNIJ SEKWENCJĘ", description: "Twórzcie tajne sekwencje kolorów i łamcie kod przeciwnika.", help: ["Każdy gracz tworzy własną sekwencję dla przeciwnika.", "Po każdej próbie widzicie tylko liczbę kolorów na poprawnym miejscu.", "Nie pokazujemy, które pozycje są prawidłowe."], allowReports:true, players:"2 osoby", minPlayers:2, maxPlayers:2, supportsLobby:true, supportsSolo:false, symbol:"◎", art:"sequence", audience:"everyone", badges:["new"], render:renderSequenceGame, defaultSettings:sequenceDefaults,
  },
  family: {
    id: "family", name: "FAMILIADA", description: "Odgadujcie najpopularniejsze odpowiedzi i zdobywajcie punkty z tablicy.", help: ["Gra losuje pytanie i odpowiedzi z ukrytej tablicy.", "Po każdej odpowiedzi pokazujemy tylko miejsce i wartość trafienia.", "Host wybiera sposób zmiany gracza oraz liczbę rund."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"★", art:"family", audience:"everyone", badges:["new"], render:renderFamilyGame, defaultSettings:familyDefaults,
  },
  "word-chain": {
    id: "word-chain", name: "ŁAŃCUCH SŁÓW", description: "Budujcie łańcuch słów, pilnując ostatniej litery.", help: ["Pierwsze słowo jest losowane z dużego słownika.", "Każde kolejne słowo zaczyna się ostatnią literą poprzedniego.", "Host może włączyć język angielski oraz kontrolowane powtórki."], allowReports:true, players:"2-8 osób", minPlayers:2, maxPlayers:8, supportsLobby:true, supportsSolo:false, symbol:"↔", art:"word-chain", audience:"everyone", badges:["new"], render:renderWordChainGame, defaultSettings:wordChainDefaults,
  },
};

export const gamesList = Object.values(gamesRegistry);

export function getGameMode(id) {
  return gamesRegistry[id] || gamesRegistry.udowodnij;
}
