import { identityCategories, identityCategoryNames } from "../content/kim-jestem/categories.js";
import { $, avatarHtml, escapeHtml, normalizeAnswer, playerMiniHtml } from "./utils.js";
import { levelBadgeHtml } from "./progression.js";
import { Audio } from "./audio.js";
import { Effects } from "./effects.js";
let timerId,lastCountdown;
export const identityDefaults={category:"Wszystkie",turnTime:45,rounds:3,responseMode:"extended",oneGuess:true,newAfterGuess:true,endAfterRounds:true,playerWordsEnabled:false};
const shuffle=a=>[...a].sort(()=>Math.random()-.5), now=()=>Date.now();
const objectOrEmpty=value=>value&&typeof value==="object"&&!Array.isArray(value)?value:{};
const arrayOrEmpty=value=>Array.isArray(value)?value:[];
const mini=p=>playerMiniHtml(p);
function pool(settings,customWords){let base=settings.category==="Wszystkie"?Object.values(identityCategories).flat():identityCategories[settings.category]||[];const own=Object.values(customWords||{}).flat();return [...own,...base];}
function drawWord(game,uid,settings,customWords){const choices=shuffle(pool(settings,customWords)).filter(word=>!(customWords?.[uid]||[]).includes(word));return choices[0]||shuffle(pool(settings,customWords))[0]||"tajemnicza postać";}
export function createIdentityGame(players,settings,customWords={}){const words={};players.forEach(uid=>words[uid]=drawWord({},uid,settings,customWords));const order=shuffle(players);return{phase:"turn",order,turnIndex:0,round:1,words,history:[],responses:{},pending:null,scores:Object.fromEntries(players.map(uid=>[uid,0])),phaseEndsAt:now()+settings.turnTime*1000};}
function normalizeIdentityGame(game,players=[]){game.history=arrayOrEmpty(game.history);game.responses=objectOrEmpty(game.responses);game.scores=objectOrEmpty(game.scores);game.words=objectOrEmpty(game.words);game.order=Array.isArray(game.order)?game.order:(players.length?[...players]:Object.keys(game.words));if(!Number.isFinite(Number(game.turnIndex)))game.turnIndex=0;return game;}
function advance(game,settings,customWords){const uid=game.order[game.turnIndex];if(game.pending?.correct&&settings.newAfterGuess)game.words[uid]=drawWord(game,uid,settings,customWords);game.pending=null;game.responses={};game.turnIndex++;if(game.turnIndex>=game.order.length){game.turnIndex=0;game.round++;if(settings.endAfterRounds&&game.round>settings.rounds){game.phase="results";game.phaseEndsAt=null;return;}}game.phase="turn";game.phaseEndsAt=now()+settings.turnTime*1000;}
export const IdentityEngine={
 submit(game,uid,text,type,settings,customWords){normalizeIdentityGame(game);if(game.phase!=="turn"||game.order[game.turnIndex]!==uid)return"To nie jest twoja tura.";if(!text.trim())return"Wpisz pytanie lub odpowiedź.";const correct=type==="guess"&&normalizeAnswer(text)===normalizeAnswer(game.words[uid]);game.pending={uid,text:text.trim(),type,correct};if(correct){game.scores[uid]=(game.scores[uid]||0)+1;game.history.push({...game.pending,answer:"TRAFIONE"});advance(game,settings,customWords);}else{game.phase="responses";game.responses={};game.phaseEndsAt=now()+settings.turnTime*1000;}},
 respond(game,uid,response,settings,customWords){normalizeIdentityGame(game);if(game.phase!=="responses")return"Pytanie nie oczekuje już na odpowiedzi.";if(uid===game.pending?.uid)return"Aktywny gracz nie odpowiada na własne pytanie.";if(uid in game.responses)return"Twoja odpowiedź została już zapisana.";game.responses[uid]=response;const needed=game.order.length-1;if(Object.keys(game.responses).length>=needed){game.history.push({...game.pending,answer:Object.values(game.responses).join(" / ")});advance(game,settings,customWords);}return null;},
 timeout(game,settings,customWords){normalizeIdentityGame(game);if(game.phase==="turn")game.history.push({uid:game.order[game.turnIndex],text:"brak pytania",type:"miss",answer:"CZAS"});else if(game.phase==="responses")game.history.push({...game.pending,answer:"CZAS"});advance(game,settings,customWords);}
};
export function renderIdentityLobbySettings(room,isHost){const s={...identityDefaults,...room.settings};return`<div class="impostor-settings-grid">
<label>Kategoria<select data-identity-setting="category" ${isHost?"":"disabled"}>${["Wszystkie",...identityCategoryNames].map(x=>`<option ${s.category===x?"selected":""}>${x}</option>`).join("")}</select></label>
<label>Czas tury <b>${s.turnTime}s</b><input data-identity-setting="turnTime" type="range" min="20" max="90" step="5" value="${s.turnTime}" ${isHost?"":"disabled"}></label>
<label>Liczba rund<select data-identity-setting="rounds" ${isHost?"":"disabled"}>${[1,2,3,4,5,6].map(n=>`<option ${s.rounds===n?"selected":""}>${n}</option>`).join("")}</select></label>
<label>Odpowiedzi<select data-identity-setting="responseMode" ${isHost?"":"disabled"}><option value="binary" ${s.responseMode==="binary"?"selected":""}>TAK / NIE</option><option value="extended" ${s.responseMode==="extended"?"selected":""}>TAK / NIE / NIE WIEM / CZĘŚCIOWO</option></select></label>
<label class="check"><input data-identity-setting="oneGuess" type="checkbox" ${s.oneGuess?"checked":""} ${isHost?"":"disabled"}> Jedna próba zgadnięcia na turę</label>
<label class="check"><input data-identity-setting="newAfterGuess" type="checkbox" ${s.newAfterGuess?"checked":""} ${isHost?"":"disabled"}> Nowa postać po trafieniu</label>
<label class="check"><input data-identity-setting="endAfterRounds" type="checkbox" ${s.endAfterRounds?"checked":""} ${isHost?"":"disabled"}> Koniec po X rundach</label>
<label class="check"><input data-identity-setting="playerWordsEnabled" type="checkbox" ${s.playerWordsEnabled?"checked":""} ${isHost?"":"disabled"}> Hasła graczy</label></div>
${s.playerWordsEnabled?`<div class="custom-words"><label>Twoje własne hasła (1-5, oddziel przecinkami)</label><div class="row"><input id="identity-custom-words" value="${escapeHtml((room.customWords?.[room.viewerUid]||[]).join(", "))}" placeholder="np. Shrek, lodówka, Warszawa"><button id="save-identity-words">Zapisz hasła</button></div></div>`:""}`;}
export function stopIdentityTimer(){clearInterval(timerId);timerId=null;lastCountdown=null;}
const timer=g=>`<div class="timer-box"><b id="identity-timer">${Math.max(0,Math.ceil((g.phaseEndsAt-now())/1000))}s</b></div>`;
function identityBoard(game,accounts,currentUser,active){
  return `<section class="identity-board">${game.order.map(uid=>`<article class="identity-player-card ${uid===active?"active-identity-card":""} ${uid===currentUser?"own-identity-card":""}">
    <span class="identity-card-pin"></span>
    ${avatarHtml(accounts[uid],"identity-avatar")}
    <span class="identity-card-name"><span class="nick ${accounts[uid]?.selectedNickEffect||"defaultNick"}">${escapeHtml(accounts[uid]?.nick||"Gracz")}</span>${levelBadgeHtml(accounts[uid])}</span>
    <div class="identity-card-word">${uid===currentUser?"???":escapeHtml(game.words[uid])}</div>
    <small>${uid===currentUser?"Twoja karta jest tajna":`${game.scores[uid]} pkt`}</small>
  </article>`).join("")}</section>`;
}
export function renderIdentityGame(root,{room,accounts,currentUser},actions){stopIdentityTimer();const g=room.game,s={...identityDefaults,...room.settings};g.history ||= [];g.responses ||= {};g.scores ||= Object.fromEntries(room.players.map(uid=>[uid,0]));g.order ||= room.players;g.words ||= {};const active=g.order[g.turnIndex],me=active===currentUser;if(g.phase==="results")Effects.play("roundWin",`${room.roomId}:identity:results`);const answers=s.responseMode==="binary"?["TAK","NIE"]:["TAK","NIE","NIE WIEM","CZĘŚCIOWO"];
const main=g.phase==="results"?`<section class="panel center"><h1>Koniec gry</h1><div class="final-ranking">${Object.entries(g.scores).sort((a,b)=>b[1]-a[1]).map(([uid,n],index)=>`<article><b>#${index+1}</b>${mini(accounts[uid])}<strong>${n} pkt</strong></article>`).join("")}</div><button class="primary" id="identity-again">Wróć do lobby</button></section>`:`<section class="panel identity-main"><div class="game-top"><div><p class="eyebrow">RUNDA ${g.round}/${s.rounds}</p><h1>${escapeHtml(accounts[active]?.nick)} zgaduje</h1></div>${timer(g)}</div><div class="identity-turn-token">${me?"Twoja kolej. Patrz na karty znajomych i odkryj własną postać.":`${escapeHtml(accounts[active]?.nick||"Gracz")} próbuje odkryć swoją kartę.`}</div>${g.phase==="turn"?(me?`<form id="identity-form"><input id="identity-input" placeholder="zadaj pytanie lub zgadnij"><div class="choice-row"><button class="primary" data-identity-type="question">Zadaj pytanie</button><button data-identity-type="guess">Zgaduję</button></div></form>`:`<div class="waiting-state"><span class="waiting-pulse">…</span><h3>Teraz odpowiada ${escapeHtml(accounts[active]?.nick||"inny gracz")}</h3><p>Czekaj na pytanie. Gdy się pojawi, wybierzesz odpowiedź dla aktywnego gracza.</p></div>`):(me?`<p>Twoje pytanie: <b>${escapeHtml(g.pending.text)}</b></p><div class="waiting-state"><span class="waiting-pulse">…</span><h3>Czekamy na odpowiedzi grupy</h3><p>Znajomi odpowiadają teraz na twoje pytanie.</p></div>`:`<p>${escapeHtml(g.pending.text)}</p>${currentUser in g.responses?`<div class="waiting-state"><span class="waiting-pulse">✓</span><h3>Twoja odpowiedź została zapisana</h3><p>Czekamy jeszcze na ${Math.max(0,g.order.length-1-Object.keys(g.responses).length)} graczy. Kolejna tura rozpocznie się automatycznie.</p></div>`:`<div class="choice-row">${answers.map(a=>`<button data-identity-response="${a}">${a}</button>`).join("")}</div>`}`)}</section>`;
root.innerHTML=`<main class="page identity-page board-shell enter"><section class="identity-table"><p class="eyebrow">STÓŁ GRACZY</p>${identityBoard(g,accounts,currentUser,active)}</section>${main}<section class="panel"><h3>Historia</h3><div class="clue-list">${g.history.slice(-10).reverse().map(h=>`<div class="clue"><b>${escapeHtml(accounts[h.uid]?.nick)}</b><span>${escapeHtml(h.text)}</span><small>${escapeHtml(h.answer)}</small></div>`).join("")||'<p class="muted">Brak pytań.</p>'}</div></section><button class="ghost" id="leave-room">Wyjdź</button></main>`;
$("#leave-room").addEventListener("click",actions.leaveRoom);$("#identity-again")?.addEventListener("click",actions.returnToRoom);root.querySelectorAll("[data-identity-type]").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();actions.identitySubmit($("#identity-input").value,b.dataset.identityType);}));root.querySelectorAll("[data-identity-response]").forEach(b=>b.addEventListener("click",()=>actions.identityRespond(b.dataset.identityResponse)));if(g.phase!=="results")startTimer(actions);}
function startTimer(actions){timerId=setInterval(()=>{const el=$("#identity-timer");if(!el)return;const left=Math.max(0,Number(el.textContent.replace("s",""))-1);el.textContent=`${left}s`;if(left>0&&left<=3&&lastCountdown!==left){lastCountdown=left;Audio.play("countdown");}if(!left){stopIdentityTimer();actions.identityTimeout();}},1000);}
