import { escapeHtml } from "./utils.js?v=20260822-1";

export const markerDefaults = { boardSize:8, numberMax:50, markerSkin:"defaultMarker" };
const MARKER_TURN_TIME = 10;
const skins = { defaultMarker:"#171923", redMarker:"#ef476f", blueMarker:"#3b82f6", neonMarker:"#35f5ff", rainbowMarker:"#d946ef" };
const sizeOptions=[8,10,12], rangeOptions=[20,30,40,50,60,70,80,90,100];
const shuffle=list=>[...list].sort(()=>Math.random()-.5);
const ensureMarkerState=game=>{game=game&&typeof game==="object"?game:{};const size=[8,10,12].includes(Number(game.size))?Number(game.size):8,max=[20,30,40,50,60,70,80,90,100].includes(Number(game.numberMax))?Number(game.numberMax):50,total=size*size;const validNumbers=Array.isArray(game.numbers)&&game.numbers.length===total&&game.numbers.every(value=>value!==null&&value!==""&&Number.isFinite(Number(value))&&Number(value)>=0&&Number(value)<=max);if(!validNumbers)game.numbers=shuffle(Array.from({length:total},(_,i)=>i%(max+1)));game.size=size;game.numberMax=max;game.phase=["select","draw","result"].includes(game.phase)?game.phase:"select";if(game.phase==="select"){game.phaseEndsAt=Number.isFinite(Number(game.phaseEndsAt))&&Number(game.phaseEndsAt)>0?Number(game.phaseEndsAt):Date.now()+MARKER_TURN_TIME*1000;}else game.phaseEndsAt=0;game.marked=game.marked&&typeof game.marked==="object"&&!Array.isArray(game.marked)?game.marked:{};game.coverage=game.coverage&&typeof game.coverage==="object"&&!Array.isArray(game.coverage)?game.coverage:{};game.players=Array.isArray(game.players)?game.players.filter(Boolean).slice(0,2):[];game.players.forEach(uid=>{if(!game.coverage[uid]||typeof game.coverage[uid]!=="object"||Array.isArray(game.coverage[uid]))game.coverage[uid]={};});if(!game.players.includes(game.turnUid))game.turnUid=game.players[0]||"";if(game.selectedCell!=null&&(!Number.isInteger(Number(game.selectedCell))||Number(game.selectedCell)<0||Number(game.selectedCell)>=total)){game.selectedCell=null;game.drawerUid="";game.seekerUid="";if(game.phase==="draw")game.phase="select";}return game;};

export function createMarkerGame(players,settings={}) { const size=sizeOptions.includes(Number(settings.boardSize))?Number(settings.boardSize):8,max=rangeOptions.includes(Number(settings.numberMax))?Number(settings.numberMax):50,total=size*size;return {mode:"marker",phase:"select",size,numberMax:max,numbers:shuffle(Array.from({length:total},(_,i)=>i%(max+1))),turnUid:players[Math.floor(Math.random()*2)],drawerUid:"",seekerUid:"",selectedCell:null,marked:{},coverage:Object.fromEntries(players.map(uid=>[uid,{}])),players:players.slice(0,2),winner:"",phaseEndsAt:Date.now()+MARKER_TURN_TIME*1000}; }
const opponent=(game,uid)=>game.players.find(player=>player!==uid)||game.players[0];
function startTimer(game){game.phaseEndsAt=Date.now()+MARKER_TURN_TIME*1000;}
function swapRoles(game){ const next=game.seekerUid||opponent(game,game.turnUid);game.turnUid=next;game.drawerUid="";game.seekerUid="";game.selectedCell=null;game.phase="select";startTimer(game); }
export const MarkerEngine={ select(game,uid,cell){ensureMarkerState(game);if(game.phase!=="select"||game.turnUid!==uid||game.marked[cell])return "To nie jest Twoja kolej.";game.selectedCell=Number(cell);game.drawerUid=uid;game.seekerUid=opponent(game,uid);game.phase="draw";game.phaseEndsAt=0;}, coverage(game,uid,ratio){ensureMarkerState(game);if(game.phase!=="draw"||game.drawerUid!==uid||game.selectedCell==null)return "Nie możesz teraz rysować.";const value=Math.max(0,Math.min(1,Number(ratio)||0));if(value<0.05)return "Narysuj krzyżyk na wybranym polu.";game.coverage[uid]={...(game.coverage[uid]||{}),[game.selectedCell]:value};}, find(game,uid,cell){ensureMarkerState(game);if(game.phase!=="draw"||game.seekerUid!==uid||game.selectedCell==null||!game.coverage[game.drawerUid]?.[game.selectedCell])return "Najpierw poczekaj na gotowy krzyżyk.";if(Number(cell)!==Number(game.selectedCell))return "To nie ta liczba — spróbuj jeszcze raz.";game.marked[game.selectedCell]=true;if(Object.keys(game.marked).length>=game.size*game.size){game.phase="result";game.winner=uid;game.finished=true;}else swapRoles(game);}, timeout(game){ensureMarkerState(game);if(game.phase==="result")return "Gra jest już zakończona.";if(game.phase!=="select")return "Nie ma teraz odliczania.";const available=game.numbers.map((value,index)=>value!=null&&!game.marked[index]?index:null).filter(index=>index!==null);const cell=available[Math.floor(Math.random()*available.length)];if(cell==null){game.phase="result";game.finished=true;game.winner=game.turnUid;return;}return this.select(game,game.turnUid,cell);}};
function drawCommon(canvas,game){const ctx=canvas.getContext("2d"),size=canvas.width,cell=size/game.size;ctx.clearRect(0,0,size,size);ctx.font=`700 ${Math.max(13,cell*.27)}px "Comic Sans MS",cursive`;ctx.textAlign="center";ctx.textBaseline="middle";game.numbers.forEach((number,index)=>{if(number==null)return;const x=(index%game.size)*cell+cell/2,y=Math.floor(index/game.size)*cell+cell/2,found=Boolean(game.marked[index]);ctx.fillStyle=found?"#8b93a1":"#252b3b";ctx.fillText(number,x,y);if(found){ctx.strokeStyle="#626b78";ctx.lineWidth=Math.max(3,cell*.045);ctx.beginPath();ctx.moveTo(x-cell*.33,y);ctx.lineTo(x+cell*.33,y);ctx.stroke();}});}
function drawSheet(canvas,game,uid,skin){const ctx=canvas.getContext("2d"),size=canvas.width,cell=size/game.size;ctx.clearRect(0,0,size,size);const color=skins[skin]||skins.defaultMarker;Object.entries(game.coverage[uid]||{}).forEach(([index,ratio])=>{if(!ratio)return;const x=(Number(index)%game.size)*cell,y=Math.floor(Number(index)/game.size)*cell;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=Math.max(4,cell*.1);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(x+cell*.18,y+cell*.18);ctx.lineTo(x+cell*.82,y+cell*.82);ctx.moveTo(x+cell*.82,y+cell*.18);ctx.lineTo(x+cell*.18,y+cell*.82);ctx.stroke();ctx.restore();});}
let markerTimer = 0;
const markerDrafts=new Map();
const markerDraftPixels=new Map();
export function stopMarkerTimer(){clearTimeout(markerTimer);markerTimer=0;}
function bindCanvases(root,game,uid,actions,expected,draftKey){const common=root.querySelector("[data-marker-board]");if(common){drawCommon(common,game);common.addEventListener("click",event=>{const rect=common.getBoundingClientRect(),cell=Math.floor((event.clientX-rect.left)/(rect.width/game.size))+Math.floor((event.clientY-rect.top)/(rect.height/game.size))*game.size;if(game.marked[cell])return;if(game.phase==="select")actions.markerSelect(cell,expected);else if(game.phase==="draw"&&game.seekerUid===uid)actions.markerFind(cell,expected);});}const sheet=root.querySelector("[data-marker-sheet]");if(!sheet||game.drawerUid!==uid||game.selectedCell==null)return;const ctx=sheet.getContext("2d"),rect=()=>sheet.getBoundingClientRect(),alreadyDrawn=Boolean(game.coverage[uid]?.[game.selectedCell]);let drawing=false;const point=e=>{const r=rect();return {x:(e.clientX-r.left)*sheet.width/r.width,y:(e.clientY-r.top)*sheet.height/r.height};};if(!alreadyDrawn){sheet.addEventListener("pointerdown",e=>{drawing=true;sheet.setPointerCapture(e.pointerId);const p=point(e);ctx.strokeStyle=skins[game.markerSkin]||skins.defaultMarker;ctx.lineWidth=Math.max(4,sheet.width/game.size*.1);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(p.x,p.y);});sheet.addEventListener("pointermove",e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();});const finish=()=>{if(!drawing)return;drawing=false;const pixels=ctx.getImageData(0,0,sheet.width,sheet.height);markerDraftPixels.set(draftKey,pixels);markerDrafts.set(draftKey,sheet.toDataURL());let ink=0;for(let i=3;i<pixels.data.length;i+=4)if(pixels.data[i]>35)ink++;actions.markerCoverage(Math.min(1,ink/(sheet.width*sheet.height)),expected);};sheet.addEventListener("pointerup",finish);sheet.addEventListener("pointercancel",finish);}drawSheet(sheet,game,uid,game.markerSkin);const draftPixels=markerDraftPixels.get(draftKey);if(draftPixels){ctx.putImageData(draftPixels,0,0);}else{const draft=markerDrafts.get(draftKey);if(draft){const image=new Image();image.onload=()=>ctx.drawImage(image,0,0,sheet.width,sheet.height);image.src=draft;}}if(alreadyDrawn){markerDraftPixels.delete(draftKey);markerDrafts.delete(draftKey);}}
export function renderMarkerGame(root,{room,currentUser,accounts},actions){stopMarkerTimer();const game=ensureMarkerState(room?.game||{});const safeAccounts=accounts&&typeof accounts==="object"?accounts:{};if(game.phase==="result"){root.innerHTML=`<main class="page marker-page"><section class="panel marker-panel center"><p class="eyebrow">MARKER · WYNIKI</p><h1>${escapeHtml(safeAccounts[game.winner]?.nick||"Gracz")} wygrał!</h1><p class="muted">Wszystkie pola zostały poprawnie oznaczone.</p><button class="primary" id="marker-room">Wróć do lobby</button></section></main>`;root.querySelector("#marker-room").addEventListener("click",actions.returnToRoom);return;}const expected={phase:game.phase,selectedCell:game.selectedCell,phaseEndsAt:game.phaseEndsAt};const isDrawer=game.drawerUid===currentUser;const isSeeker=game.seekerUid===currentUser;const hasDraft=Boolean(isDrawer&&game.selectedCell!=null&&game.coverage[currentUser]?.[game.selectedCell]);const showBoard=game.phase==="select"||isSeeker;const draftKey=`${room?.roomId||room?.id||room?.code||"marker"}:${currentUser}:${game.selectedCell}`;root.innerHTML=`<main class="page marker-page enter"><section class="panel marker-panel"><p class="eyebrow">MARKER · ${game.size}×${game.size} · 0-${game.numberMax}</p><h1>${game.phase==="select"?(game.turnUid===currentUser?"Wybierz liczbę":"Przeciwnik wybiera liczbę"):isDrawer?(hasDraft?"Krzyżyk zapisany":"Narysuj krzyżyk na swoim polu"):"Znajdź wskazaną liczbę"}</h1><div class="marker-status">${game.phase==="draw"&&game.selectedCell!=null?(isDrawer?`<b>Wybrana liczba: ${game.numbers[game.selectedCell]}</b>`:`<b>Znajdź i kliknij liczbę: ${game.numbers[game.selectedCell]}</b>`):`<span>Pola: ${Object.keys(game.marked||{}).length}/${game.size*game.size}</span>`}</div>${showBoard?`<canvas class="marker-board" data-marker-board width="720" height="720" aria-label="Wspólna plansza"></canvas>`:`<div class="marker-waiting"><p class="muted">Krzyżyk jest gotowy. Czekamy, aż przeciwnik znajdzie liczbę.</p></div>`}${isDrawer?`<div class="marker-sheet-wrap"><p class="eyebrow">TWOJA KARTKA</p><canvas class="marker-sheet" data-marker-sheet width="720" height="720"></canvas>${hasDraft?`<p class="tiny">Iks zapisany. Czekaj, aż drugi gracz znajdzie liczbę.</p>`:""}</div>`:""}<p class="tiny">${game.phase==="select"?"Masz 10 sekund na wybranie liczby.":"Nie ma limitu czasu — graj spokojnie."}</p></section></main>`;bindCanvases(root,game,currentUser,actions,expected,draftKey);if(game.phase==="select")markerTimer=setTimeout(()=>actions.markerTimeout(expected),Math.max(100,Number(game.phaseEndsAt||0)-Date.now()+50));}
export function renderMarkerLobbySettings(room,isHost){const s=room.settings||markerDefaults;return `<div class="marker-settings"><label>Rozmiar planszy <select data-marker-setting="boardSize" ${isHost?"":"disabled"}>${sizeOptions.map(value=>`<option value="${value}" ${Number(s.boardSize)===value?"selected":""}>${value}×${value}</option>`).join("")}</select></label><label>Zakres liczb <select data-marker-setting="numberMax" ${isHost?"":"disabled"}>${rangeOptions.map(value=>`<option value="${value}" ${Number(s.numberMax)===value?"selected":""}>0-${value}</option>`).join("")}</select></label><p class="muted">Pierwszy gracz jest losowany automatycznie. Domyślny marker: czarny.</p></div>`;}
