import { escapeHtml } from "./utils.js?v=20260613-2";

export const markerDefaults = { boardSize:8, numberMax:50, markerSkin:"defaultMarker" };
const MARKER_TURN_TIME = 10;
const skins = { defaultMarker:"#171923", redMarker:"#ef476f", blueMarker:"#3b82f6", neonMarker:"#35f5ff", rainbowMarker:"#d946ef" };
const sizeOptions=[8,10,12], rangeOptions=[20,30,40,50,60,70,80,90,100];
const shuffle=list=>[...list].sort(()=>Math.random()-.5);

export function createMarkerGame(players,settings={}) { const size=sizeOptions.includes(Number(settings.boardSize))?Number(settings.boardSize):8,max=rangeOptions.includes(Number(settings.numberMax))?Number(settings.numberMax):50,total=size*size;return {mode:"marker",phase:"select",size,numberMax:max,numbers:shuffle(Array.from({length:total},(_,i)=>i%(max+1))),turnUid:players[Math.floor(Math.random()*2)],drawerUid:"",seekerUid:"",selectedCell:null,marked:{},coverage:Object.fromEntries(players.map(uid=>[uid,{}])),players:players.slice(0,2),winner:"",phaseEndsAt:Date.now()+MARKER_TURN_TIME*1000}; }
const opponent=(game,uid)=>game.players.find(player=>player!==uid)||game.players[0];
function startTimer(game){game.phaseEndsAt=Date.now()+MARKER_TURN_TIME*1000;}
function swapRoles(game){ const next=game.seekerUid||opponent(game,game.turnUid);game.turnUid=next;game.drawerUid="";game.seekerUid="";game.selectedCell=null;game.phase="select";startTimer(game); }
export const MarkerEngine={ select(game,uid,cell){if(game.phase!=="select"||game.turnUid!==uid||game.marked[cell])return "To nie jest Twoja kolej.";game.selectedCell=Number(cell);game.drawerUid=uid;game.seekerUid=opponent(game,uid);game.phase="draw";startTimer(game);}, coverage(game,uid,ratio){if(game.phase!=="draw"||game.drawerUid!==uid||game.selectedCell==null)return "Nie możesz teraz rysować.";const value=Math.max(0,Math.min(1,Number(ratio)||0));game.coverage[uid]={...(game.coverage[uid]||{}),[game.selectedCell]:value};if(value>=0.18){game.marked[game.selectedCell]=true;if(Object.keys(game.marked).length>=game.size*game.size){game.phase="result";game.winner=uid;game.finished=true;}else swapRoles(game);}}, find(game,uid){if(game.phase!=="draw"||game.seekerUid!==uid||game.selectedCell==null||!game.coverage[game.drawerUid]?.[game.selectedCell])return "Najpierw zakryj pole markerem.";game.marked[game.selectedCell]=true;if(Object.keys(game.marked).length>=game.size*game.size){game.phase="result";game.winner=uid;game.finished=true;}else swapRoles(game);}, timeout(game){if(game.phase==="result")return "Gra jest już zakończona.";if(game.phase==="select"){const available=game.numbers.map((value,index)=>value!=null&&!game.marked[index]?index:null).filter(index=>index!==null);const cell=available[Math.floor(Math.random()*available.length)];if(cell==null){game.phase="result";game.finished=true;game.winner=game.turnUid;return;}return this.select(game,game.turnUid,cell);}swapRoles(game);}};
function drawCommon(canvas,game){const ctx=canvas.getContext("2d"),size=canvas.width,cell=size/game.size;ctx.clearRect(0,0,size,size);ctx.font=`700 ${Math.max(13,cell*.27)}px "Comic Sans MS",cursive`;ctx.textAlign="center";ctx.textBaseline="middle";game.numbers.forEach((number,index)=>{if(number==null)return;const x=(index%game.size)*cell+cell/2,y=Math.floor(index/game.size)*cell+cell/2;ctx.fillStyle=game.marked[index]?"#86efac":"#252b3b";ctx.fillText(number,x,y);});}
function drawSheet(canvas,game,uid,skin){const ctx=canvas.getContext("2d"),size=canvas.width,cell=size/game.size;ctx.clearRect(0,0,size,size);const color=skins[skin]||skins.defaultMarker;Object.entries(game.coverage[uid]||{}).forEach(([index,ratio])=>{if(!ratio)return;const x=(Number(index)%game.size)*cell,y=Math.floor(Number(index)/game.size)*cell;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=Math.max(4,cell*.1);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(x+cell*.18,y+cell*.18);ctx.lineTo(x+cell*.82,y+cell*.82);ctx.moveTo(x+cell*.82,y+cell*.18);ctx.lineTo(x+cell*.18,y+cell*.82);ctx.stroke();ctx.restore();});}
let markerTimer = 0;
export function stopMarkerTimer(){clearTimeout(markerTimer);markerTimer=0;}
function bindCanvases(root,game,uid,actions,expected){const common=root.querySelector("[data-marker-board]");if(common){drawCommon(common,game);common.addEventListener("click",event=>{const rect=common.getBoundingClientRect(),cell=Math.floor((event.clientX-rect.left)/(rect.width/game.size))+Math.floor((event.clientY-rect.top)/(rect.height/game.size))*game.size;actions.markerSelect(cell,expected);});}const sheet=root.querySelector("[data-marker-sheet]");if(!sheet||game.drawerUid!==uid||game.selectedCell==null)return;const ctx=sheet.getContext("2d"),rect=()=>sheet.getBoundingClientRect();let drawing=false;const point=e=>{const r=rect();return {x:(e.clientX-r.left)*sheet.width/r.width,y:(e.clientY-r.top)*sheet.height/r.height};};sheet.addEventListener("pointerdown",e=>{drawing=true;sheet.setPointerCapture(e.pointerId);const p=point(e);ctx.strokeStyle=skins[game.markerSkin]||skins.defaultMarker;ctx.lineWidth=Math.max(4,sheet.width/game.size*.1);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(p.x,p.y);});sheet.addEventListener("pointermove",e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();});sheet.addEventListener("pointerup",()=>{if(!drawing)return;drawing=false;const size=sheet.width/game.size,index=game.selectedCell,x=(index%game.size)*size,y=Math.floor(index/game.size)*size;const pixels=ctx.getImageData(x,y,size,size).data;let ink=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>35)ink++;actions.markerCoverage(Math.min(1,ink/(size*size)),expected);});drawSheet(sheet,game,uid,game.markerSkin);}
export function renderMarkerGame(root,{room,currentUser,accounts},actions){stopMarkerTimer();const game=room.game;if(game.phase==="result"){root.innerHTML=`<main class="page marker-page"><section class="panel marker-panel center"><p class="eyebrow">MARKER · WYNIKI</p><h1>${escapeHtml(accounts[game.winner]?.nick||"Gracz")} wygrał!</h1><p class="muted">Wszystkie pola zostały poprawnie oznaczone.</p><button class="primary" id="marker-room">Wróć do lobby</button></section></main>`;root.querySelector("#marker-room").addEventListener("click",actions.returnToRoom);return;}const expected={phase:game.phase,selectedCell:game.selectedCell,phaseEndsAt:game.phaseEndsAt};const isDrawer=game.drawerUid===currentUser;const isSeeker=game.seekerUid===currentUser;const showBoard=game.phase==="select"||isSeeker;root.innerHTML=`<main class="page marker-page enter"><section class="panel marker-panel"><p class="eyebrow">MARKER · ${game.size}×${game.size} · 0-${game.numberMax}</p><h1>${game.phase==="select"?(game.turnUid===currentUser?"Wybierz liczbę":"Przeciwnik wybiera liczbę"):isDrawer?"Narysuj krzyżyk na swoim polu":"Znajdź wskazaną liczbę"}</h1><div class="marker-status">${game.phase==="draw"&&game.selectedCell!=null?`<b>Cel: ${game.numbers[game.selectedCell]}</b>`:`<span>Pola: ${Object.keys(game.marked||{}).length}/${game.size*game.size}</span>`}</div>${showBoard?`<canvas class="marker-board" data-marker-board width="720" height="720" aria-label="Wspólna plansza"></canvas>`:`<div class="marker-waiting"><p class="muted">Krzyżyk jest gotowy. Czekamy na sprawdzenie liczby.</p></div>`}${isDrawer?`<div class="marker-sheet-wrap"><p class="eyebrow">TWOJA KARTKA</p><canvas class="marker-sheet" data-marker-sheet width="720" height="720"></canvas></div>`:""}${game.phase==="draw"&&isSeeker?`<button class="primary" id="marker-find">Znalazłem liczbę</button>`:""}<p class="tiny">Masz 10 sekund na wykonanie ruchu.</p></section></main>`;bindCanvases(root,game,currentUser,actions,expected);root.querySelector("#marker-find")?.addEventListener("click",()=>actions.markerFind(expected));markerTimer=setTimeout(()=>actions.markerTimeout(expected),Math.max(100,Number(game.phaseEndsAt||0)-Date.now()+50));}
export function renderMarkerLobbySettings(room,isHost){const s=room.settings||markerDefaults;return `<div class="marker-settings"><label>Rozmiar planszy <select data-marker-setting="boardSize" ${isHost?"":"disabled"}>${sizeOptions.map(value=>`<option value="${value}" ${Number(s.boardSize)===value?"selected":""}>${value}×${value}</option>`).join("")}</select></label><label>Zakres liczb <select data-marker-setting="numberMax" ${isHost?"":"disabled"}>${rangeOptions.map(value=>`<option value="${value}" ${Number(s.numberMax)===value?"selected":""}>0-${value}</option>`).join("")}</select></label><p class="muted">Pierwszy gracz jest losowany automatycznie. Domyślny marker: czarny.</p></div>`;}
