import { avatarHtml, escapeHtml } from "./utils.js?v=20260613-2";

export const mathematicsDefaults = { questionCount: 10, questionTime: 45, testTime: 300, mathematicsVariant: "single", answerMode: "abcd", showOpponentAnswers: true, categories: ["addition", "subtraction", "multiplication", "division"] };
const labels = { addition:"Dodawanie", subtraction:"Odejmowanie", multiplication:"Mnożenie", division:"Dzielenie", powers:"Potęgi", roots:"Pierwiastki", fractions:"Ułamki", percentages:"Procenty", equations:"Równania", areas:"Pola figur", perimeters:"Obwody figur", volumes:"Objętości", geometry:"Geometria", order:"Kolejność działań" };
const categories = Object.keys(labels);
const rand = (min,max) => Math.floor(Math.random()*(max-min+1))+min;
const gcd = (a,b) => { while(b){ const t=a%b; a=b; b=t; } return Math.abs(a)||1; };
const fraction = (n,d) => { const g=gcd(n,d), sign=d<0?-1:1; return `${sign*n/g}/${sign*d/g}`; };
const numberText = value => Number.isInteger(value) ? String(value) : String(Number(value.toFixed(2)));
const task = (prompt, answer, distractors, category, display=answer) => { const opts=[answer,...distractors].map(String); return { prompt, answer:String(answer), display:String(display), options:opts.sort(()=>Math.random()-.5), category }; };

function makeTask(category, level) {
  const n=2+level, a=rand(2+n,8+n*3), b=rand(2+n,8+n*2), c=rand(2,n+5);
  if(category==="addition") return task(`${a} + ${b} = ?`,a+b,[a-b,a+b+rand(1,3),a*b],category);
  if(category==="subtraction") return task(`${a} − ${b} = ?`,a-b,[b-a,a+b,a-b+rand(1,4)],category);
  if(category==="multiplication") return task(`${a} × ${b} = ?`,a*b,[a+b,a*b+a,a*(b-1)],category);
  if(category==="division"){ const result=rand(2+n,10+n), divisor=rand(2,8+n); return task(`${result*divisor} ÷ ${divisor} = ?`,result,[result+1,result-1,result*divisor],category); }
  if(category==="powers"){ const base=rand(2,Math.min(8,3+level)); const exp=level>5?3:2; const result=base**exp; return task(`${base}${exp===2?"²":"³"} = ?`,result,[base*exp,result+base,result-base],category); }
  if(category==="roots"){ const root=rand(2,Math.min(15,5+level)), result=root*root; return task(`√${result} = ?`,root,[root+1,result-root,root-1],category); }
  if(category==="fractions"){ const d=rand(2,5+level), x=rand(2,6+level), n=x*rand(2,4); const reduced=fraction(n,d), parts=reduced.split("/"); return task(`${n}/${d} = ?`,reduced,[fraction(n+1,d),fraction(n,d+1),fraction(n-1,d)],category,`${parts[0]}/${parts[1]}`); }
  if(category==="percentages"){ const percent=[10,20,25,50,75][rand(0,4)], base=rand(2,10+level)*10, result=base*percent/100; return task(`${percent}% z ${base} = ?`,result,[result+10,result-percent,result*2],category); }
  if(category==="equations"){ const x=rand(2,8+level), coefficient=rand(2,5+Math.min(level,5)), constant=rand(1,9+level), result=coefficient*x+constant; return task(`${coefficient}x + ${constant} = ${result}.  x = ?`,x,[x+1,x-1,result-coefficient],category); }
  if(category==="areas"){ const w=rand(2,8+level), h=rand(2,8+level); return task(`Pole prostokąta ${w} × ${h} = ?`,w*h,[w+h,w*h+w,(w+h)*2],category); }
  if(category==="perimeters"){ const w=rand(2,8+level), h=rand(2,8+level), result=2*(w+h); return task(`Obwód prostokąta ${w} × ${h} = ?`,result,[w+h,result+w,result-2],category); }
  if(category==="volumes"){ const w=rand(2,5+level), h=rand(2,5+level), d=rand(2,4+level), result=w*h*d; return task(`Objętość prostopadłościanu ${w} × ${h} × ${d} = ?`,result,[w+h+d,result+w,w*h],category); }
  if(category==="geometry"){ const angles=level>4?5:4, result=(angles-2)*180; return task(`Suma kątów wewnętrznych ${angles}-kąta = ?`,result,[angles*180,(angles-1)*180,360],category); }
  if(category==="order"){ const result=a+b*c; return task(`${a} + ${b} × ${c} = ?`,result,[(a+b)*c,a+b+c,a*b+c],category); }
  return makeTask("addition",level);
}

export function createMathematicsGame(players, settings={}) {
  const count=Math.max(3,Math.min(20,Number(settings.questionCount)||10)), chosen=(settings.categories||mathematicsDefaults.categories).filter(category=>categories.includes(category));
  const pool=chosen.length?chosen:mathematicsDefaults.categories;
  const mathematicsVariant=settings.mathematicsVariant==="full-test"?"full-test":"single", testTime=Math.max(60,Number(settings.testTime)||300), questions=Array.from({length:count},(_,i)=>makeTask(pool[rand(0,pool.length-1)],i));
  return { mode:"mathematics", variant:mathematicsVariant, phase:mathematicsVariant==="full-test"?"test":"question", questionIndex:0, questions, answers:{}, testAnswers:Object.fromEntries(players.map(uid=>[uid,[]])), progress:Object.fromEntries(players.map(uid=>[uid,0])), completed:Object.fromEntries(players.map(uid=>[uid,false])), history:[], scores:Object.fromEntries(players.map(uid=>[uid,0])), playerCount:players.length, answerMode:settings.answerMode==="input"?"input":"abcd", showOpponentAnswers:settings.showOpponentAnswers!==false, questionTime:Math.max(10,Number(settings.questionTime)||45), testTime, testEndsAt:Date.now()+testTime*1000, phaseEndsAt:Date.now()+Math.max(10,Number(settings.questionTime)||45)*1000 };
}

const parseAnswer = value => { let text=String(value??"").trim().replace(/,/g,".").replace(/×/g,"*").replace(/÷/g,"/").replace(/²/g,"**2").replace(/³/g,"**3").replace(/xʸ/g,"^").replace(/π/g,String(Math.PI)); if(/^√\s*\d+(?:\.\d+)?$/.test(text))return Math.sqrt(Number(text.slice(1))); text=text.replace(/\^/g,"**"); if(!text)return null; if(/^[-+]?\d+(?:\.\d+)?\s*\/\s*[-+]?\d+(?:\.\d+)?$/.test(text)){const [n,d]=text.split("/").map(Number);return d? n/d:null;} if(!/^[0-9+\-*/(). *]+$/.test(text))return null; try{return Number(Function(`"use strict"; return (${text})`)());}catch{return null;} };
const isCorrect = (value,answer) => { const left=parseAnswer(value), right=parseAnswer(answer); return left!=null&&right!=null&&Math.abs(left-right)<0.001; };
const renderMathSettingsBase=renderMathematicsLobbySettings;
renderMathematicsLobbySettings=(room,isHost)=>{const html=renderMathSettingsBase(room,isHost),s={...mathematicsDefaults,...(room.settings||{})},variant=s.mathematicsVariant==="full-test"?"full-test":"single";return html.replace("<fieldset>",`<label class="math-variant-setting">Podtryb<select data-math-setting="mathematicsVariant" ${isHost?"":"disabled"}><option value="single" ${variant==="single"?"selected":""}>1 pytanie na raz</option><option value="full-test" ${variant==="full-test"?"selected":""}>Cały test</option></select></label>${variant==="full-test"?`<label class="math-test-time-setting">Czas na cały test<select data-math-setting="testTime" ${isHost?"":"disabled"}><option value="180" ${Number(s.testTime)===180?"selected":""}>3 min</option><option value="300" ${Number(s.testTime)!==180&&Number(s.testTime)!==600?"selected":""}>5 min</option><option value="600" ${Number(s.testTime)===600?"selected":""}>10 min</option></select></label>`:""}<label class="math-visibility-setting"><span>Pokazuj odpowiedzi przeciwników</span><input type="checkbox" data-math-setting="showOpponentAnswers" ${s.showOpponentAnswers!==false?"checked":""} ${isHost?"":"disabled"}></label><fieldset>`);};
const renderMathematicsGameBase=renderMathematicsGame;
function renderFullTestGame(root,{room,accounts,currentUser},actions){const game=room.game;stopMathematicsTimer();if(game.phase==="result"){const rows=Object.entries(game.scores||{}).sort(([,a],[,b])=>b-a).map(([uid,score],i)=>`<div class="math-result-row"><b>${i+1}. ${escapeHtml(accounts[uid]?.nick||"Gracz")}</b><strong>${score} pkt</strong></div>`).join("");root.innerHTML=`<main class="page mathematics-page"><section class="panel mathematics-panel center"><p class="eyebrow">MATEMATYKA · WYNIKI</p><h1>Ranking</h1><div class="math-results">${rows}</div><button class="primary" id="math-room">Wróć do lobby</button></section></main>`;root.querySelector("#math-room").addEventListener("click",actions.returnToRoom);return;}const index=Math.max(0,Number(game.progress?.[currentUser])||0),done=Boolean(game.completed?.[currentUser]),q=game.questions?.[index],expected={phase:game.phase,testEndsAt:game.testEndsAt};if(done||!q){root.innerHTML=`<main class="page mathematics-page enter"><section class="panel mathematics-panel center"><p class="eyebrow">MATEMATYKA · CAŁY TEST</p><h1>Test ukończony</h1><p class="muted">Twój wynik: <b>${game.scores?.[currentUser]||0}/${game.questions?.length||0}</b></p><p class="muted">Czekamy, aż pozostali gracze skończą.</p><strong data-math-countdown>${Math.max(0,Math.ceil((game.testEndsAt-Date.now())/1000))}s</strong></section></main>`;}else{root.innerHTML=`<main class="page mathematics-page enter"><section class="panel mathematics-panel"><p class="eyebrow">MATEMATYKA · CAŁY TEST · PYTANIE ${index+1}/${game.questions.length} · ${escapeHtml(labels[q.category])}</p><h1>${escapeHtml(q.prompt)}</h1>${game.answerMode==="abcd"?`<div class="math-options">${q.options.map((option,i)=>`<button class="math-option" data-math-full-answer="${i}">${escapeHtml(String(option))}</button>`).join("")}</div>`:`<input id="math-answer" placeholder="Wpisz odpowiedź"><div class="math-keypad"><button data-math-key="1">1</button><button data-math-key="2">2</button><button data-math-key="3">3</button><button data-math-key="backspace">⌫</button><button data-math-key="clear">C</button></div><button id="math-submit" class="primary">Odpowiedz</button>`}<div class="math-footer"><strong data-math-countdown>${Math.max(0,Math.ceil((game.testEndsAt-Date.now())/1000))}s</strong><span>${index}/${game.questions.length} ukończonych</span></div></section></main>`;root.querySelectorAll("[data-math-full-answer]").forEach(button=>button.addEventListener("click",()=>actions.mathematicsAnswer(button.dataset.mathFullAnswer,expected)));if(game.answerMode==="input")renderInput(root,actions,game,q,false,expected);}renderMathematicsGame.countdown=setInterval(()=>{const node=root.querySelector("[data-math-countdown]");if(node)node.textContent=`${Math.max(0,Math.ceil((game.testEndsAt-Date.now())/1000))}s`;},250);renderMathematicsGame.timer=setTimeout(()=>actions.mathematicsTimeout(expected),Math.max(100,game.testEndsAt-Date.now()+50));}
renderMathematicsGame=(root,context,actions)=>{const game=context?.room?.game;if(game?.variant==="full-test")return renderFullTestGame(root,context,actions);if(game?.phase==="question"&&(!Array.isArray(game.questions)||!game.questions[game.questionIndex]||!Array.isArray(game.questions[game.questionIndex].options))){game.phase="result";game.finished=true;}return renderMathematicsGameBase(root,context,actions);};
function normalizeGame(game, players = []) {
  game.answers = game.answers && typeof game.answers === "object" && !Array.isArray(game.answers) ? game.answers : {};
  game.history = Array.isArray(game.history) ? game.history : [];
  game.scores = game.scores && typeof game.scores === "object" && !Array.isArray(game.scores) ? game.scores : {};
  players.forEach(uid => { if (!(uid in game.scores)) game.scores[uid] = 0; });
  game.questions = Array.isArray(game.questions) ? game.questions : [];
  game.questionIndex = Math.max(0, Number(game.questionIndex) || 0);
  return game;
}
function advance(game, players) { normalizeGame(game, players); game.history.push({ questionIndex:game.questionIndex, answers:{...game.answers} }); if(game.questionIndex+1>=game.questions.length){game.phase="result";game.finished=true;return;} game.questionIndex+=1;game.answers={};game.phaseEndsAt=Date.now()+game.questionTime*1000; }
export const MathematicsEngine = { answer(game,uid,value,players){ normalizeGame(game, players); if(game.phase!=="question"||game.answers?.[uid]!=null)return "Odpowiedź została już wysłana."; const question=game.questions[game.questionIndex]; if(!question)return "Brak aktualnego pytania."; const answer=game.answerMode==="abcd"?question.options[Number(value)]:String(value); if(answer==null)return "Nieprawidłowa odpowiedź."; game.answers={...(game.answers||{}),[uid]:answer}; if(isCorrect(answer,question.answer))game.scores[uid]=(game.scores[uid]||0)+1; if(Object.keys(game.answers).length>=players.length)advance(game,players); }, timeout(game,players){ normalizeGame(game, players); if(game.phase!=="question")return; advance(game,players); } };

function normalizeFullTest(game,players=[]){game.variant="full-test";game.phase=game.phase==="result"?"result":"test";game.progress=game.progress&&typeof game.progress==="object"?game.progress:{};game.testAnswers=game.testAnswers&&typeof game.testAnswers==="object"?game.testAnswers:{};game.completed=game.completed&&typeof game.completed==="object"?game.completed:{};game.scores=game.scores&&typeof game.scores==="object"?game.scores:{};players.forEach(uid=>{if(!(uid in game.progress))game.progress[uid]=0;if(!Array.isArray(game.testAnswers[uid]))game.testAnswers[uid]=[];if(!(uid in game.completed))game.completed[uid]=false;if(!(uid in game.scores))game.scores[uid]=0;});game.testTime=Math.max(60,Number(game.testTime)||300);game.testEndsAt=Number(game.testEndsAt)||Date.now()+game.testTime*1000;return game;}
function answerFullTest(game,uid,value,players){normalizeFullTest(game,players);if(game.phase!=="test"||game.completed[uid])return "Test został już ukończony.";const index=Math.max(0,Number(game.progress[uid])||0),question=game.questions[index];if(!question){game.completed[uid]=true;return;}const answer=game.answerMode==="abcd"?question.options[Number(value)]:String(value);if(answer==null)return "Nieprawidłowa odpowiedź.";game.testAnswers[uid].push(answer);if(isCorrect(answer,question.answer))game.scores[uid]=(game.scores[uid]||0)+1;game.progress[uid]=index+1;if(game.progress[uid]>=game.questions.length)game.completed[uid]=true;if(players.length&&players.every(player=>game.completed[player])){game.phase="result";game.finished=true;}}
function timeoutFullTest(game,players){normalizeFullTest(game,players);if(game.phase==="test"){game.phase="result";game.finished=true;}}
const mathematicsAnswerBase=MathematicsEngine.answer;
MathematicsEngine.answer=(game,uid,value,players)=>game.variant==="full-test"?answerFullTest(game,uid,value,players):mathematicsAnswerBase(game,uid,value,players);
const mathematicsTimeoutBase=MathematicsEngine.timeout;
MathematicsEngine.timeout=(game,players)=>game.variant==="full-test"?timeoutFullTest(game,players):mathematicsTimeoutBase(game,players);

function answerAvatars(game,value,accounts){ if(game.showOpponentAnswers===false)return ""; return Object.entries(game.answers||{}).filter(([,answer])=>String(answer)===String(value)).map(([uid])=>`<span class="math-answer-avatar" data-tooltip="${escapeHtml(accounts[uid]?.nick||"Gracz")}">${avatarHtml(accounts[uid]||{nick:"Gracz"},"math-avatar")}</span>`).join(""); }
function renderInput(root,actions,game,question,answered,expected){ const field=root.querySelector("#math-answer"); root.querySelectorAll("[data-math-key]").forEach(button=>button.addEventListener("click",()=>{if(field.disabled)return; const key=button.dataset.mathKey; field.value=key==="backspace"?field.value.slice(0,-1):key==="clear"?"":field.value+key;field.focus();})); root.querySelector("#math-submit")?.addEventListener("click",()=>actions.mathematicsAnswer(field.value,expected)); }
export function renderMathematicsGame(root,{room,accounts,currentUser},actions){ const game=room.game; window.clearTimeout(renderMathematicsGame.timer);window.clearInterval(renderMathematicsGame.countdown); if(game.phase==="result"){ const rows=Object.entries(game.scores).sort(([,a],[,b])=>b-a).map(([uid,score],i)=>`<div class="math-result-row"><b>${i+1}. ${escapeHtml(accounts[uid]?.nick||"Gracz")}</b><strong>${score} pkt</strong></div>`).join("");root.innerHTML=`<main class="page mathematics-page"><section class="panel mathematics-panel center"><p class="eyebrow">MATEMATYKA · WYNIKI</p><h1>Ranking</h1><div class="math-results">${rows}</div><button class="primary" id="math-room">Wróć do lobby</button></section></main>`;root.querySelector("#math-room").addEventListener("click",actions.returnToRoom);return; }
  const q=game.questions[game.questionIndex], chosen=game.answers?.[currentUser], answered=chosen!=null, expected={phase:game.phase,phaseEndsAt:game.phaseEndsAt}; root.innerHTML=`<main class="page mathematics-page enter"><section class="panel mathematics-panel"><p class="eyebrow">MATEMATYKA · PYTANIE ${game.questionIndex+1}/${game.questions.length} · ${escapeHtml(labels[q.category])}</p><h1>${escapeHtml(q.prompt)}</h1>${game.answerMode==="abcd"?`<div class="math-options">${q.options.map((option,index)=>`<button class="math-option ${answered&&String(chosen)===String(option)?(isCorrect(option,q.answer)?"is-correct":"is-wrong"):""}" data-math-answer="${index}" ${answered?"disabled":""}><span>${escapeHtml(option)}</span>${answerAvatars(game,option,accounts)}</button>`).join("")}</div>`:`<div class="math-input-wrap"><input id="math-answer" autocomplete="off" inputmode="none" value="${answered?escapeHtml(chosen):""}" ${answered?"disabled":""} placeholder="Wpisz wynik"><div class="math-keyboard">${["√","²","³","xʸ","π","÷","×","/","(",")","⌫","C"].map(key=>`<button class="ghost" data-math-key="${key==="⌫"?"backspace":key==="C"?"clear":key}">${key}</button>`).join("")}</div><button class="primary" id="math-submit" ${answered?"disabled":""}>Odpowiedz</button></div>`}<div class="math-bottom"><strong data-math-countdown>${Math.max(0,Math.ceil((game.phaseEndsAt-Date.now())/1000))}s</strong><span>${Object.keys(game.answers||{}).length}/${game.playerCount} odpowiedzi</span></div></section></main>`;
  root.querySelectorAll("[data-math-answer]").forEach(button=>button.addEventListener("click",()=>actions.mathematicsAnswer(button.dataset.mathAnswer,expected)));if(game.answerMode==="input")renderInput(root,actions,game,q,answered,expected);renderMathematicsGame.countdown=setInterval(()=>{const node=root.querySelector("[data-math-countdown]");if(node)node.textContent=`${Math.max(0,Math.ceil((game.phaseEndsAt-Date.now())/1000))}s`;},250);renderMathematicsGame.timer=setTimeout(()=>actions.mathematicsTimeout(expected),Math.max(100,game.phaseEndsAt-Date.now()+50)); }
export function renderMathematicsLobbySettings(room,isHost){ const s=room.settings||mathematicsDefaults;return `<div class="mathematics-settings"><label>Liczba pytań <input data-math-setting="questionCount" type="number" min="3" max="20" value="${s.questionCount||10}" ${isHost?"":"disabled"}></label><label>Czas na pytanie <input data-math-setting="questionTime" type="number" min="10" max="180" value="${s.questionTime||45}" ${isHost?"":"disabled"}> s</label><label>Sposób odpowiadania <select data-math-setting="answerMode" ${isHost?"":"disabled"}><option value="abcd" ${s.answerMode!=="input"?"selected":""}>ABCD</option><option value="input" ${s.answerMode==="input"?"selected":""}>Wpisywanie odpowiedzi</option></select></label><fieldset><legend>Typy zadań</legend>${categories.map(category=>`<label class="math-category"><input type="checkbox" data-math-category="${category}" ${((s.categories||mathematicsDefaults.categories).includes(category))?"checked":""} ${isHost?"":"disabled"}>${labels[category]}</label>`).join("")}</fieldset></div>`; }
export function stopMathematicsTimer(){window.clearTimeout(renderMathematicsGame.timer);window.clearInterval(renderMathematicsGame.countdown);}
