import { otherQuestionCategories, otherQuestionPairs } from "../content/inne-pytanie/questionPairs.js?v=20260605-3";
import { $, boardPlayerStripHtml, escapeHtml, playerMiniHtml } from "./utils.js?v=20260605-5";import{Audio}from"./audio.js";import{Effects}from"./effects.js";
let timerId,lastCountdown;const now=()=>Date.now(),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const objectOrEmpty=value=>value&&typeof value==="object"&&!Array.isArray(value)?value:{};
const arrayOrEmpty=value=>Array.isArray(value)?value:[];
function normalizeOtherQuestionGame(g){g.answers=objectOrEmpty(g.answers);g.votes=objectOrEmpty(g.votes);g.scores=objectOrEmpty(g.scores);g.chat=arrayOrEmpty(g.chat);return g;}
export const otherQuestionDefaults={answerTime:20,discussionTime:60,voteTime:15,chatEnabled:true,category:"",categories:otherQuestionCategories.slice(0,3),rounds:5};
export const otherQuestionCategoryCounts=Object.fromEntries(otherQuestionCategories.map(category=>[category,otherQuestionPairs.filter(item=>item.category===category).length]));
const minOtherCategories=3;
const categoryUsage=settings=>settings?.categoryUsage&&typeof settings.categoryUsage==="object"&&!Array.isArray(settings.categoryUsage)?{...settings.categoryUsage}:{};
const bumpUsage=(usage,category)=>{if(category)usage[category]=Number(usage[category]||0)+1;return usage;};
function selectedOtherCategories(settings){let picked=Array.isArray(settings.categories)?settings.categories:(settings.category&&settings.category!=="Wszystkie"?[settings.category]:otherQuestionCategories.slice(0,3));picked=[...new Set(picked)].filter(category=>otherQuestionCategories.includes(category));otherQuestionCategories.forEach(category=>{if(picked.length<minOtherCategories&&!picked.includes(category))picked.push(category);});return picked;}
function pick(settings){const categories=selectedOtherCategories(settings);let p=otherQuestionPairs.filter(x=>categories.includes(x.category));return p[Math.floor(Math.random()*p.length)]||otherQuestionPairs[0];}
export function createOtherQuestionGame(players,settings){const pair=pick(settings),impostor=players[Math.floor(Math.random()*players.length)],usage=bumpUsage(categoryUsage(settings),pair.category);return{phase:"answering",pair,category:pair.category,categoryUsage:usage,impostor,answers:{},chat:[],votes:{},round:1,scores:Object.fromEntries(players.map(x=>[x,0])),phaseEndsAt:now()+settings.answerTime*1000};}
function startDiscussion(g,s){g.phase="discussion";g.phaseEndsAt=now()+s.discussionTime*1000;}function startVote(g,s){g.phase="voting";g.votes={};g.phaseEndsAt=now()+s.voteTime*1000;}
function finishVote(g){normalizeOtherQuestionGame(g);const c={};Object.values(g.votes).forEach(x=>c[x]=(c[x]||0)+1);const picked=Object.entries(c).sort((a,b)=>b[1]-a[1])[0]?.[0];const caught=picked===g.impostor;g.phase="results";g.result={picked,caught,counts:c};g.phaseEndsAt=null;}
export const OtherQuestionEngine={answer(g,uid,text,s){normalizeOtherQuestionGame(g);if(g.phase!=="answering"||uid in g.answers)return;if(!text.trim())return"Wpisz odpowiedź.";g.answers[uid]=text.trim();if(Object.keys(g.answers).length>=Object.keys(g.scores).length)startDiscussion(g,s);},chat(g,uid,text){normalizeOtherQuestionGame(g);if(text.trim())g.chat.push({uid,text:text.trim()});},vote(g,uid,target){normalizeOtherQuestionGame(g);if(g.phase!=="voting"||uid in g.votes)return;g.votes[uid]=target;if(Object.keys(g.votes).length>=Object.keys(g.scores).length)finishVote(g);},timeout(g,s){normalizeOtherQuestionGame(g);if(g.phase==="answering"){Object.keys(g.scores).forEach(uid=>g.answers[uid]??="brak odpowiedzi");startDiscussion(g,s);}else if(g.phase==="discussion")startVote(g,s);else if(g.phase==="voting")finishVote(g);},next(g,players,s){normalizeOtherQuestionGame(g);const score=g.result.caught?players.filter(x=>x!==g.impostor):[g.impostor];score.forEach(x=>g.scores[x]=(g.scores[x]||0)+1);if(g.round>=s.rounds){g.phase="final";return;}const n=createOtherQuestionGame(players,{...s,categoryUsage:objectOrEmpty(g.categoryUsage)});Object.assign(g,n,{round:g.round+1,scores:g.scores});}};
export function renderOtherQuestionLobbySettings(room,isHost){const s={...otherQuestionDefaults,...room.settings},selected=selectedOtherCategories(s),usage=room.game?.categoryUsage||room.settings?.categoryUsage||{},categoryBadge=category=>`<span class="category-count">${Number(usage[category]||0)}/${otherQuestionCategoryCounts[category]||0}</span>`;return`<div class="impostor-settings-grid"><label>Czas odpowiedzi <b>${s.answerTime}s</b><input data-other-setting="answerTime" type="range" min="10" max="30" value="${s.answerTime}" ${isHost?"":"disabled"}></label><label>Dyskusja <b>${s.discussionTime}s</b><input data-other-setting="discussionTime" type="range" min="30" max="120" step="10" value="${s.discussionTime}" ${isHost?"":"disabled"}></label><label>Głosowanie <b>${s.voteTime}s</b><input data-other-setting="voteTime" type="range" min="10" max="30" value="${s.voteTime}" ${isHost?"":"disabled"}></label><label>Liczba rund<select data-other-setting="rounds" ${isHost?"":"disabled"}>${[1,2,3,4,5,6,7,8,10].map(n=>`<option ${s.rounds===n?"selected":""}>${n}</option>`).join("")}</select></label><div class="most-category-box"><b>Kategorie</b><small>minimum ${minOtherCategories}, bez limitu</small><div class="multi-category-list">${otherQuestionCategories.map(category=>`<label class="check category-chip"><span><input data-other-category="${escapeHtml(category)}" type="checkbox" ${selected.includes(category)?"checked":""} ${!isHost||selected.length<=minOtherCategories&&selected.includes(category)?"disabled":""}> ${escapeHtml(category)}</span>${categoryBadge(category)}</label>`).join("")}</div></div><label class="check"><input data-other-setting="chatEnabled" type="checkbox" ${s.chatEnabled?"checked":""} ${isHost?"":"disabled"}> Czat</label></div>`;}
export function stopOtherQuestionTimer(){clearInterval(timerId);timerId=null;lastCountdown=null;}const timer=g=>`<div class="timer-box"><b id="other-timer">${Math.max(0,Math.ceil(((g.phaseEndsAt||now())-now())/1000))}s</b></div>`;
export function renderOtherQuestionGame(root,{room,accounts,currentUser},actions){stopOtherQuestionTimer();const g=room.game,s={...otherQuestionDefaults,...room.settings};g.answers ||= {};g.votes ||= {};g.chat ||= [];g.scores ||= Object.fromEntries(room.players.map(uid=>[uid,0]));const question=currentUser===g.impostor?g.pair.impostor:g.pair.main;if(g.phase==="results")Effects.play(g.result.caught?"citizensWin":"impostorWin",`${room.roomId}:other:${g.round}:${g.result.picked}`);let body;
if(g.phase==="answering")body=`<section class="panel center"><p class="eyebrow">PRYWATNE PYTANIE · RUNDA ${g.round}/${s.rounds}</p><h1>${escapeHtml(question)}</h1>${timer(g)}${currentUser in g.answers?`<div class="waiting-state"><span class="waiting-pulse">✓</span><h3>Odpowiedź zapisana</h3><p>Czekamy jeszcze na ${room.players.length-Object.keys(g.answers).length} graczy. Dyskusja rozpocznie się automatycznie.</p></div>`:'<form id="other-answer-form" class="answer-form"><input id="other-answer" placeholder="twoja odpowiedź"><button class="primary">Wyślij</button></form>'}<p>${Object.keys(g.answers).length}/${room.players.length} odpowiedzi</p></section>`;
else if(g.phase==="discussion")body=`<section class="panel"><div class="game-top"><div><p class="eyebrow">DYSKUSJA</p><h1>${escapeHtml(g.pair.main)}</h1></div>${timer(g)}</div><div class="answer-board">${room.players.map(uid=>`<article>${playerMiniHtml(accounts[uid])}<span>${escapeHtml(g.answers[uid])}</span></article>`).join("")}</div></section>`;
else if(g.phase==="voting")body=`<section class="panel center"><h1>Kto dostał inne pytanie?</h1>${timer(g)}${currentUser in g.votes?'<div class="waiting-state"><span class="waiting-pulse">✓</span><h3>Głos zapisany</h3><p>Czekamy na głosy pozostałych graczy.</p></div>':`<div class="vote-grid">${room.players.map(uid=>`<button data-other-vote="${uid}">${playerMiniHtml(accounts[uid])}</button>`).join("")}</div>`}</section>`;
else if(g.phase==="results")body=`<section class="panel center"><h1>${g.result.caught?"Impostor wykryty!":"Impostor się ukrył!"}</h1><p>Inne pytanie dostał:</p><div class="result-focus-player">${playerMiniHtml(accounts[g.impostor])}</div><div class="question-reveal"><p>${escapeHtml(g.pair.main)}</p><p>${escapeHtml(g.pair.impostor)}</p></div><p class="money-pop">Zwycięzcy rundy dostają +100$</p><button class="primary" id="other-next">Następna runda</button></section>`;
else body=`<section class="panel center"><h1>Koniec gry</h1><div class="final-ranking">${Object.entries(g.scores).sort((a,b)=>b[1]-a[1]).map(([uid,n],index)=>`<article><b>#${index+1}</b>${playerMiniHtml(accounts[uid])}<strong>${n} pkt</strong></article>`).join("")}</div><button class="primary" id="other-lobby">Wróć do lobby</button></section>`;
root.innerHTML=`<main class="page other-page question-board board-shell enter">${boardPlayerStripHtml(room.players,accounts,{scores:g.scores})}<section class="question-table">${body}</section>${s.chatEnabled&&["discussion","voting"].includes(g.phase)?`<section class="panel"><h3>Czat</h3><div class="chat-messages">${g.chat.map(m=>`<p><b>${escapeHtml(accounts[m.uid]?.nick)}:</b> ${escapeHtml(m.text)}</p>`).join("")}</div><form id="other-chat" class="answer-form"><input id="other-chat-input" placeholder="wiadomość"><button>Wyślij</button></form></section>`:""}<button class="ghost" id="leave-room">Wyjdź</button></main>`;
$("#leave-room").addEventListener("click",actions.leaveRoom);$("#other-answer-form")?.addEventListener("submit",e=>{e.preventDefault();actions.otherAnswer($("#other-answer").value);});root.querySelectorAll("[data-other-vote]").forEach(b=>b.addEventListener("click",()=>actions.otherVote(b.dataset.otherVote)));$("#other-chat")?.addEventListener("submit",async e=>{e.preventDefault();const input=$("#other-chat-input"),text=input.value;if(await actions.otherChat(text)!==false)input.value="";});$("#other-next")?.addEventListener("click",actions.otherNext);$("#other-lobby")?.addEventListener("click",actions.returnToRoom);if(!["results","final"].includes(g.phase))startTimer(actions);}
function startTimer(actions){timerId=setInterval(()=>{const e=$("#other-timer");if(!e)return;const n=Math.max(0,Number(e.textContent.replace("s",""))-1);e.textContent=`${n}s`;if(n>0&&n<=3&&lastCountdown!==n){lastCountdown=n;Audio.play("countdown");}if(!n){stopOtherQuestionTimer();actions.otherTimeout();}},1000);}
