import { escapeHtml } from "./utils.js?v=20260613-2";
import { impostorWords } from "../content/impostor/words.js";

export const wordChainDefaults={answerTime:20,allowRepeats:false,repeatGap:3,acceptEnglish:false,hearts:3};
const polish=`arbuz autobus aparat ananas akwarium akwaleria balon banan biblioteka balkon boisko borsuk brama bransoletka broda budynek burza cebula cyrk cytryna czapka czarnoziem czekolada dach deszcz delfin dom droga dzwon ekran ekierka ekologia farba foka fotel fotografia gabinet galaretka garnek gazeta gitara góra gruszka herbata hotel hulajnoga igloo indyk jabłko jagoda jajko jeleń jezioro zegar kamera kanapka kapelusz karuzela kasztan kajak kebab kiwi koc kot kotlet kredka krokodyl krzesło książka kubek kuchnia labirynt lampa las lawenda legenda lekarz lew lodówka lokomotywa lotnisko łabędź łyżka mapa marchew maska mewa mięta mleko motyl muzeum mysz narciarz nos notes ocean ogórek okulary obraz obiad odkurzacz ogień ogórek oko orkiestra owca ołówek palec papuga parasol park pasja pizza plaża plecak pociąg pomidor pomarańcza portret pralka prezenter komputer radio rakieta rower ryba rzeka robot rogalek roślina ropucha samolot ser serce słoń słońce sofa sokół sprężyna stadion statek stół samochód szafa szczupak szpital szpinak telefon telewizor termos tęcza torba tramwaj trawa truskawka tulipan ulica ubranie ukulele uczelnia walizka warzywo wazon wiatr wiśnia wiewiórka winogrono woda wózek wróbel wyspa zamek zeszyt zebra zima zupa żaba żaglówka żarówka żółw`.split(/\s+/);
const english=`apple airplane airport animal ant apartment avocado backpack balloon banana beach bicycle bird biscuit blanket book bottle bridge browser building burger bus butterfly camera candle castle cat chair cheese cherry chocolate city cloud coffee computer cookie crocodile diamond dog dolphin door dragon dress eagle elephant engine evening family farm feather film flower forest fork frog galaxy garden ghost guitar hamburger hat house island jacket jungle key kitchen kite lake lamp lemon library lion luggage machine mango market meadow mirror monkey moon mountain museum music notebook ocean orange panda paper park pencil pepper piano pizza planet pocket potato rabbit rainbow river robot rocket sandwich school shark sheep shirt shoe snow spider squirrel stadium star strawberry summer sunset table tiger tomato train tree turtle umbrella village violin volcano wallet watermelon window winter wizard wolf zebra`.split(/\s+/);
const extraPolish=impostorWords.flatMap(item=>[item.main,item.impostor]).filter(Boolean);
const polishWords=[...new Set([...polish,...extraPolish])];
const normalize=value=>String(value||"").toLocaleLowerCase("pl-PL").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ł/g,"l").replace(/[^a-z]/g,"");
const polishSet=new Set(polishWords.map(normalize)),englishSet=new Set([...polishWords,...english].map(normalize));
const displayWords=new Map([...polishWords,...english].map(word=>[normalize(word),word]));
const allowedWords=englishMode=>[...new Set(englishMode?[...polishWords,...english]:polishWords)].map(normalize).filter(Boolean);
const wordShape=englishMode=>value=>{const raw=String(value||"").trim();if(raw.length<2||raw.length>32)return false;const pattern=englishMode?/^[a-ząćęłńóśźż]+$/iu:/^[a-ząćęłńóśźż]+$/iu;return pattern.test(raw)&&/[aeiouyąęó]/iu.test(raw);};
const phaseEnd=seconds=>Date.now()+Math.max(5,Number(seconds)||20)*1000;

export function createWordChainGame(players,settings={}){const englishMode=Boolean(settings.acceptEnglish),pool=allowedWords(englishMode),first=pool[Math.floor(Math.random()*pool.length)],hearts=Math.max(1,Math.min(5,Number(settings.hearts)||3));return {mode:"word-chain",phase:"answer",players,turnIndex:0,currentUid:players[0],chain:[displayWords.get(first)||first],used:[first],answerTime:Number(settings.answerTime)||20,allowRepeats:Boolean(settings.allowRepeats),repeatGap:Math.max(2,Math.min(5,Number(settings.repeatGap)||3)),acceptEnglish:englishMode,hearts:Object.fromEntries(players.map(uid=>[uid,hearts])),eliminated:[],missedPlayers:[],wrong:false,wordChanged:false,phaseEndsAt:phaseEnd(settings.answerTime)};}
function activePlayers(game){return (game.players||[]).filter(uid=>!(game.eliminated||[]).includes(uid));}
function nextPlayer(game){const active=activePlayers(game);if(active.length<=1){game.phase="result";game.finished=true;game.winner=active[0]||"";return;}let index=Number(game.turnIndex)||0;for(let step=0;step<game.players.length;step+=1){index=(index+1)%game.players.length;if(active.includes(game.players[index])){game.turnIndex=index;game.currentUid=game.players[index];return;}}game.phase="result";game.finished=true;game.winner=active[0]||"";}
function loseHeart(game,uid){game.hearts=game.hearts&&typeof game.hearts==="object"&&!Array.isArray(game.hearts)?game.hearts:{};game.eliminated=Array.isArray(game.eliminated)?game.eliminated:[];game.hearts[uid]=Math.max(0,Number(game.hearts[uid]??3)-1);if(game.hearts[uid]===0&&!game.eliminated.includes(uid))game.eliminated.push(uid);}
function replacementWord(game){const pool=allowedWords(Boolean(game.acceptEnglish)),last=normalize(game.chain?.at(-1)||""),fresh=pool.filter(word=>word!==last&&!game.used?.includes(word));const source=fresh.length?fresh:pool.filter(word=>word!==last);const word=source[Math.floor(Math.random()*source.length)]||pool[0]||last;return {normalized:word,display:displayWords.get(word)||word};}
function changeWord(game){const next=replacementWord(game);game.chain=[next.display];if(!game.used.includes(next.normalized))game.used.push(next.normalized);game.missedPlayers=[];game.wordChanged=true;}
export const WordChainEngine={answer(game,uid,value){if(game.phase!=="answer"||uid!==game.currentUid)return "To nie jest Twoja kolej.";const raw=String(value||"").trim(),word=normalize(raw),last=normalize(game.chain.at(-1)||"");if(!word)return "Wpisz słowo.";if(!wordShape(Boolean(game.acceptEnglish))(raw))return "Wpisz jedno słowo złożone z liter (2–32 znaki).";if(word[0]!==last.at(-1))return `Słowo musi zaczynać się na: ${last.at(-1).toUpperCase()}.`;const previous=game.used.lastIndexOf(word);if(previous>=0&&(!game.allowRepeats||game.used.length-previous-1<game.repeatGap))return `To słowo można powtórzyć dopiero po ${game.repeatGap} innych słowach.`;game.chain.push(displayWords.get(word)||raw);game.used.push(word);game.missedPlayers=[];game.wrong=false;game.wordChanged=false;nextPlayer(game);if(game.phase==="answer")game.phaseEndsAt=phaseEnd(game.answerTime);},timeout(game){if(game.phase!=="answer")return;const current=game.currentUid,activeBefore=activePlayers(game);game.missedPlayers=Array.isArray(game.missedPlayers)?game.missedPlayers:[];if(!game.missedPlayers.includes(current))game.missedPlayers.push(current);loseHeart(game,current);game.wrong=true;nextPlayer(game);if(game.phase!=="answer")return;if(activeBefore.length&&activeBefore.every(uid=>game.missedPlayers.includes(uid)))changeWord(game);game.phaseEndsAt=phaseEnd(game.answerTime);}};
export function renderWordChainGame(root,{room,accounts,currentUser},actions){const game=room.game,expected={phase:game.phase,phaseEndsAt:game.phaseEndsAt},maxHearts=Math.max(1,Math.min(5,Number(room.settings?.hearts)||3)),hearts=uid=>{const left=Math.max(0,Math.min(maxHearts,Number(game.hearts?.[uid]??maxHearts)));return `<span class="word-chain-hearts" aria-label="${left}/${maxHearts} serc">${Array.from({length:maxHearts},(_,index)=>`<i class="${index<left?"live":"lost"}">♥</i>`).join("")}</span>`;},last=String(game.chain?.at(-1)||"");root.innerHTML=`<main class="page word-chain-page enter"><section class="panel word-chain-panel"><p class="eyebrow">ŁAŃCUCH SŁÓW · ${game.acceptEnglish?"PL + EN":"JĘZYK POLSKI"}</p><h1>Ostatnia litera, następne słowo</h1><div class="word-chain-last"><small>Ostatnie słowo</small><strong>${escapeHtml(last)}</strong><span>Następne słowo zaczyna się na <b>${escapeHtml(last.at(-1)?.toUpperCase()||"?")}</b></span></div><div class="word-chain-list">${(game.chain||[]).slice(-12).map((word,index)=>`<span class="word-chain-chip">${escapeHtml(word)}${index===(game.chain||[]).slice(-12).length-1?" ← teraz":""}</span>`).join("")}</div><div class="word-chain-roster">${(game.players||[]).map(uid=>`<span class="${game.eliminated?.includes(uid)?"eliminated":""}">${escapeHtml(accounts[uid]?.nick||"Gracz")} ${hearts(uid)}</span>`).join("")}</div><p class="word-chain-turn">${game.phase==="result"?(game.winner?`${escapeHtml(accounts[game.winner]?.nick||"Gracz")} wygrywa!`:"Koniec gry"):(game.currentUid===currentUser?"Twoja kolej":"Kolej: "+escapeHtml(accounts[game.currentUid]?.nick||"Gracz"))}</p>${game.wordChanged?'<div class="word-chain-miss">Nikt nie odpowiedział — wylosowano nowe słowo.</div>':game.wrong?'<div class="word-chain-miss">Czas minął — kolejka przeszła dalej.</div>':""}${game.phase==="answer"?`<form id="word-chain-form" class="word-chain-form"><input id="word-chain-input" autocomplete="off" placeholder="Wpisz słowo" ${game.currentUid===currentUser?"":"disabled"}><button class="primary" ${game.currentUid===currentUser?"":"disabled"}>Odpowiedz</button></form><div class="word-chain-bottom"><strong data-word-chain-timer>${Math.max(0,Math.ceil((game.phaseEndsAt-Date.now())/1000))}s</strong><span>${game.allowRepeats?`Powtórki po ${game.repeatGap} słowach` : "Bez powtórek"}</span></div>`:""}</section></main>`;root.querySelector("#word-chain-form")?.addEventListener("submit",event=>{event.preventDefault();actions.wordChainAnswer(root.querySelector("#word-chain-input").value,expected);});if(game.phase!=="answer")return;renderWordChainGame.countdown=setInterval(()=>{const node=root.querySelector("[data-word-chain-timer]");if(node)node.textContent=`${Math.max(0,Math.ceil((game.phaseEndsAt-Date.now())/1000))}s`;},250);renderWordChainGame.timer=setTimeout(()=>actions.wordChainTimeout(expected),Math.max(100,game.phaseEndsAt-Date.now()+50));}
export function stopWordChainTimer(){clearTimeout(renderWordChainGame.timer);clearInterval(renderWordChainGame.countdown);}

export function wordChainBotWord(game){const last=normalize(String(game?.chain?.at(-1)||""));const required=last.at(-1);const pool=[...new Set([...(game?.acceptEnglish?[...polishWords,...english]:polishWords)].map(normalize))].filter(word=>word[0]===required&&!game.used?.includes(word));return pool[Math.floor(Math.random()*pool.length)]||pool[0]||"";}

export function renderWordChainLobbySettings(room,isHost){const s={...wordChainDefaults,...(room.settings||{})};return `<div class="word-chain-settings"><label class="setting-row"><span>Czas odpowiedzi</span><span class="setting-control"><input data-word-chain-setting="answerTime" type="number" min="5" max="180" value="${s.answerTime||20}" ${isHost?"":"disabled"}><small>s</small></span></label><label class="setting-row"><span>Liczba serc na gracza</span><select data-word-chain-setting="hearts" ${isHost?"":"disabled"}>${[1,2,3,4,5].map(value=>`<option value="${value}" ${Number(s.hearts||3)===value?"selected":""}>${value}</option>`).join("")}</select></label><label class="setting-row check"><span>Możliwość powtarzania słów</span><input type="checkbox" data-word-chain-setting="allowRepeats" ${s.allowRepeats?"checked":""} ${isHost?"":"disabled"}></label><label class="setting-row"><span>Odstęp powtórki</span><select data-word-chain-setting="repeatGap" ${!isHost||!s.allowRepeats?"disabled":""}>${[2,3,4,5].map(value=>`<option value="${value}" ${Number(s.repeatGap||3)===value?"selected":""}>${value} innych słów</option>`).join("")}</select></label><label class="setting-row check"><span>Akceptuj angielskie słowa</span><input type="checkbox" data-word-chain-setting="acceptEnglish" ${s.acceptEnglish?"checked":""} ${isHost?"":"disabled"}></label><p class="tiny">Za brak odpowiedzi gracz traci serce. Jeśli nikt nie odpowie w pełnym obiegu, losowane jest nowe słowo.</p></div>`;}
