import { escapeHtml } from "./utils.js?v=20260613-2";

export const wordChainDefaults={answerTime:20,allowRepeats:false,repeatGap:3,acceptEnglish:false};
const polish=`arbuz autobus aparat ananas akwarium akwaleria balon banan biblioteka balkon boisko borsuk brama bransoletka broda budynek burza cebula cyrk cytryna czapka czarnoziem czekolada dach deszcz delfin dom droga dzwon ekran ekierka ekologia farba foka fotel fotografia gabinet galaretka garnek gazeta gitara góra gruszka herbata hotel hulajnoga igloo indyk jabłko jagoda jajko jeleń jezioro zegar kamera kanapka kapelusz karuzela kasztan kajak kebab kiwi koc kot kotlet kredka krokodyl krzesło książka kubek kuchnia labirynt lampa las lawenda legenda lekarz lew lodówka lokomotywa lotnisko łabędź łyżka mapa marchew maska mewa mięta mleko motyl muzeum mysz narciarz nos notes ocean ogórek okulary obraz obiad odkurzacz ogień ogórek oko orkiestra owca ołówek palec papuga parasol park pasja pizza plaża plecak pociąg pomidor pomarańcza portret pralka prezenter komputer radio rakieta rower ryba rzeka robot rogalek roślina ropucha samolot ser serce słoń słońce sofa sokół sprężyna stadion statek stół samochód szafa szczupak szpital szpinak telefon telewizor termos tęcza torba tramwaj trawa truskawka tulipan ulica ubranie ukulele uczelnia walizka warzywo wazon wiatr wiśnia wiewiórka winogrono woda wózek wróbel wyspa zamek zeszyt zebra zima zupa żaba żaglówka żarówka żółw`.split(/\s+/);
const english=`apple airplane airport animal ant apartment avocado backpack balloon banana beach bicycle bird biscuit blanket book bottle bridge browser building burger bus butterfly camera candle castle cat chair cheese cherry chocolate city cloud coffee computer cookie crocodile diamond dog dolphin door dragon dress eagle elephant engine evening family farm feather film flower forest fork frog galaxy garden ghost guitar hamburger hat house island jacket jungle key kitchen kite lake lamp lemon library lion luggage machine mango market meadow mirror monkey moon mountain museum music notebook ocean orange panda paper park pencil pepper piano pizza planet pocket potato rabbit rainbow river robot rocket sandwich school shark sheep shirt shoe snow spider squirrel stadium star strawberry summer sunset table tiger tomato train tree turtle umbrella village violin volcano wallet watermelon window winter wizard wolf zebra`.split(/\s+/);
const normalize=value=>String(value||"").toLocaleLowerCase("pl-PL").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z]/g,"");
const polishSet=new Set(polish.map(normalize)),englishSet=new Set([...polish,...english].map(normalize));
const displayWords=new Map([...polish,...english].map(word=>[normalize(word),word]));
const allowedWords=englishMode=>[...new Set(englishMode?[...polish,...english]:polish)].map(normalize).filter(Boolean);
const phaseEnd=seconds=>Date.now()+Math.max(5,Number(seconds)||20)*1000;

export function createWordChainGame(players,settings={}){const englishMode=Boolean(settings.acceptEnglish),pool=allowedWords(englishMode);const first=pool[Math.floor(Math.random()*pool.length)];return {mode:"word-chain",phase:"answer",players,turnIndex:0,currentUid:players[0],chain:[first],used:[first],answerTime:Number(settings.answerTime)||20,allowRepeats:Boolean(settings.allowRepeats),repeatGap:Math.max(2,Math.min(5,Number(settings.repeatGap)||3)),acceptEnglish:englishMode,wrong:false,phaseEndsAt:phaseEnd(settings.answerTime)};}
function nextPlayer(game){game.turnIndex=(game.turnIndex+1)%game.players.length;game.currentUid=game.players[game.turnIndex];}
export const WordChainEngine={answer(game,uid,value){if(game.phase!=="answer"||uid!==game.currentUid)return "To nie jest Twoja kolej.";const word=normalize(value),last=game.chain.at(-1)||"";if(!word)return "Wpisz słowo.";const pool=game.acceptEnglish?englishSet:polishSet;if(!pool.has(word))return "Tego słowa nie ma w słowniku.";if(word[0]!==last.at(-1))return `Słowo musi zaczynać się na: ${last.at(-1).toUpperCase()}.`;const previous=game.used.lastIndexOf(word);if(previous>=0&&(!game.allowRepeats||game.used.length-previous-1<game.repeatGap))return `To słowo można powtórzyć dopiero po ${game.repeatGap} innych słowach.`;game.chain.push(displayWords.get(word)||word);game.used.push(word);game.wrong=false;nextPlayer(game);game.phaseEndsAt=phaseEnd(game.answerTime);},timeout(game){if(game.phase!=="answer")return;game.wrong=true;nextPlayer(game);game.phaseEndsAt=phaseEnd(game.answerTime);}};
export function renderWordChainGame(root,{room,accounts,currentUser},actions){const game=room.game,expected={phase:game.phase,phaseEndsAt:game.phaseEndsAt};root.innerHTML=`<main class="page word-chain-page enter"><section class="panel word-chain-panel"><p class="eyebrow">ŁAŃCUCH SŁÓW · ${game.acceptEnglish?"PL + EN":"JĘZYK POLSKI"}</p><h1>Ostatnia litera, następne słowo</h1><div class="word-chain-last"><small>Ostatnie słowo</small><strong>${escapeHtml(game.chain.at(-1))}</strong><span>Następne słowo zaczyna się na <b>${escapeHtml(game.chain.at(-1).at(-1).toUpperCase())}</b></span></div><div class="word-chain-list">${game.chain.slice(-12).map((word,index)=>`<span class="word-chain-chip">${escapeHtml(word)}${index===game.chain.slice(-12).length-1?" ← teraz":""}</span>`).join("")}</div><p class="word-chain-turn">${game.currentUid===currentUser?"Twoja kolej":"Kolej: "+escapeHtml(accounts[game.currentUid]?.nick||"Gracz")}</p>${game.wrong?'<div class="word-chain-miss">Czas minął — kolejka przeszła dalej.</div>':""}<form id="word-chain-form" class="word-chain-form"><input id="word-chain-input" autocomplete="off" placeholder="Wpisz słowo" ${game.currentUid===currentUser?"":"disabled"}><button class="primary" ${game.currentUid===currentUser?"":"disabled"}>Odpowiedz</button></form><div class="word-chain-bottom"><strong data-word-chain-timer>${Math.max(0,Math.ceil((game.phaseEndsAt-Date.now())/1000))}s</strong><span>${game.allowRepeats?`Powtórki po ${game.repeatGap} słowach` : "Bez powtórek"}</span></div></section></main>`;root.querySelector("#word-chain-form")?.addEventListener("submit",event=>{event.preventDefault();actions.wordChainAnswer(root.querySelector("#word-chain-input").value,expected);});renderWordChainGame.countdown=setInterval(()=>{const node=root.querySelector("[data-word-chain-timer]");if(node)node.textContent=`${Math.max(0,Math.ceil((game.phaseEndsAt-Date.now())/1000))}s`;},250);renderWordChainGame.timer=setTimeout(()=>actions.wordChainTimeout(expected),Math.max(100,game.phaseEndsAt-Date.now()+50));}
export function stopWordChainTimer(){clearTimeout(renderWordChainGame.timer);clearInterval(renderWordChainGame.countdown);}

export function renderWordChainLobbySettings(room,isHost){const s=room.settings||wordChainDefaults;return `<div class="word-chain-settings"><label class="setting-row"><span>Czas odpowiedzi</span><span class="setting-control"><input data-word-chain-setting="answerTime" type="number" min="5" max="180" value="${s.answerTime||20}" ${isHost?"":"disabled"}><small>s</small></span></label><label class="setting-row check"><span>Możliwość powtarzania słów</span><input type="checkbox" data-word-chain-setting="allowRepeats" ${s.allowRepeats?"checked":""} ${isHost?"":"disabled"}></label><label class="setting-row"><span>Odstęp powtórki</span><select data-word-chain-setting="repeatGap" ${!isHost||!s.allowRepeats?"disabled":""}>${[2,3,4,5].map(value=>`<option value="${value}" ${Number(s.repeatGap||3)===value?"selected":""}>${value} innych słów</option>`).join("")}</select></label><label class="setting-row check"><span>Akceptuj angielskie słowa</span><input type="checkbox" data-word-chain-setting="acceptEnglish" ${s.acceptEnglish?"checked":""} ${isHost?"":"disabled"}></label><p class="tiny">Słowa są sprawdzane względem dużego słownika. Polskie znaki nie zmieniają wymaganej ostatniej litery.</p></div>`;}
