// Dodaj nową parę jako: { category:"Kategoria", main:"hasło obywateli", impostor:"podobne hasło" }.
export const impostorWords = [
  { category:"Jedzenie", main:"pizza", impostor:"zapiekanka" },
  { category:"Jedzenie", main:"burger", impostor:"kebab" },
  { category:"Jedzenie", main:"rosół", impostor:"pomidorowa" },
  { category:"Jedzenie", main:"pierogi", impostor:"naleśniki" },
  { category:"Jedzenie", main:"sushi", impostor:"ramen" },
  { category:"Jedzenie", main:"frytki", impostor:"chipsy" },
  { category:"Jedzenie", main:"lody", impostor:"sorbet" },
  { category:"Jedzenie", main:"czekolada", impostor:"baton" },
  { category:"Warzywa", main:"ziemniak", impostor:"marchewka" },
  { category:"Warzywa", main:"pomidor", impostor:"papryka" },
  { category:"Warzywa", main:"ogórek", impostor:"cukinia" },
  { category:"Warzywa", main:"cebula", impostor:"czosnek" },
  { category:"Warzywa", main:"brokuł", impostor:"kalafior" },
  { category:"Warzywa", main:"sałata", impostor:"szpinak" },
  { category:"Warzywa", main:"dynia", impostor:"kabaczek" },
  { category:"Warzywa", main:"burak", impostor:"rzodkiewka" },
  { category:"Owoce", main:"jabłko", impostor:"gruszka" },
  { category:"Owoce", main:"malina", impostor:"truskawka" },
  { category:"Owoce", main:"cytryna", impostor:"limonka" },
  { category:"Owoce", main:"arbuz", impostor:"melon" },
  { category:"Owoce", main:"brzoskwinia", impostor:"nektarynka" },
  { category:"Owoce", main:"mandarynka", impostor:"pomarańcza" },
  { category:"Owoce", main:"jagoda", impostor:"borówka" },
  { category:"Owoce", main:"mango", impostor:"papaja" },
  { category:"Zwierzęta", main:"pies", impostor:"wilk" },
  { category:"Zwierzęta", main:"kot", impostor:"tygrys" },
  { category:"Zwierzęta", main:"lew", impostor:"gepard" },
  { category:"Zwierzęta", main:"krowa", impostor:"koza" },
  { category:"Zwierzęta", main:"rekin", impostor:"delfin" },
  { category:"Zwierzęta", main:"orzeł", impostor:"sokół" },
  { category:"Zwierzęta", main:"żaba", impostor:"ropucha" },
  { category:"Zwierzęta", main:"krokodyl", impostor:"aligator" },
  { category:"Szkoła", main:"zeszyt", impostor:"podręcznik" },
  { category:"Szkoła", main:"długopis", impostor:"ołówek" },
  { category:"Szkoła", main:"matematyka", impostor:"fizyka" },
  { category:"Szkoła", main:"historia", impostor:"geografia" },
  { category:"Szkoła", main:"tablica", impostor:"projektor" },
  { category:"Szkoła", main:"plecak", impostor:"piórnik" },
  { category:"Szkoła", main:"kartkówka", impostor:"sprawdzian" },
  { category:"Szkoła", main:"nauczyciel", impostor:"dyrektor" },
  { category:"Technologia", main:"telefon", impostor:"tablet" },
  { category:"Technologia", main:"laptop", impostor:"komputer" },
  { category:"Technologia", main:"klawiatura", impostor:"mysz" },
  { category:"Technologia", main:"monitor", impostor:"telewizor" },
  { category:"Technologia", main:"słuchawki", impostor:"głośnik" },
  { category:"Technologia", main:"wifi", impostor:"bluetooth" },
  { category:"Technologia", main:"procesor", impostor:"karta graficzna" },
  { category:"Technologia", main:"ładowarka", impostor:"powerbank" },
  { category:"Gry", main:"minecraft", impostor:"terraria" },
  { category:"Gry", main:"fortnite", impostor:"apex legends" },
  { category:"Gry", main:"valorant", impostor:"counter strike" },
  { category:"Gry", main:"fifa", impostor:"rocket league" },
  { category:"Gry", main:"roblox", impostor:"minecraft" },
  { category:"Gry", main:"the sims", impostor:"stardew valley" },
  { category:"Gry", main:"brawl stars", impostor:"clash royale" },
  { category:"Filmy i seriale", main:"harry potter", impostor:"władca pierścieni" },
  { category:"Filmy i seriale", main:"shrek", impostor:"madagaskar" },
  { category:"Filmy i seriale", main:"star wars", impostor:"star trek" },
  { category:"Filmy i seriale", main:"stranger things", impostor:"wednesday" },
  { category:"Filmy i seriale", main:"breaking bad", impostor:"narcos" },
  { category:"Filmy i seriale", main:"marvel", impostor:"dc" },
  { category:"Filmy i seriale", main:"kraina lodu", impostor:"vaiana" },
  { category:"Filmy i seriale", main:"barbie", impostor:"oppenheimer" },
  { category:"Muzyka", main:"gitara", impostor:"ukulele" },
  { category:"Muzyka", main:"fortepian", impostor:"keyboard" },
  { category:"Muzyka", main:"spotify", impostor:"youtube music" },
  { category:"Muzyka", main:"koncert", impostor:"festiwal" },
  { category:"Muzyka", main:"rap", impostor:"trap" },
  { category:"Muzyka", main:"perkusja", impostor:"tamburyn" },
  { category:"Muzyka", main:"mikrofon", impostor:"głośnik" },
  { category:"Muzyka", main:"piosenka", impostor:"album" },
  { category:"Sport", main:"piłka nożna", impostor:"futsal" },
  { category:"Sport", main:"koszykówka", impostor:"siatkówka" },
  { category:"Sport", main:"tenis", impostor:"badminton" },
  { category:"Sport", main:"narty", impostor:"snowboard" },
  { category:"Sport", main:"basen", impostor:"aquapark" },
  { category:"Sport", main:"rower", impostor:"hulajnoga" },
  { category:"Sport", main:"boks", impostor:"mma" },
  { category:"Sport", main:"maraton", impostor:"sprint" },
  { category:"Miasta", main:"warszawa", impostor:"kraków" },
  { category:"Miasta", main:"gdańsk", impostor:"sopot" },
  { category:"Miasta", main:"wrocław", impostor:"poznań" },
  { category:"Miasta", main:"paryż", impostor:"londyn" },
  { category:"Miasta", main:"rzym", impostor:"wenecja" },
  { category:"Miasta", main:"nowy jork", impostor:"los angeles" },
  { category:"Miasta", main:"tokio", impostor:"seul" },
  { category:"Miasta", main:"barcelona", impostor:"madryt" },
  { category:"Kraje", main:"polska", impostor:"czechy" },
  { category:"Kraje", main:"niemcy", impostor:"austria" },
  { category:"Kraje", main:"włochy", impostor:"hiszpania" },
  { category:"Kraje", main:"norwegia", impostor:"szwecja" },
  { category:"Kraje", main:"usa", impostor:"kanada" },
  { category:"Kraje", main:"japonia", impostor:"korea południowa" },
  { category:"Kraje", main:"brazylia", impostor:"argentyna" },
  { category:"Kraje", main:"egipt", impostor:"maroko" },
  { category:"Rzeczy codzienne", main:"kubek", impostor:"szklanka" },
  { category:"Rzeczy codzienne", main:"widelec", impostor:"łyżka" },
  { category:"Rzeczy codzienne", main:"kanapa", impostor:"fotel" },
  { category:"Rzeczy codzienne", main:"łóżko", impostor:"materac" },
  { category:"Rzeczy codzienne", main:"parasol", impostor:"kurtka" },
  { category:"Rzeczy codzienne", main:"lodówka", impostor:"zamrażarka" },
  { category:"Rzeczy codzienne", main:"szampon", impostor:"mydło" },
  { category:"Rzeczy codzienne", main:"klucz", impostor:"kłódka" },
  { category:"Internet i memy", main:"youtube", impostor:"tiktok" },
  { category:"Internet i memy", main:"discord", impostor:"messenger" },
  { category:"Internet i memy", main:"instagram", impostor:"snapchat" },
  { category:"Internet i memy", main:"reddit", impostor:"wykop" },
  { category:"Internet i memy", main:"rickroll", impostor:"harlem shake" },
  { category:"Internet i memy", main:"sigma", impostor:"gigachad" },
  { category:"Internet i memy", main:"streamer", impostor:"youtuber" },
  { category:"Internet i memy", main:"meme", impostor:"gif" },
  { category:"Minecraft", main:"creeper", impostor:"zombie" },
  { category:"Minecraft", main:"enderman", impostor:"warden" },
  { category:"Minecraft", main:"diament", impostor:"szmaragd" },
  { category:"Minecraft", main:"kilof", impostor:"siekiera" },
  { category:"Minecraft", main:"nether", impostor:"end" },
  { category:"Minecraft", main:"wioska", impostor:"twierdza" },
  { category:"Minecraft", main:"obsydian", impostor:"bedrock" },
  { category:"Minecraft", main:"redstone", impostor:"lapis" },
  { category:"Roblox", main:"Brookhaven", impostor:"Adopt Me" },
  { category:"Roblox", main:"Doors", impostor:"Piggy" },
  { category:"Roblox", main:"Blox Fruits", impostor:"BedWars" },
  { category:"Roblox", main:"obby", impostor:"Tower of Hell" },
  { category:"Gry", main:"Minecraft", impostor:"Terraria" },
  { category:"Gry", main:"Fortnite", impostor:"Apex Legends" },
  { category:"Gry", main:"Valorant", impostor:"Counter-Strike" },
  { category:"Gry", main:"The Sims", impostor:"Stardew Valley" },
  { category:"Twórcy internetowi", main:"MrBeast", impostor:"PewDiePie" },
  { category:"Twórcy internetowi", main:"Dream", impostor:"Technoblade" },
  { category:"Twórcy internetowi", main:"Friz", impostor:"Rezi" },
  { category:"Twórcy internetowi", main:"Blowek", impostor:"Mandzio" },
  { category:"Twórcy internetowi", main:"IShowSpeed", impostor:"Kai Cenat" },
  { category:"Muzyka", main:"Spotify", impostor:"YouTube Music" },
  { category:"Muzyka", main:"koncert", impostor:"festiwal" },
  { category:"Sport", main:"Real Madryt", impostor:"Barcelona" },
  { category:"Sport", main:"Messi", impostor:"Ronaldo" },
];

impostorWords.push(
  { category:"Jedzenie", main:"pizza", impostor:"zapiekanka" },
  { category:"Jedzenie", main:"kebab", impostor:"burrito" },
  { category:"Jedzenie", main:"naleśniki", impostor:"gofry" },
  { category:"Jedzenie", main:"chipsy", impostor:"popcorn" },
  { category:"Jedzenie", main:"rosół", impostor:"pomidorowa" },
  { category:"Zwierzęta", main:"pies", impostor:"wilk" },
  { category:"Zwierzęta", main:"kot", impostor:"tygrys" },
  { category:"Zwierzęta", main:"delfin", impostor:"wieloryb" },
  { category:"Zwierzęta", main:"żaba", impostor:"ropucha" },
  { category:"Zwierzęta", main:"papuga", impostor:"kanarek" },
  { category:"Szkoła", main:"matematyka", impostor:"fizyka" },
  { category:"Szkoła", main:"zeszyt", impostor:"podręcznik" },
  { category:"Szkoła", main:"długopis", impostor:"ołówek" },
  { category:"Szkoła", main:"plecak", impostor:"piórnik" },
  { category:"Technologia", main:"laptop", impostor:"tablet" },
  { category:"Technologia", main:"Discord", impostor:"Messenger" },
  { category:"Technologia", main:"TikTok", impostor:"Instagram" },
  { category:"Technologia", main:"klawiatura", impostor:"kontroler" },
  { category:"Technologia", main:"ładowarka", impostor:"powerbank" },
  { category:"Gry", main:"Fortnite", impostor:"PUBG" },
  { category:"Gry", main:"Minecraft", impostor:"Terraria" },
  { category:"Gry", main:"Brawl Stars", impostor:"Clash Royale" },
  { category:"Gry", main:"Valorant", impostor:"Counter-Strike 2" },
  { category:"Gry", main:"EA Sports FC", impostor:"eFootball" },
  { category:"Filmy i seriale", main:"Shrek", impostor:"Kung Fu Panda" },
  { category:"Filmy i seriale", main:"Harry Potter", impostor:"Władca Pierścieni" },
  { category:"Filmy i seriale", main:"Avengers", impostor:"Liga Sprawiedliwości" },
  { category:"Filmy i seriale", main:"Toy Story", impostor:"Auta" },
  { category:"Muzyka", main:"Taylor Swift", impostor:"Ariana Grande" },
  { category:"Muzyka", main:"Mata", impostor:"Taco Hemingway" },
  { category:"Muzyka", main:"gitara", impostor:"ukulele" },
  { category:"Muzyka", main:"słuchawki", impostor:"głośnik" },
  { category:"Sport", main:"piłka nożna", impostor:"futsal" },
  { category:"Sport", main:"koszykówka", impostor:"siatkówka" },
  { category:"Sport", main:"rower", impostor:"hulajnoga" },
  { category:"Miasta", main:"Warszawa", impostor:"Kraków" },
  { category:"Miasta", main:"Paryż", impostor:"Londyn" },
  { category:"Miasta", main:"Barcelona", impostor:"Madryt" },
  { category:"Miasta", main:"Tokio", impostor:"Seul" },
  { category:"Kraje", main:"Polska", impostor:"Czechy" },
  { category:"Kraje", main:"Włochy", impostor:"Hiszpania" },
  { category:"Kraje", main:"Japonia", impostor:"Korea Południowa" },
  { category:"Kraje", main:"Norwegia", impostor:"Szwecja" },
  { category:"Minecraft", main:"Creeper", impostor:"Zombie" },
  { category:"Minecraft", main:"Enderman", impostor:"Warden" },
  { category:"Minecraft", main:"diament", impostor:"netherit" },
  { category:"Minecraft", main:"kilof", impostor:"łopata" },
  { category:"Minecraft", main:"Nether", impostor:"End" },
  { category:"Roblox", main:"Brookhaven", impostor:"Adopt Me!" },
  { category:"Roblox", main:"Doors", impostor:"Rainbow Friends" },
  { category:"Roblox", main:"Blox Fruits", impostor:"Anime Fighters Simulator" },
  { category:"Roblox", main:"Dress to Impress", impostor:"Royale High" },
  { category:"Pokémon", main:"Pikachu", impostor:"Eevee" },
  { category:"Pokémon", main:"Charmander", impostor:"Torchic" },
  { category:"Pokémon", main:"Squirtle", impostor:"Piplup" },
  { category:"Pokémon", main:"Bulbasaur", impostor:"Treecko" },
  { category:"Pokémon", main:"Mew", impostor:"Mewtwo" },
  { category:"Internet i memy", main:"YouTube", impostor:"TikTok" },
  { category:"Internet i memy", main:"Discord", impostor:"Reddit" },
  { category:"Internet i memy", main:"sigma", impostor:"gigachad" },
  { category:"Internet i memy", main:"meme", impostor:"gif" },
  { category:"Twórcy internetowi", main:"MrBeast", impostor:"KSI" },
  { category:"Twórcy internetowi", main:"Friz", impostor:"Rezi" },
  { category:"Twórcy internetowi", main:"IShowSpeed", impostor:"Kai Cenat" },
  { category:"Twórcy internetowi", main:"Dream", impostor:"TommyInnit" }
);

impostorWords.push(
  { category:"Jedzenie", main:"taco", impostor:"quesadilla" },
  { category:"Jedzenie", main:"hot dog", impostor:"burger" },
  { category:"Jedzenie", main:"sernik", impostor:"tiramisu" },
  { category:"Jedzenie", main:"paczki", impostor:"donuty" },
  { category:"Jedzenie", main:"kanapka", impostor:"tost" },
  { category:"Napoje", main:"cola", impostor:"pepsi" },
  { category:"Napoje", main:"herbata", impostor:"kawa" },
  { category:"Napoje", main:"lemoniada", impostor:"oranzada" },
  { category:"Napoje", main:"shake", impostor:"smoothie" },
  { category:"Napoje", main:"woda gazowana", impostor:"tonik" },
  { category:"Dom", main:"dywan", impostor:"wycieraczka" },
  { category:"Dom", main:"biurko", impostor:"stol" },
  { category:"Dom", main:"pralka", impostor:"zmywarka" },
  { category:"Dom", main:"pilot", impostor:"kontroler" },
  { category:"Dom", main:"poduszka", impostor:"koc" },
  { category:"Praca", main:"spotkanie", impostor:"prezentacja" },
  { category:"Praca", main:"mail", impostor:"wiadomosc" },
  { category:"Praca", main:"deadline", impostor:"egzamin" },
  { category:"Praca", main:"szef", impostor:"manager" },
  { category:"Praca", main:"drukarka", impostor:"skaner" },
  { category:"Podroze", main:"lotnisko", impostor:"dworzec" },
  { category:"Podroze", main:"hotel", impostor:"apartament" },
  { category:"Podroze", main:"walizka", impostor:"plecak" },
  { category:"Podroze", main:"paszport", impostor:"dowod" },
  { category:"Podroze", main:"plaza", impostor:"basen" },
  { category:"Aplikacje", main:"Netflix", impostor:"Disney Plus" },
  { category:"Aplikacje", main:"WhatsApp", impostor:"Telegram" },
  { category:"Aplikacje", main:"Google Maps", impostor:"Apple Maps" },
  { category:"Aplikacje", main:"Steam", impostor:"Epic Games" },
  { category:"Aplikacje", main:"Canva", impostor:"Photoshop" },
  { category:"Gry", main:"League of Legends", impostor:"Dota 2" },
  { category:"Gry", main:"GTA", impostor:"Saints Row" },
  { category:"Gry", main:"Among Us", impostor:"Town of Salem" },
  { category:"Gry", main:"Overwatch", impostor:"Paladins" },
  { category:"Gry", main:"Pokemon GO", impostor:"Ingress" },
  { category:"Filmy i seriale", main:"Spider-Man", impostor:"Batman" },
  { category:"Filmy i seriale", main:"Minionki", impostor:"Smerfy" },
  { category:"Filmy i seriale", main:"Wiedzmin", impostor:"Gra o tron" },
  { category:"Filmy i seriale", main:"Avatar", impostor:"Diuna" },
  { category:"Filmy i seriale", main:"Joker", impostor:"Deadpool" },
  { category:"Sport", main:"Formula 1", impostor:"MotoGP" },
  { category:"Sport", main:"silownia", impostor:"crossfit" },
  { category:"Sport", main:"ping pong", impostor:"tenis" },
  { category:"Sport", main:"lyzwy", impostor:"rolki" },
  { category:"Sport", main:"golf", impostor:"bilard" },
  { category:"Moda", main:"bluza", impostor:"sweter" },
  { category:"Moda", main:"adidasy", impostor:"trampki" },
  { category:"Moda", main:"czapka", impostor:"kapelusz" },
  { category:"Moda", main:"zegarek", impostor:"bransoletka" },
  { category:"Moda", main:"plecak", impostor:"torba" },
  { category:"Emocje", main:"radosc", impostor:"ekscytacja" },
  { category:"Emocje", main:"stres", impostor:"panika" },
  { category:"Emocje", main:"nuda", impostor:"zmeczenie" },
  { category:"Emocje", main:"zlosc", impostor:"irytacja" },
  { category:"Emocje", main:"wstyd", impostor:"trema" }
);

const normalizeWord = value => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const uniqueImpostorWords = new Map(impostorWords.map(item => [`${normalizeWord(item.category)}|${[normalizeWord(item.main), normalizeWord(item.impostor)].sort().join("|")}`, item]));
impostorWords.splice(0, impostorWords.length, ...uniqueImpostorWords.values());

export const impostorCategories = [...new Set(impostorWords.map(item => item.category))];
