// Zachowujemy dotychczasowe ID pytań, ale grupujemy je według nastroju rozgrywki.
const moodBySource={
  "Jedzenie":"Przyjemne","Muzyka":"Przyjemne","Relacje":"Przyjemne","Podróże":"Przyjemne","Pokémon":"Przyjemne","Sport":"Przyjemne",
  "Szkoła":"Nieprzyjemne","Trudne wybory":"Nieprzyjemne",
  "Gaming":"Neutralne","Internet":"Neutralne","Filmy i seriale":"Neutralne","Życie codzienne":"Neutralne","Dziwne":"Neutralne","Minecraft i Roblox":"Neutralne",
};
const q=(id,category,optionA,optionB,adult=false)=>({id,category:adult?"18+":moodBySource[category]||category,question:"Co wolisz?",optionA,optionB,adult});
export const wouldYouRatherQuestions=[
q("food_001","Jedzenie","Nigdy więcej nie jeść pizzy","Nigdy więcej nie jeść kebaba"),q("food_002","Jedzenie","Jeść tylko słodkie śniadania","Jeść tylko wytrawne śniadania"),q("food_003","Jedzenie","Zrezygnować z frytek","Zrezygnować z lodów"),q("food_004","Jedzenie","Dostać darmowe sushi co tydzień","Dostać darmową pizzę co tydzień"),q("food_005","Jedzenie","Jeść bardzo ostre potrawy","Jeść tylko łagodne potrawy"),q("food_006","Jedzenie","Zawsze pić ciepłą colę","Zawsze jeść zimne frytki"),q("food_007","Jedzenie","Umieć idealnie gotować","Mieć darmowe jedzenie na dowóz"),q("food_008","Jedzenie","Nigdy więcej nie jeść słodyczy","Nigdy więcej nie pić słodkich napojów"),
q("school_001","Szkoła","Mieć sprawdzian co tydzień","Mieć pracę domową codziennie"),q("school_002","Szkoła","Zawsze siedzieć w pierwszej ławce","Zawsze odpowiadać przy tablicy"),q("school_003","Szkoła","Być świetnym z matematyki","Być świetnym z języków"),q("school_004","Szkoła","Mieć dłuższe wakacje","Mieć krótsze lekcje"),q("school_005","Szkoła","Pisać tylko kartkówki","Robić tylko prezentacje"),q("school_006","Szkoła","Zapomnieć plecaka","Zapomnieć pracy domowej"),q("school_007","Szkoła","Mieć lekcje od 7:00","Mieć lekcje do 18:00"),q("school_008","Szkoła","Uczyć się wyłącznie online","Chodzić wyłącznie stacjonarnie"),
q("gaming_001","Gaming","Grać tylko w single player","Grać tylko w multiplayer"),q("gaming_002","Gaming","Grać zawsze z bardzo wysokim pingiem","Grać zawsze na 30 FPS"),q("gaming_003","Gaming","Stracić wszystkie skiny ze wszystkich swoich gier","Stracić wszystkie osiągnięcia ze wszystkich swoich gier"),q("gaming_004","Gaming","Dostać nową konsolę","Dostać mocny komputer"),q("gaming_005","Gaming","Grać tylko w jedną ulubioną grę","Codziennie losować inną grę"),q("gaming_006","Gaming","Zawsze grać ze znajomymi","Zawsze wygrywać solo"),q("gaming_007","Gaming","Mieć darmowe gry na Steamie","Mieć darmowy abonament konsolowy"),q("gaming_008","Gaming","Być pro graczem","Być popularnym streamerem"),
q("internet_001","Internet","Zrezygnować z TikToka","Zrezygnować z YouTube"),q("internet_002","Internet","Mieć internet tylko w telefonie","Mieć internet tylko na komputerze"),q("internet_003","Internet","Nigdy więcej nie używać emoji","Nigdy więcej nie wysyłać gifów"),q("internet_004","Internet","Mieć viralowy film","Mieć popularne konto przez rok"),q("internet_005","Internet","Czytać wszystkie komentarze","Nigdy nie czytać komentarzy"),q("internet_006","Internet","Stracić dostęp do social mediów","Stracić dostęp do streamingu"),q("internet_007","Internet","Zawsze mieć słabe Wi-Fi","Zawsze mieć 10% baterii"),q("internet_008","Internet","Pokazać znajomym historię wyszukiwania","Pokazać znajomym zapisane memy"),
q("music_001","Muzyka","Słuchać tylko jednego artysty","Nie móc słuchać ulubionego artysty"),q("music_002","Muzyka","Umieć śpiewać","Umieć grać na każdym instrumencie"),q("music_003","Muzyka","Dostać bilet na koncert","Poznać ulubionego artystę"),q("music_004","Muzyka","Słuchać muzyki tylko na słuchawkach","Słuchać muzyki tylko na głośniku"),q("music_005","Muzyka","Mieć świetny głos","Mieć idealne wyczucie rytmu"),q("music_006","Muzyka","Chodzić na małe koncerty","Chodzić na wielkie festiwale"),q("music_007","Muzyka","Słuchać tylko nowych hitów","Słuchać tylko starych klasyków"),q("music_008","Muzyka","Znać tekst każdej piosenki","Znać tytuł każdej piosenki"),
q("movies_001","Filmy i seriale","Oglądać tylko filmy","Oglądać tylko seriale"),q("movies_002","Filmy i seriale","Zagrać w filmie Marvela","Zagrać w filmie fantasy"),q("movies_003","Filmy i seriale","Znać wszystkie spoilery","Nigdy nie móc oglądać zwiastunów"),q("movies_004","Filmy i seriale","Chodzić tylko do kina","Oglądać wszystko tylko w domu"),q("movies_005","Filmy i seriale","Mieć Netflix","Mieć wszystkie kanały sportowe"),q("movies_006","Filmy i seriale","Obejrzeć maraton horrorów","Obejrzeć maraton komedii romantycznych"),q("movies_007","Filmy i seriale","Zagrać czarny charakter","Zagrać głównego bohatera"),q("movies_008","Filmy i seriale","Zapomnieć ulubiony film i obejrzeć go pierwszy raz","Pamiętać każdą scenę ulubionego filmu"),
q("daily_001","Życie codzienne","Zawsze wstawać wcześnie","Zawsze chodzić spać późno"),q("daily_002","Życie codzienne","Nie używać windy","Nie używać samochodu"),q("daily_003","Życie codzienne","Mieć darmowe podróże","Mieć darmowe jedzenie"),q("daily_004","Życie codzienne","Nigdy się nie spóźniać","Nigdy niczego nie zapominać"),q("daily_005","Życie codzienne","Mieszkać w centrum miasta","Mieszkać blisko natury"),q("daily_006","Życie codzienne","Zawsze mieć idealną pogodę","Zawsze mieć idealną temperaturę w pokoju"),q("daily_007","Życie codzienne","Mieć więcej czasu","Mieć więcej pieniędzy"),q("daily_008","Życie codzienne","Sprzątać codziennie po 15 minut","Sprzątać cały dzień raz w miesiącu"),
q("weird_001","Dziwne","Mówić tylko szeptem","Mówić wszystko śpiewając"),q("weird_002","Dziwne","Mieć ręce zamiast stóp","Mieć stopy zamiast rąk"),q("weird_003","Dziwne","Rozumieć zwierzęta","Rozumieć wszystkie języki"),q("weird_004","Dziwne","Zawsze mieć mokre skarpetki","Zawsze mieć piasek w butach"),q("weird_005","Dziwne","Kichać za każdym razem, gdy kłamiesz","Czkawką zdradzać każdy sekret"),q("weird_006","Dziwne","Mieć prywatnego smoka","Mieć teleport"),q("weird_007","Dziwne","Nigdy więcej nie widzieć memów","Widzieć tylko stare memy"),q("weird_008","Dziwne","Zamienić się w kota na tydzień","Zamienić się w psa na tydzień"),
q("hard_001","Trudne wybory","Znać przyszłość","Móc zmienić jedną rzecz z przeszłości"),q("hard_002","Trudne wybory","Być sławnym","Być bardzo bogatym i anonimowym"),q("hard_003","Trudne wybory","Mieć wymarzoną pracę","Mieć dużo wolnego czasu"),q("hard_004","Trudne wybory","Zawsze mówić prawdę","Zawsze wiedzieć, kiedy ktoś kłamie"),q("hard_005","Trudne wybory","Mieszkać rok za granicą","Nigdy nie wyjechać z kraju"),q("hard_006","Trudne wybory","Czytać w myślach","Być niewidzialnym"),q("hard_007","Trudne wybory","Wygrać milion teraz","Dostawać wygodną pensję do końca życia"),q("hard_008","Trudne wybory","Nigdy nie odczuwać stresu","Nigdy nie odczuwać zmęczenia"),
q("relations_001","Relacje","Mieć wielu znajomych","Mieć kilku bardzo bliskich znajomych"),q("relations_002","Relacje","Zorganizować dużą imprezę","Spędzić spokojny wieczór z najbliższymi"),q("relations_003","Relacje","Zawsze wybierać miejsce spotkania","Nigdy nie musieć nic organizować"),q("relations_004","Relacje","Powiedzieć komuś trudną prawdę","Przemilczeć ją dla jego spokoju"),q("relations_005","Relacje","Mieć przyjaciela bardzo podobnego do ciebie","Mieć przyjaciela zupełnie innego od ciebie"),q("relations_006","Relacje","Poznać nowych ludzi na żywo","Poznać nowych ludzi przez internet"),q("relations_007","Relacje","Dostać ręcznie zrobiony prezent","Dostać drogi prezent"),q("relations_008","Relacje","Mieć zawsze rację w kłótni","Zawsze szybko się pogodzić"),
q("adult_001","18+","Pójść na randkę w ciemno","Napisać pierwszy do dawnego crusha",true),q("adult_002","18+","Pokazać znajomym ostatnią wiadomość do crusha","Pokazać ostatnie wyszukiwanie profilu na Instagramie",true),q("adult_003","18+","Być na bardzo romantycznej randce","Być na spontanicznej randce bez planu",true),q("adult_004","18+","Dostać miłosny list","Dostać niespodziewany flirtujący tekst",true),q("adult_005","18+","Umówić się z kimś bardzo zabawnym","Umówić się z kimś bardzo romantycznym",true),q("adult_006","18+","Przyznać się do crusha znajomym","Napisać crushowi pierwszy",true),q("adult_007","18+","Pocałunek na pierwszej randce","Trzymać się za ręce na pierwszej randce",true),q("adult_008","18+","Mieć partnera, który planuje niespodzianki","Mieć partnera, który zawsze pyta o zdanie",true),
q("gaming_009","Gaming","Grać rok tylko w Minecraft","Grać rok tylko w Roblox"),q("gaming_010","Gaming","Spotkać creepera w kopalni w Minecraft","Spotkać wardena w jaskini w Minecraft"),q("gaming_011","Gaming","Budować ogromne bazy w grach","Robić speedruny w grach"),q("gaming_012","Gaming","Mieć wszystkie skiny w Fortnite","Mieć nieskończone Robuxy"),q("gaming_013","Gaming","Grać z Dreamem w Minecraft","Grać z IShowSpeedem w FIFA"),q("gaming_014","Gaming","Być świetnym w PvP w grach","Być mistrzem budowania baz w grach"),q("internet_009","Internet","Oglądać tylko polski YouTube","Oglądać tylko zagraniczny YouTube"),q("internet_010","Internet","Mieć milion subów na YouTube","Mieć milion obserwujących na TikToku"),q("internet_011","Internet","Spędzić dzień bez Discorda","Spędzić dzień bez YouTube"),q("internet_012","Internet","Nagrać viralowy film z ekipą","Wystąpić w filmie ulubionego twórcy"),q("weird_009","Dziwne","Mieć creepera jako zwierzaka","Mieć endermana jako ochroniarza"),q("weird_010","Dziwne","Móc teleportować się jak enderman","Móc latać na elytrze"),q("food_009","Jedzenie","Jeść pizzę bez sera","Jeść frytki bez sosu"),q("daily_009","Życie codzienne","Zawsze mieć pełną baterię","Zawsze mieć idealny internet"),q("relations_009","Relacje","Grać całą noc ze znajomymi","Jechać ze znajomymi na spontaniczny wyjazd")
];
wouldYouRatherQuestions.push(
  q("food_010","Jedzenie","Jeść tylko pizzę przez miesiąc","Jeść tylko kebab przez miesiąc"),
  q("food_011","Jedzenie","Zrezygnować z czekolady","Zrezygnować z chipsów"),
  q("food_012","Jedzenie","Dostawać darmowe sushi","Dostawać darmowe burgery"),
  q("food_013","Jedzenie","Jeść tylko słodkie śniadania","Jeść tylko słone śniadania"),
  q("school_009","Szkoła","Mieć codziennie pierwszą lekcję wolną","Kończyć codziennie godzinę wcześniej"),
  q("school_010","Szkoła","Pisać sprawdzian z matematyki","Odpowiadać przy całej klasie z historii"),
  q("school_011","Szkoła","Mieć najlepsze oceny","Mieć najwięcej wolnego czasu"),
  q("school_012","Szkoła","Chodzić do szkoły w soboty krócej","Chodzić dłużej od poniedziałku do piątku"),
  q("gaming_015","Gaming","Mieć idealny aim","Mieć idealny refleks"),
  q("gaming_016","Gaming","Grać tylko w gry retro","Grać tylko w nowe premiery"),
  q("gaming_017","Gaming","Mieć własny serwer Minecraft","Mieć własną popularną grę Roblox"),
  q("gaming_018","Gaming","Zagrać z ulubionym streamerem","Dostać każdy skin w ulubionej grze"),
  q("gaming_019","Gaming","Grać tylko na klawiaturze","Grać tylko na padzie"),
  q("internet_013","Internet","Usunąć wszystkie zapisane memy","Usunąć całą historię wiadomości"),
  q("internet_014","Internet","Mieć milion wyświetleń jednego filmu","Mieć stałą małą społeczność"),
  q("internet_015","Internet","Nie używać telefonu po 20:00","Nie używać telefonu przed południem"),
  q("internet_016","Internet","Zostać popularnym na TikToku","Zostać popularnym na YouTube"),
  q("music_009","Muzyka","Być na koncercie Taylor Swift","Być na koncercie ulubionego polskiego artysty"),
  q("music_010","Muzyka","Słuchać tylko rapu","Słuchać tylko popu"),
  q("music_011","Muzyka","Nauczyć się grać na gitarze","Nauczyć się grać na pianinie"),
  q("movies_009","Filmy i seriale","Mieszkać w świecie Harry'ego Pottera","Mieszkać w świecie Marvela"),
  q("movies_010","Filmy i seriale","Oglądać tylko animacje","Oglądać tylko filmy aktorskie"),
  q("movies_011","Filmy i seriale","Spotkać Shreka","Spotkać Spider-Mana"),
  q("daily_010","Życie codzienne","Mieć zawsze czysty pokój","Mieć zawsze pełną lodówkę"),
  q("daily_011","Życie codzienne","Móc teleportować się do szkoły lub pracy","Móc spać godzinę dłużej"),
  q("daily_012","Życie codzienne","Nie musieć nigdy gotować","Nie musieć nigdy sprzątać"),
  q("weird_011","Dziwne","Mieć głos jak robot","Chodzić jak postać z gry"),
  q("weird_012","Dziwne","Znaleźć portal do Netheru","Znaleźć prawdziwego Pokémona"),
  q("weird_013","Dziwne","Mieć gadającego kota","Mieć psa, który umie pisać wiadomości"),
  q("hard_009","Trudne wybory","Pamiętać wszystko","Móc zapomnieć każdą żenującą sytuację"),
  q("hard_010","Trudne wybory","Mieć talent do każdej gry","Mieć talent do każdego sportu"),
  q("hard_011","Trudne wybory","Znać odpowiedź na każde pytanie","Zawsze wiedzieć, co powiedzieć"),
  q("relations_010","Relacje","Zorganizować nocny maraton gier","Zorganizować spontaniczny wyjazd"),
  q("relations_011","Relacje","Dostać od znajomego idealny mem","Dostać od znajomego idealny prezent"),
  q("relations_012","Relacje","Mieć ekipę online z całego świata","Mieć ekipę zawsze dostępną na żywo"),
  q("minecraft_001","Minecraft i Roblox","Spotkać creepera w domu","Spotkać wardena w kopalni"),
  q("minecraft_002","Minecraft i Roblox","Mieć kilof z Minecrafta","Mieć portal do dowolnej gry Roblox"),
  q("minecraft_003","Minecraft i Roblox","Zbudować ogromny zamek w survivalu","Przejść trudne obby bez ani jednego upadku"),
  q("minecraft_004","Minecraft i Roblox","Dostać nieskończone diamenty","Dostać nieskończone Robuxy"),
  q("pokemon_001","Pokémon","Mieć Pikachu","Mieć Eevee"),
  q("pokemon_002","Pokémon","Wybrać Charmandera","Wybrać Squirtle'a"),
  q("pokemon_003","Pokémon","Złapać Mew","Złapać Mewtwo"),
  q("pokemon_004","Pokémon","Podróżować z Ash'em","Zostać liderem sali Pokémon"),
  q("travel_001","Podróże","Pojechać do Japonii","Pojechać do USA"),
  q("travel_002","Podróże","Spędzić tydzień nad morzem","Spędzić tydzień w górach"),
  q("travel_003","Podróże","Podróżować samolotem","Podróżować pociągiem"),
  q("sport_001","Sport","Spotkać Ronaldo","Spotkać Messiego"),
  q("sport_002","Sport","Obejrzeć finał mundialu","Obejrzeć finał Ligi Mistrzów"),
  q("adult_009","18+","Dostać od crusha zabawną wiadomość","Dostać od crusha romantyczną wiadomość",true),
  q("adult_010","18+","Pójść na randkę do kina","Pójść na randkę na spacer",true),
  q("adult_011","18+","Powiedzieć znajomym, kto ci się podoba","Pozwolić znajomym wybrać ci randkę",true)
);

wouldYouRatherQuestions.push(
  q("pleasant_001","Przyjemne","Dostać bilety na dowolny koncert","Dostać bilety na dowolny mecz"),
  q("pleasant_002","Przyjemne","Spędzić weekend w domku w górach","Spędzić weekend nad ciepłym morzem"),
  q("pleasant_003","Przyjemne","Mieć zawsze wolne piątki","Mieć dwa miesiące wakacji więcej"),
  q("pleasant_004","Przyjemne","Dostać idealny prezent-niespodziankę","Zaplanować idealny dzień ze znajomymi"),
  q("pleasant_005","Przyjemne","Umieć teleportować się na wakacje","Móc zatrzymywać czas na drzemkę"),
  q("pleasant_006","Przyjemne","Mieć pokój kinowy w domu","Mieć własny pokój gamingowy"),
  q("unpleasant_001","Nieprzyjemne","Zawsze mieć 1% baterii","Zawsze mieć bardzo wolny internet"),
  q("unpleasant_002","Nieprzyjemne","Stać godzinę w korku","Stać godzinę w długiej kolejce"),
  q("unpleasant_003","Nieprzyjemne","Obudzić się godzinę za późno","Przyjść godzinę za wcześnie"),
  q("unpleasant_004","Nieprzyjemne","Przez tydzień nie używać telefonu","Przez tydzień nie używać komputera"),
  q("unpleasant_005","Nieprzyjemne","Zawsze zapominać ładowarki","Zawsze zapominać słuchawek"),
  q("unpleasant_006","Nieprzyjemne","Mieć mokre buty przez cały dzień","Mieć rękaw bluzy zahaczający o każdą klamkę"),
  q("neutral_001","Neutralne","Zawsze wybierać film dla ekipy","Zawsze wybierać grę dla ekipy"),
  q("neutral_002","Neutralne","Grać wieczorem w planszówki","Grać wieczorem online"),
  q("neutral_003","Neutralne","Mieszkać w dużym mieście","Mieszkać w małej miejscowości"),
  q("neutral_004","Neutralne","Rozmawiać tylko głosowo","Pisać tylko wiadomości"),
  q("neutral_005","Neutralne","Oglądać serię odcinków naraz","Oglądać po jednym odcinku dziennie"),
  q("neutral_006","Neutralne","Zawsze grać pierwszą turę","Zawsze grać ostatnią turę"),
  q("adult_012","18+","Pójść na podwójną randkę ze znajomymi","Pójść na spokojną randkę tylko we dwoje",true),
  q("adult_013","18+","Dostać od crusha głosówkę","Dostać od crusha długą wiadomość",true),
  q("adult_014","18+","Zrobić pierwszy krok na imprezie","Czekać, aż druga osoba zrobi pierwszy krok",true),
  q("adult_015","18+","Mieć odważny flirt przez wiadomości","Mieć romantyczną rozmowę do późna",true)
);

wouldYouRatherQuestions.push(
  q("adult_016","18+","Wysłać odważną wiadomość osobie, która ci się podoba","Powiedzieć jej to samo prosto w oczy",true),
  q("adult_017","18+","Pocałować kogoś na pierwszej randce","Czekać z pocałunkiem do kolejnego spotkania",true),
  q("adult_018","18+","Mieć jedną bardzo intensywną noc","Mieć spokojny romantyczny weekend tylko we dwoje",true),
  q("adult_019","18+","Powiedzieć partnerowi o swojej najbardziej odważnej fantazji","Usłyszeć jego najbardziej odważną fantazję",true),
  q("adult_020","18+","Uprawiać seks przy zapalonym świetle","Uprawiać seks wyłącznie po ciemku",true),
  q("adult_021","18+","Mieć seks bez zobowiązań z kimś znajomym","Pójść na randkę z kimś zupełnie nowym",true),
  q("adult_022","18+","Przyznać się znajomym do najbardziej żenującej randki","Przyznać się partnerowi do najbardziej żenującej historii z imprezy",true),
  q("adult_023","18+","Dostać bardzo odważne zdjęcie od partnera","Dostać bardzo odważną wiadomość głosową od partnera",true),
  q("adult_024","18+","Zostać przyłapanym podczas pocałunku","Przypadkiem przeczytać przy znajomych swoją najbardziej flirtującą wiadomość",true),
  q("adult_025","18+","Mieć partnera bardzo romantycznego","Mieć partnera bardzo namiętnego",true),
  q("adult_026","18+","Zrobić pierwszy krok w klubie","Napisać pierwszą odważną wiadomość po imprezie",true),
  q("adult_027","18+","Pocałować swojego dawnego crusha","Pójść na randkę z osobą, która od dawna ma crusha na ciebie",true),
  q("adult_028","18+","Opowiedzieć partnerowi o swoim największym turn-onie","Zapytać partnera o jego największy turn-on",true),
  q("adult_029","18+","Mieć randkę zakończoną spontaniczną nocą razem","Mieć randkę zakończoną długą rozmową do rana",true),
  q("adult_030","18+","Flirtować bardzo bezpośrednio","Budować napięcie powoli przez cały wieczór",true),
  q("adult_031","18+","Dostać masaż od partnera","Zrobić masaż partnerowi",true),
  q("adult_032","18+","Mieć odważną rozmowę przez wiadomości","Mieć tę samą rozmowę twarzą w twarz",true),
  q("adult_033","18+","Wyjść z imprezy wcześniej z osobą, która ci się podoba","Zostać do końca i flirtować z nią przez cały wieczór",true),
  q("adult_034","18+","Zdradzić partnerowi swój największy turn-off","Usłyszeć od partnera jego największy turn-off",true),
  q("adult_035","18+","Mieć partnera, który często inicjuje zbliżenia","Samemu częściej inicjować zbliżenia",true)
);

// Osobna pula dla dorosłych. Nie trafia do domyślnego losowania.
// Zostawiamy wyłącznie scenariusze między świadomie zgadzającymi się dorosłymi.
const adultSpicyQuestions=[
  q("adult_spicy_001","18+","Nigdy więcej się nie masturbować","Nigdy więcej nie uprawiać seksu",true),
  q("adult_spicy_002","18+","Być dominującą osobą w łóżku","Być uległą osobą w łóżku",true),
  q("adult_spicy_003","18+","Seks szybki i intensywny","Seks długi i bardzo czuły",true),
  q("adult_spicy_004","18+","Zawsze uprawiać seks przy zapalonym świetle","Zawsze uprawiać seks wyłącznie po ciemku",true),
  q("adult_spicy_005","18+","Seks wyłącznie na misjonarza","Seks wyłącznie od tyłu",true),
  q("adult_spicy_006","18+","Dostawać klapsy za zgodą","Dawać klapsy za zgodą",true),
  q("adult_spicy_007","18+","Być związanym za zgodą","Wiązać partnera za zgodą",true),
  q("adult_spicy_008","18+","Kajdanki i opaska na oczy","Liny shibari",true),
  q("adult_spicy_009","18+","Delikatny romantyczny seks","Ostry seks BDSM z ustalonymi granicami",true),
  q("adult_spicy_010","18+","Seks z miłości","Seks bez zobowiązań",true),
  q("adult_spicy_011","18+","Seks w samochodzie w prywatnym miejscu","Seks w hotelu",true),
  q("adult_spicy_012","18+","Seks w saunie tylko we dwoje","Seks w jacuzzi tylko we dwoje",true),
  q("adult_spicy_013","18+","Seks w lesie w odludnym miejscu","Seks na pustej plaży nocą",true),
  q("adult_spicy_014","18+","Seks z bardzo głośnym partnerem","Seks z bardzo cichym partnerem",true),
  q("adult_spicy_015","18+","Partner bardzo doświadczony","Partner, który dopiero odkrywa swoje preferencje",true),
  q("adult_spicy_016","18+","Zawsze patrzeć sobie w oczy podczas seksu","Nigdy nie patrzeć sobie w oczy podczas seksu",true),
  q("adult_spicy_017","18+","Zawsze całować się podczas seksu","Skupiać się na innych rzeczach niż pocałunki",true),
  q("adult_spicy_018","18+","Seks trwający 5 minut, ale bardzo intensywny","Seks trwający 40 minut, ale spokojniejszy",true),
  q("adult_spicy_019","18+","Codzienny szybki seks","Długi seks raz w tygodniu",true),
  q("adult_spicy_020","18+","Mieć idealne życie seksualne i przeciętny związek","Mieć idealny związek i przeciętne życie seksualne",true),
  q("adult_spicy_021","18+","Opowiedzieć partnerowi wszystkie swoje fantazje","Usłyszeć wszystkie fantazje partnera",true),
  q("adult_spicy_022","18+","Dostać od partnera odważne zdjęcie","Dostać od partnera bardzo odważną wiadomość głosową",true),
  q("adult_spicy_023","18+","Wysłać partnerowi odważne zdjęcie","Nagrać partnerowi odważną wiadomość głosową",true),
  q("adult_spicy_024","18+","Mieć nagranie tylko dla was dwojga","Robić tylko prywatne zdjęcia dla partnera",true),
  q("adult_spicy_025","18+","Nigdy więcej nie oglądać pornografii","Nigdy więcej nie pić alkoholu",true),
  q("adult_spicy_026","18+","Przez rok nie masturbować się","Przez rok nie oglądać pornografii",true),
  q("adult_spicy_027","18+","Nigdy więcej nie flirtować","Nigdy więcej nie chodzić na randki",true),
  q("adult_spicy_028","18+","Mieć tylko jednego partnera przez całe życie","Nigdy nie mieć stałego partnera",true),
  q("adult_spicy_029","18+","Partner bardzo zazdrosny","Partner bardzo flirtujący",true),
  q("adult_spicy_030","18+","Znać każdy sekret partnera","Pozwolić partnerowi poznać każdy swój sekret",true),
  q("adult_spicy_031","18+","Stracić wszystkie wspomnienia ze związków","Stracić wszystkie prywatne zdjęcia z telefonu",true),
  q("adult_spicy_032","18+","Miesiąc mieszkać z byłym partnerem","Miesiąc mieszkać z osobą, której najbardziej nie lubisz",true),
  q("adult_spicy_033","18+","Wysłać przypadkiem prywatną wiadomość rodzinie","Wysłać ją przypadkiem całej paczce znajomych",true),
  q("adult_spicy_034","18+","Pokazać znajomym historię wyszukiwania","Pokazać znajomym wszystkie prywatne wiadomości",true),
  q("adult_spicy_035","18+","Przyznać się znajomym do liczby swoich partnerów","Pokazać znajomym stan swojego konta bankowego",true),
  q("adult_spicy_036","18+","Doggy style","Cowgirl",true),
  q("adult_spicy_037","18+","Reverse cowgirl","Spooning",true),
  q("adult_spicy_038","18+","Pozycja 69","Oral na zmianę",true),
  q("adult_spicy_039","18+","Pozycja lotus twarzą w twarz","Pozycja na stojąco",true),
  q("adult_spicy_040","18+","Seks na łóżku","Seks na kanapie",true),
  q("adult_spicy_041","18+","Tylko pozycje z patrzeniem sobie w oczy","Tylko pozycje bez patrzenia sobie w oczy",true),
  q("adult_spicy_042","18+","Seks analny","Seks waginalny",true),
  q("adult_spicy_043","18+","Dawać oral","Dostawać oral",true),
  q("adult_spicy_044","18+","Lizać cipkę","Dostawać lizanie cipki",true),
  q("adult_spicy_045","18+","Robić loda","Dostawać loda",true),
  q("adult_spicy_046","18+","Rimming za zgodą","Dostawać rimming za zgodą",true),
  q("adult_spicy_047","18+","Seks z wibratorem","Seks bez żadnych zabawek",true),
  q("adult_spicy_048","18+","Plug analny","Klamry na sutki",true),
  q("adult_spicy_049","18+","Wibrator","Strap-on",true),
  q("adult_spicy_050","18+","Edging przez godzinę","Kilka orgazmów z rzędu",true),
  q("adult_spicy_051","18+","Skończyć wewnątrz za zgodą partnera","Skończyć na zewnątrz",true),
  q("adult_spicy_052","18+","Creampie za zgodą partnera","Skończyć na twarz za zgodą partnera",true),
  q("adult_spicy_053","18+","Squirt","Creampie za zgodą partnera",true),
  q("adult_spicy_054","18+","Seks z osobą całkowicie wygoloną","Seks z osobą naturalną",true),
  q("adult_spicy_055","18+","Seks z osobą z tatuażami i piercingiem","Seks z osobą bez tatuaży i piercingu",true),
  q("adult_spicy_056","18+","Nazywać partnera tatusiem lub mamusią","Używać w łóżku odważniejszych wyzwisk za obopólną zgodą",true),
  q("adult_spicy_057","18+","Mieć trójkąt MMF","Mieć trójkąt FFM",true),
  q("adult_spicy_058","18+","Trójkąt raz w życiu","Regularny seks tylko we dwoje",true),
  q("adult_spicy_059","18+","Trójkąt z partnerem i obcą osobą","Trójkąt z partnerem i bliskim znajomym",true),
  q("adult_spicy_060","18+","Klasyczny trójkąt","Seks grupowy z większą liczbą dorosłych osób",true),
  q("adult_spicy_061","18+","Być w środku trójkąta","Być na końcu trójkąta",true),
  q("adult_spicy_062","18+","Seks grupowy, w którym wszyscy są bi","Seks grupowy z ustalonymi parami",true),
  q("adult_spicy_063","18+","Seks z kimś z paczki znajomych","Seks z całkowicie obcą dorosłą osobą",true),
  q("adult_spicy_064","18+","Jednorazowy seks po randce","Regularny friends with benefits",true),
  q("adult_spicy_065","18+","Wysłać nudesy zaufanej osobie","Dostać nudesy od zaufanej osoby",true),
  q("adult_spicy_066","18+","Powiedzieć partnerowi o swoim największym turn-onie","Powiedzieć partnerowi o swoim największym turn-offie",true),
  q("adult_spicy_067","18+","Zrobić pierwszy krok w klubie","Napisać pierwszą odważną wiadomość po imprezie",true),
  q("adult_spicy_068","18+","Wyjść wcześniej z imprezy z osobą, która ci się podoba","Zostać do końca i flirtować przez cały wieczór",true),
  q("adult_spicy_069","18+","Nigdy więcej nie pić piwa","Nigdy więcej nie pić wódki",true),
  q("adult_spicy_070","18+","Pić do końca życia tylko szampana","Pić do końca życia tylko tanie wino",true),
  q("adult_spicy_071","18+","Mieć dwudniowego kaca po każdej imprezie","Zawsze być trzeźwą osobą na imprezie",true),
  q("adult_spicy_072","18+","Być osobą, która zawsze stawia kolejkę","Być osobą, która nigdy nie stawia kolejki",true),
  q("adult_spicy_073","18+","Przez rok nie imprezować","Przez rok nie randkować",true),
  q("adult_spicy_074","18+","Zawsze mówić prawdę po alkoholu","Zawsze publikować swoje imprezowe przemyślenia w internecie",true),
  q("adult_spicy_075","18+","Obudzić się po imprezie bez telefonu","Obudzić się po imprezie ze wstydliwymi wiadomościami wysłanymi do znajomych",true),
  q("adult_spicy_076","18+","Seks gejowski do końca życia","Seks heteroseksualny do końca życia",true),
  q("adult_spicy_077","18+","Dawać anal","Brać anal",true),
  q("adult_spicy_078","18+","Być dominującym topem","Być uległym bottomem",true),
  q("adult_spicy_079","18+","Seks z bardzo męskim brodatym facetem","Seks z delikatnym wysportowanym twinkiem",true),
  q("adult_spicy_080","18+","Seks z bardzo kobiecą dziewczyną","Seks z dziewczyną w stylu tomboy",true),
  q("adult_spicy_081","18+","Tribbing","Pozycja 69",true),
  q("adult_spicy_082","18+","Dominująca partnerka","Uległa partnerka",true),
  q("adult_spicy_083","18+","Seks tylko z jedną osobą","Seks z dwiema dorosłymi osobami naraz",true),
  q("adult_spicy_084","18+","Zapytać partnera o najodważniejszą fantazję","Samemu pierwszemu zdradzić najodważniejszą fantazję",true),
  q("adult_spicy_085","18+","Mieć idealną technikę oralną","Mieć idealną kondycję podczas seksu",true),
  q("adult_spicy_086","18+","Zawsze inicjować seks","Zawsze czekać, aż partner zainicjuje seks",true),
  q("adult_spicy_087","18+","Seks tylko rano","Seks tylko późno w nocy",true),
  q("adult_spicy_088","18+","Seks podczas romantycznego wyjazdu","Seks po spontanicznej randce",true),
  q("adult_spicy_089","18+","Mieć partnera bardzo czułego","Mieć partnera bardzo namiętnego",true),
  q("adult_spicy_090","18+","Nigdy więcej nie odczuwać zakochania","Nigdy więcej nie odczuwać pożądania",true)
];
const adultPairKey=item=>[item.optionA,item.optionB].map(value=>String(value).toLowerCase().trim()).sort().join("|");
const uniqueAdultQuestions=[...new Map(adultSpicyQuestions.map(item=>[adultPairKey(item),item])).values()];
wouldYouRatherQuestions.splice(0,wouldYouRatherQuestions.length,...wouldYouRatherQuestions.filter(item=>!item.adult),...uniqueAdultQuestions);

export const wouldYouRatherCategories=["Przyjemne","Nieprzyjemne","Neutralne","18+"];
