// Dopisuj hasła do tablicy wybranej kategorii lub dodaj nową kategorię z własną tablicą.
export const identityCategories = {
  "Postacie z bajek":["Shrek","Elsa","Kubuś Puchatek","Myszka Miki","Scooby-Doo","SpongeBob","Król Lew","Pikachu","Minionek","Vaiana","Arielka","Kaczor Donald","Tom","Jerry","Pszczółka Maja","Gargamel"],
  "Postacie z filmów":["Harry Potter","Darth Vader","Indiana Jones","Spider-Man","Batman","Barbie","Rocky Balboa","Jack Sparrow","Forrest Gump","James Bond","Wednesday Addams","Hulk","Neo","Hermiona Granger","Shrek","Wolverine"],
  "Postacie z gier":["Mario","Sonic","Steve z Minecrafta","Kratos","Lara Croft","Geralt","Pac-Man","Link","Kirby","Master Chief","CJ z GTA","Agent 47","Pikachu","Crash Bandicoot","Leon Kennedy","Ezio Auditore"],
  "Celebryci i artyści":["Taylor Swift","Robert Lewandowski","Sanah","Dawid Podsiadło","Lady Gaga","The Weeknd","Billie Eilish","Rihanna","Mata","Taco Hemingway","Iga Świątek","Cristiano Ronaldo","Lionel Messi","Ariana Grande","Ed Sheeran","Dua Lipa"],
  "Zwierzęta":["pies","kot","żyrafa","pingwin","rekin","słoń","wilk","lis","krokodyl","delfin","panda","kangur","papuga","żaba","koń","chomik"],
  "Zawody":["lekarz","strażak","nauczyciel","programista","kucharz","pilot","fryzjer","policjant","aktor","fotograf","mechanik","weterynarz","architekt","prawnik","kelner","astronauta"],
  "Przedmioty":["parasol","lodówka","telefon","krzesło","plecak","szczoteczka do zębów","klucz","lustro","czajnik","słuchawki","poduszka","odkurzacz","widelec","latarka","zegarek","walizka"],
  "Jedzenie":["pizza","burger","pierogi","sushi","rosół","naleśniki","kebab","lody","czekolada","frytki","spaghetti","sałatka","tost","ramen","popcorn","sernik"],
  "Marki":["Nike","Adidas","Apple","Samsung","Netflix","Spotify","Lego","IKEA","Coca-Cola","McDonald's","PlayStation","Xbox","YouTube","TikTok","Zara","Żabka"],
  "Kraje":["Polska","Japonia","Włochy","Hiszpania","USA","Kanada","Brazylia","Egipt","Australia","Norwegia","Niemcy","Francja","Grecja","Meksyk","Indie","Islandia"],
  "Miasta":["Warszawa","Kraków","Gdańsk","Wrocław","Paryż","Londyn","Nowy Jork","Tokio","Rzym","Barcelona","Berlin","Praga","Wenecja","Dubaj","Sopot","Zakopane"],
  "Memy i internet":["rickroll","sigma","gigachad","NPC","streamer","influencer","meme","selfie","hashtag","viral","scrollowanie TikToka","subskrypcja","emoji","Discord","YouTube Shorts","streak"],
  "Minecraft":["Creeper","Zombie","Szkielet","Enderman","Warden","Wieśniak","Żelazny golem","Steve","Alex","Herobrine","Wither","Ender Dragon","Ghast","Blaze","Piglin","Wiedźma","Axolotl","Pszczoła","Shulker","Pillager"],
  "Roblox":["noob z Roblox","gracz Brookhaven","gracz Adopt Me","Blox Fruits","Doors","Piggy","Tower of Hell","obby","Robux","avatar Roblox","Pet Simulator","Murder Mystery 2","Dress to Impress","Jailbreak","Arsenal","Rainbow Friends"],
  "Twórcy internetowi":["MrBeast","PewDiePie","IShowSpeed","Kai Cenat","Dream","Technoblade","TommyInnit","DanTDM","Friz","Rezi","Blowek","Mandzio","Gimper","Izak","Wersow","Wardęga","Eleven","Vertez","SKKF","KSI"],
  "Gry popularne":["Minecraft","Roblox","Fortnite","GTA V","The Sims","Brawl Stars","Among Us","Valorant","Counter-Strike","League of Legends","EA FC","Rocket League","Terraria","Subnautica","Pokémon","Mario Kart","Clash Royale","Fall Guys","Stardew Valley","Wiedźmin"],
};
const identityExtras = {
  "Postacie z bajek":["Prosiaczek","Tygrysek","Królik Bugs","Minnie","Goofy","Shaggy","Patryk Rozgwiazda","Skalmar","Anna","Olaf","Stich","Simba","Timon","Pumba","Osioł","Kot w butach","Gru","Po","Król Julian","Peppa","Bluey","Asterix","Obelix","Bolek","Lolek","Reksio","Muminek"],
  "Postacie z filmów":["Ron Weasley","Voldemort","Luke Skywalker","Yoda","Gandalf","Frodo","Gollum","Legolas","Katniss Everdeen","Terminator","Rambo","John Wick","Iron Man","Thor","Kapitan Ameryka","Deadpool","Thanos","Wonder Woman","Harley Quinn","Joker","Willy Wonka","Kevin McCallister","Marty McFly","Gru","Ken"],
  "Postacie z gier":["Luigi","Alex","Creeper","Enderman","Zelda","Ciri","Trevor","Franklin","Michael","Tommy Vercetti","Arthur Morgan","Joel","Ellie","Rayman","Sub-Zero","Scorpion","Chun-Li","Ryu","Sans","Cuphead","Freddy Fazbear","Jonesy","Peely","Shelly","Spike","Leon","Dynamike"],
  "Celebryci i artyści":["Beyoncé","Shakira","Bruno Mars","Justin Bieber","Eminem","Snoop Dogg","Drake","Post Malone","Harry Styles","Miley Cyrus","Selena Gomez","Katy Perry","Michael Jackson","Freddie Mercury","Quebonafide","Bedoes","Young Leosia","Doda","Maryla Rodowicz","Kylian Mbappé","Usain Bolt","LeBron James","Michael Jordan","Mariusz Pudzianowski"],
  "Zwierzęta":["królik","świnka morska","kanarek","krowa","świnia","owca","koza","kura","kaczka","gęś","bocian","orzeł","sowa","flaming","lew","tygrys","gepard","zebra","nosorożec","hipopotam","małpa","goryl","koala","niedźwiedź","wieloryb","ośmiornica","żółw","wąż","pszczoła","motyl"],
  "Zawody":["pielęgniarka","dentysta","psycholog","trener","piłkarz","youtuber","streamer","influencer","kurier","listonosz","sprzedawca","elektryk","hydraulik","budowlaniec","rolnik","kierowca","stewardesa","grafik","dziennikarz","sędzia","ratownik","detektyw"],
  "Przedmioty":["laptop","komputer","klawiatura","myszka","monitor","telewizor","pilot","głośnik","ładowarka","powerbank","portfel","okulary","kubek","talerz","łyżka","nóż","patelnia","garnek","mikrofalówka","ręcznik","kołdra","lampka","biurko","rower","hulajnoga","piłka","aparat","konsola"],
  "Jedzenie":["hot dog","lasagne","schabowy","gofry","pączek","drożdżówka","chipsy","szarlotka","taco","burrito","zapiekanka","kanapka","jajecznica","parówki","kurczak","ryż","ziemniaki","pomidor","ogórek","banan","jabłko","arbuz","truskawka","Nutella"],
  "Marki":["Xiaomi","Huawei","Google","Microsoft","Sony","Nintendo","Puma","New Balance","Vans","Converse","H&M","Pepsi","Sprite","Red Bull","Monster","KFC","Burger King","Starbucks","Biedronka","Lidl","Allegro","Amazon","Discord","Roblox"],
  "Kraje":["Portugalia","Wielka Brytania","Irlandia","Szwecja","Finlandia","Dania","Holandia","Belgia","Szwajcaria","Austria","Czechy","Słowacja","Ukraina","Turcja","Maroko","Chiny","Tajlandia","Argentyna","Korea Południowa","Chorwacja","Rumunia","Węgry","Litwa"],
  "Miasta":["Poznań","Łódź","Katowice","Szczecin","Lublin","Rzeszów","Toruń","Madryt","Lizbona","Wiedeń","Amsterdam","Bruksela","Ateny","Stambuł","Los Angeles","Miami","Chicago","Las Vegas","Toronto","Seul","Pekin","Sydney","Kair","Rio de Janeiro","Monako"],
  "Memy i internet":["Skibidi Toilet","Ohio","Rizz","Trollface","Doge","Cheems","Grumpy Cat","Pepe","Wojak","Among Us","Sus","Press F","LOL","XD","Cringe","Clickbait","Twitch","Reddit","Wikipedia","Google Maps","CapCut","ChatGPT","Duolingo","Keyboard Cat"],
  "Minecraft":["Pająk","Osadnik","Wilk","Kot","Smok Endu","Slime","Diament","Netherit","Redstone","TNT","Kilof","Miecz","Łuk","Tarcza","Totem nieśmiertelności","Stół rzemieślniczy","Piec","Skrzynia","Portal do Netheru","Nether","End","Twierdza","Wioska","Leśna posiadłość","Ocean Monument"],
  "Roblox":["Brookhaven","Adopt Me!","Bee Swarm Simulator","BedWars","Natural Disaster Survival","Build A Boat For Treasure","The Mimic","Work at a Pizza Place","Blade Ball","Evade","Flee the Facility","Restaurant Tycoon 2","Livetopia","MeepCity","Theme Park Tycoon 2","3008"],
  "Twórcy internetowi":["Markiplier","Logan Paul","Jake Paul","Sidemen","PrestonPlayz","Unspeakable","LazarBeam","Pokimane","xQc","Ninja","Kacper Blonsky","Mini Majk","Tromba","Stuu","DisStream","Madzia","Naruciak","Książulo","Mietczyński","Karol Paciorek","IsAmU","Nitrozyniak","Boxdel"],
  "Gry popularne":["Call of Duty","Overwatch 2","Apex Legends","Pokémon GO","Super Mario Bros.","The Legend of Zelda","The Witcher 3","Cyberpunk 2077","Red Dead Redemption 2","Geometry Dash","Plants vs. Zombies","Need for Speed","Forza Horizon","Genshin Impact","Five Nights at Freddy's","Undertale","Cuphead","Fallout","Skyrim","Assassin's Creed","God of War","The Last of Us","Mortal Kombat","Hogwarts Legacy"],
  "Pokémon":["Pikachu","Bulbasaur","Charmander","Squirtle","Eevee","Snorlax","Meowth","Psyduck","Jigglypuff","Gengar","Mewtwo","Mew","Charizard","Blastoise","Venusaur","Lucario","Greninja","Ditto","Magikarp","Gyarados","Lapras","Dragonite","Onix","Machamp","Slowpoke","Togepi","Piplup","Mudkip","Torchic","Treecko","Cyndaquil","Chikorita","Totodile","Rowlet","Litten","Popplio","Sprigatito","Fuecoco","Quaxly","Ash Ketchum","Team Rocket","Poké Ball"],
  "Superbohaterowie":["Spider-Man","Batman","Superman","Wonder Woman","Iron Man","Hulk","Thor","Kapitan Ameryka","Black Widow","Hawkeye","Deadpool","Wolverine","Black Panther","Doctor Strange","Ant-Man","Aquaman","Flash","Green Lantern","Joker","Harley Quinn","Venom","Thanos","Loki","Groot","Star-Lord","Gamora","Daredevil","Catwoman","Robin","Shazam","Supergirl","Miles Morales","Scarlet Witch","Vision","Homelander"],
  "Filmy i seriale":["Harry Potter","Shrek","Kraina Lodu","Toy Story","Auta","Minionki","Madagaskar","Avatar","Titanic","Barbie","Wednesday","Stranger Things","Dom z papieru","Squid Game","Gra o tron","The Walking Dead","Przyjaciele","The Office","Breaking Bad","Rodzina Addamsów","Gwiezdne wojny","Władca Pierścieni","Hobbit","Avengers","Spider-Man","Batman","Joker","Kevin sam w domu","Jurassic Park","Piraci z Karaibów","Matrix","Rocky","Kung Fu Panda","Epoka lodowcowa","Smerfy","SpongeBob","Simpsonowie","Psi Patrol","Czarnobyl"],
  "Sport":["Robert Lewandowski","Cristiano Ronaldo","Lionel Messi","Kylian Mbappé","Iga Świątek","Hubert Hurkacz","Michael Jordan","LeBron James","Usain Bolt","Mariusz Pudzianowski","Kamil Stoch","Adam Małysz","Marcin Gortat","Wojciech Szczęsny","Erling Haaland","Neymar","Karim Benzema","Luka Modrić","Novak Djoković","Rafael Nadal","Roger Federer","Michael Phelps","Mike Tyson","Muhammad Ali","Robert Kubica","Max Verstappen","Lewis Hamilton","Ronaldinho","Diego Maradona","Pelé"],
  "Anime i manga":["Naruto","Sasuke","Sakura","Kakashi","Goku","Vegeta","Luffy","Zoro","Nami","Sailor Moon","Totoro","Gojo","Yuji Itadori","Tanjiro","Nezuko","Light Yagami","Ryuk","Saitama","Eren","Mikasa","Levi","Deku","All Might","Anya Forger","Dragon Ball"],
};

Object.entries(identityExtras).forEach(([category, items]) => {
  identityCategories[category] = [...new Set([...(identityCategories[category] || []), ...items])];
});

export const identityCategoryNames=Object.keys(identityCategories);
