// Dodaj parę podobnych pytań jako: { category:"Kategoria", main:"...", impostor:"...", spicy:true }.
export const otherQuestionPairs=[
{category:"Życie codzienne",main:"Ile masz par butów?",impostor:"Ile par butów regularnie nosisz?"},
{category:"Życie codzienne",main:"Ile razy w tygodniu robisz zakupy?",impostor:"Ile razy w tygodniu wychodzisz do sklepu?"},
{category:"Życie codzienne",main:"Ile godzin zwykle śpisz?",impostor:"Ile godzin chciałbyś spać każdej nocy?"},
{category:"Życie codzienne",main:"Ile kubków wody pijesz dziennie?",impostor:"Ile napojów wypijasz dziennie?"},
{category:"Życie codzienne",main:"Ile razy dziennie sprawdzasz godzinę?",impostor:"Ile razy dziennie sprawdzasz powiadomienia?"},
{category:"Życie codzienne",main:"Ile minut zajmuje ci poranne ogarnięcie się?",impostor:"Ile minut zajmuje ci wyjście z domu?"},
{category:"Szkoła",main:"Ile sprawdzianów miałeś w ostatnim miesiącu?",impostor:"Ile kartkówek miałeś w ostatnim miesiącu?"},
{category:"Szkoła",main:"Ile godzin tygodniowo poświęcasz na naukę?",impostor:"Ile godzin tygodniowo spędzasz nad pracami domowymi?"},
{category:"Szkoła",main:"Ile przedmiotów szkolnych lubiłeś?",impostor:"Z ilu przedmiotów miałeś dobre oceny?"},
{category:"Szkoła",main:"Ile razy spóźniłeś się do szkoły?",impostor:"Ile razy zaspałeś do szkoły?"},
{category:"Szkoła",main:"Ile stron miała najdłuższa lektura, którą przeczytałeś?",impostor:"Ile stron książki przeczytałeś najwięcej w tydzień?"},
{category:"Szkoła",main:"Ile osób było w twojej klasie?",impostor:"Ile osób ze swojej klasy dobrze znałeś?"},
{category:"Internet",main:"Ile godzin dziennie siedzisz na telefonie?",impostor:"Ile godzin dziennie siedzisz przy ekranie?"},
{category:"Internet",main:"Ile kont obserwujesz na Instagramie?",impostor:"Ile osób obserwuje cię na Instagramie?"},
{category:"Internet",main:"Ile filmów oglądasz tygodniowo na YouTube?",impostor:"Ile krótkich filmów oglądasz dziennie?"},
{category:"Internet",main:"Ile serwerów Discord masz na liście?",impostor:"Na ilu serwerach Discord faktycznie piszesz?"},
{category:"Internet",main:"Ile aplikacji społecznościowych używasz?",impostor:"Ile aplikacji otwierasz codziennie?"},
{category:"Internet",main:"Ile razy dziennie odpisujesz na wiadomości?",impostor:"Ile wiadomości dziennie dostajesz?"},
{category:"Jedzenie",main:"Ile razy jadłeś fast food w tym miesiącu?",impostor:"Ile razy zamawiałeś jedzenie w tym miesiącu?"},
{category:"Jedzenie",main:"Ile kawałków pizzy zjesz na raz?",impostor:"Ile kromek chleba zjadasz na śniadanie?"},
{category:"Jedzenie",main:"Ile razy tygodniowo jesz słodycze?",impostor:"Ile razy tygodniowo pijesz słodkie napoje?"},
{category:"Jedzenie",main:"Ile pierogów dasz radę zjeść?",impostor:"Ile naleśników dasz radę zjeść?"},
{category:"Jedzenie",main:"Ile razy jadłeś sushi?",impostor:"Ile razy jadłeś ramen?"},
{category:"Jedzenie",main:"Ile kubków kawy pijesz dziennie?",impostor:"Ile kubków herbaty pijesz dziennie?"},
{category:"Znajomi",main:"Ile osób zaprosiłbyś na urodziny?",impostor:"Ilu znajomych znasz naprawdę dobrze?"},
{category:"Znajomi",main:"Ile razy w miesiącu spotykasz się ze znajomymi?",impostor:"Ile razy w miesiącu wychodzisz z domu dla rozrywki?"},
{category:"Znajomi",main:"Ile osób masz w ulubionym czacie grupowym?",impostor:"Z iloma osobami piszesz prawie codziennie?"},
{category:"Znajomi",main:"Ile osób poznałeś przez internet?",impostor:"Ile internetowych znajomości przeniosłeś do realnego życia?"},
{category:"Znajomi",main:"Ile prezentów kupujesz przed świętami?",impostor:"Ile prezentów dostałeś na ostatnie urodziny?"},
{category:"Znajomi",main:"Ile razy byłeś na domówce?",impostor:"Ile razy organizowałeś spotkanie u siebie?"},
{category:"Gaming",main:"Ile godzin tygodniowo grasz?",impostor:"Ile godzin trwała twoja najdłuższa sesja grania?"},
{category:"Gaming",main:"Ile gier masz na Steamie?",impostor:"Ile gier przeszedłeś do końca?"},
{category:"Gaming",main:"Ile razy wygrałeś battle royale?",impostor:"Ile razy byłeś w top 3 battle royale?"},
{category:"Gaming",main:"Ile gier multiplayer regularnie odpalasz?",impostor:"Ile gier kooperacyjnych przeszedłeś ze znajomymi?"},
{category:"Gaming",main:"Ile kontrolerów do grania masz w domu?",impostor:"Na ilu platformach do grania grasz?"},
{category:"Gaming",main:"Ile razy kupiłeś grę w dniu premiery?",impostor:"Ile razy zamówiłeś grę w przedsprzedaży?"},
{category:"Muzyka",main:"Ile godzin dziennie słuchasz muzyki?",impostor:"Ile piosenek słuchasz przeciętnie dziennie?"},
{category:"Muzyka",main:"Na ilu koncertach byłeś?",impostor:"Na ilu festiwalach muzycznych byłeś?"},
{category:"Muzyka",main:"Ile playlist masz zapisanych?",impostor:"Ile playlist regularnie odpalasz?"},
{category:"Muzyka",main:"Ilu artystów obserwujesz?",impostor:"Ilu artystów potrafisz wymienić bez zastanowienia?"},
{category:"Muzyka",main:"Ile piosenek znasz na pamięć?",impostor:"Ile piosenek umiesz zaśpiewać od początku do końca?"},
{category:"Muzyka",main:"Ile instrumentów próbowałeś grać?",impostor:"Na ilu instrumentach umiesz zagrać prostą melodię?"},
{category:"Filmy i seriale",main:"Ile seriali oglądałeś w ostatnim miesiącu?",impostor:"Ile filmów oglądałeś w ostatnim miesiącu?"},
{category:"Filmy i seriale",main:"Ile odcinków serialu obejrzysz jednego dnia?",impostor:"Ile godzin maratonu serialowego wytrzymasz?"},
{category:"Filmy i seriale",main:"Ile razy byłeś w kinie w tym roku?",impostor:"Ile nowych filmów obejrzałeś w tym roku?"},
{category:"Filmy i seriale",main:"Ile subskrypcji streamingowych masz?",impostor:"Z ilu platform streamingowych korzystasz?"},
{category:"Filmy i seriale",main:"Ile razy oglądałeś swój ulubiony film?",impostor:"Ile razy wróciłeś do ulubionego serialu?"},
{category:"Filmy i seriale",main:"Ile filmów z Harrym Potterem widziałeś?",impostor:"Ile filmów Marvela widziałeś?"},
{category:"Podróże",main:"Ile krajów zwiedziłeś?",impostor:"W ilu krajach byłeś chociaż przejazdem?"},
{category:"Podróże",main:"Ile miast za granicą odwiedziłeś?",impostor:"Ile europejskich stolic odwiedziłeś?"},
{category:"Podróże",main:"Ile godzin trwała twoja najdłuższa podróż?",impostor:"Ile godzin najdłużej spędziłeś w samochodzie?"},
{category:"Podróże",main:"Ile razy leciałeś samolotem?",impostor:"Ile razy jechałeś pociągiem dalekobieżnym?"},
{category:"Podróże",main:"Ile dni trwały twoje najdłuższe wakacje?",impostor:"Ile dni spędziłeś najdłużej poza domem?"},
{category:"Podróże",main:"Ile razy byłeś nad morzem?",impostor:"Ile razy byłeś w górach?"},
{category:"Dziwne pytania",main:"Ile razy rozmawiałeś sam ze sobą dzisiaj?",impostor:"Ile razy nuciłeś coś pod nosem dzisiaj?"},
{category:"Dziwne pytania",main:"Ile poduszek masz na łóżku?",impostor:"Ile koców masz w swoim pokoju?"},
{category:"Dziwne pytania",main:"Ile razy sprawdzasz lodówkę bez powodu?",impostor:"Ile razy dziennie chodzisz do kuchni?"},
{category:"Dziwne pytania",main:"Ile zdjęć masz obecnie w telefonie?",impostor:"Ile screenshotów masz obecnie w telefonie?"},
{category:"Dziwne pytania",main:"Ile razy zmieniałeś fryzurę?",impostor:"Ile razy farbowałeś włosy?"},
{category:"Dziwne pytania",main:"Ile minut wytrzymasz bez telefonu?",impostor:"Ile godzin wytrzymasz bez internetu?"},
{category:"Relacje",main:"Ile razy byłeś na randce w ostatnim roku?",impostor:"Ile nowych osób poznałeś przez znajomych w ostatnim roku?"},
{category:"Relacje",main:"Ile razy dostałeś numer telefonu od nowej osoby?",impostor:"Ile razy poprosiłeś kogoś o kontakt?"},
{category:"Relacje",main:"Ile osób zaprosiłbyś na spokojne spotkanie?",impostor:"Z iloma osobami byłeś na kawie lub spacerze?"},
{category:"Relacje",main:"Ile razy napisałeś pierwszy po udanym spotkaniu?",impostor:"Ile razy ktoś napisał pierwszy do ciebie?"},
{category:"Relacje",main:"Ile razy miałeś niewinnego crusha na znajomego?",impostor:"Ile razy ktoś ze znajomych był dla ciebie wyjątkowo miły?"},
{category:"Relacje",main:"Ile rozmów z nowymi osobami zacząłeś w internecie?",impostor:"Ile nowych znajomości utrzymałeś dłużej niż tydzień?"}
,{category:"Minecraft i Roblox",main:"Ile godzin grałeś najdłużej w Minecrafta?",impostor:"Ile godzin grałeś najdłużej w Roblox?"}
,{category:"Minecraft i Roblox",main:"Ile diamentów znalazłeś kiedyś w jednym świecie?",impostor:"Ile razy zginąłeś kiedyś w jednym świecie?"}
,{category:"Minecraft i Roblox",main:"Ile razy pokonałeś smoka Endu?",impostor:"Ile razy dotarłeś do Endu?"}
,{category:"Minecraft i Roblox",main:"Ile gier w Roblox odpaliłeś w ostatnim miesiącu?",impostor:"Ile razy odpaliłeś Roblox w ostatnim miesiącu?"}
,{category:"Minecraft i Roblox",main:"Ile Robuxów wydałeś w życiu?",impostor:"Ile pieniędzy wydałeś na gry w życiu?"}
,{category:"YouTube",main:"Ilu youtuberów regularnie oglądasz?",impostor:"Ile kanałów subskrybujesz?"}
,{category:"YouTube",main:"Ile godzin YouTube oglądasz tygodniowo?",impostor:"Ile godzin TikToka oglądasz tygodniowo?"}
,{category:"YouTube",main:"Ile razy oglądałeś stream na żywo?",impostor:"Ile razy pisałeś coś na czacie streama?"}
,{category:"YouTube",main:"Ile filmów wysłałeś znajomym w tym tygodniu?",impostor:"Ile memów wysłałeś znajomym w tym tygodniu?"}
,{category:"YouTube",main:"Ile kanałów na YouTube kiedyś założyłeś?",impostor:"Ile kont w social media kiedyś założyłeś?"}
];
otherQuestionPairs.push(
  {category:"Życie codzienne",main:"Ile minut zajmuje ci wyjście z domu?",impostor:"Ile minut zajmuje ci ogarnięcie się rano?"},
  {category:"Życie codzienne",main:"Ile razy dziennie sprawdzasz telefon?",impostor:"Ile razy dziennie odblokowujesz telefon bez powodu?"},
  {category:"Życie codzienne",main:"Ile budzików ustawiasz rano?",impostor:"Ile razy zwykle odkładasz budzik?"},
  {category:"Życie codzienne",main:"Ile godzin śpisz w weekend?",impostor:"Ile godzin śpisz w dzień szkolny lub roboczy?"},
  {category:"Szkoła",main:"Ile razy spóźniłeś się do szkoły?",impostor:"Ile razy zapomniałeś pracy domowej?"},
  {category:"Szkoła",main:"Ile przedmiotów lubiłeś w szkole?",impostor:"Ilu nauczycieli dobrze wspominasz?"},
  {category:"Szkoła",main:"Ile minut przed sprawdzianem zaczynasz się uczyć?",impostor:"Ile dni przed sprawdzianem zaczynasz się uczyć?"},
  {category:"Internet",main:"Ile godzin tygodniowo spędzasz na TikToku?",impostor:"Ile godzin tygodniowo spędzasz na YouTube?"},
  {category:"Internet",main:"Ile grupowych czatów masz wyciszonych?",impostor:"Na ilu grupowych czatach jesteś aktywny?"},
  {category:"Internet",main:"Ile memów zapisujesz miesięcznie?",impostor:"Ile memów wysyłasz znajomym miesięcznie?"},
  {category:"Jedzenie",main:"Ile kawałków pizzy zjesz bez problemu?",impostor:"Ile burgerów zjesz bez problemu?"},
  {category:"Jedzenie",main:"Ile razy w miesiącu zamawiasz jedzenie?",impostor:"Ile razy w miesiącu jesz fast food?"},
  {category:"Jedzenie",main:"Ile naleśników zjesz na raz?",impostor:"Ile pierogów zjesz na raz?"},
  {category:"Znajomi",main:"Ile osób zaprosiłbyś na domówkę?",impostor:"Ile osób zabrałbyś na wspólny wyjazd?"},
  {category:"Znajomi",main:"Ile godzin trwał twój najdłuższy call ze znajomymi?",impostor:"Ile godzin trwało twoje najdłuższe spotkanie ze znajomymi?"},
  {category:"Znajomi",main:"Ile razy wyszedłeś gdzieś spontanicznie?",impostor:"Ile razy odwołałeś plan w ostatniej chwili?"},
  {category:"Gaming",main:"Ile godzin trwała twoja najdłuższa sesja grania?",impostor:"Ile godzin tygodniowo grasz w gry?"},
  {category:"Gaming",main:"Ile gier masz zainstalowanych?",impostor:"Ile gier naprawdę regularnie odpalasz?"},
  {category:"Gaming",main:"Ile razy rage quitowałeś w tym miesiącu?",impostor:"Ile razy przegrałeś przez słaby internet?"},
  {category:"Gaming",main:"Ile skórek kupiłeś w grach?",impostor:"Ile pieniędzy wydałeś na gry?"},
  {category:"Muzyka",main:"Ile godzin muzyki słuchasz tygodniowo?",impostor:"Ile playlist masz zapisanych?"},
  {category:"Muzyka",main:"Ile koncertów widziałeś na żywo?",impostor:"Ile festiwali odwiedziłeś?"},
  {category:"Filmy i seriale",main:"Ile odcinków serialu obejrzysz jednego dnia?",impostor:"Ile filmów obejrzysz w jeden weekend?"},
  {category:"Filmy i seriale",main:"Ile razy oglądałeś swój ulubiony film?",impostor:"Ile razy wracałeś do ulubionego serialu?"},
  {category:"Podróże",main:"Ile krajów odwiedziłeś?",impostor:"Ile miast odwiedziłeś poza swoim regionem?"},
  {category:"Podróże",main:"Ile godzin wytrzymasz w samochodzie bez marudzenia?",impostor:"Ile godzin wytrzymasz w pociągu bez nudy?"},
  {category:"Dziwne pytania",main:"Ile dni przeżyłbyś bez internetu?",impostor:"Ile dni przeżyłbyś bez telefonu?"},
  {category:"Dziwne pytania",main:"Ile razy dziennie mówisz XD?",impostor:"Ile razy dziennie wysyłasz emoji?"},
  {category:"Minecraft i Roblox",main:"Ile razy wykopałeś diamenty w Minecraft?",impostor:"Ile razy wpadłeś do lawy w Minecraft?"},
  {category:"Minecraft i Roblox",main:"Ile gier Roblox masz w ulubionych?",impostor:"Ile gier Roblox odpaliłeś choć raz?"},
  {category:"Minecraft i Roblox",main:"Ile minut przeżyjesz pierwszej nocy w Minecraft?",impostor:"Ile minut zajmie ci znalezienie pierwszych diamentów?"},
  {category:"YouTube",main:"Ile kanałów na YouTube subskrybujesz?",impostor:"Ilu twórców oglądasz regularnie?"},
  {category:"YouTube",main:"Ile shortów obejrzysz bez przerwy?",impostor:"Ile filmów wyślesz znajomym tygodniowo?"},
  {category:"Pokémon i nostalgia",main:"Ile Pokémonów potrafisz nazwać?",impostor:"Ile Pokémonów rozpoznasz na obrazku?"},
  {category:"Pokémon i nostalgia",main:"Ile odcinków bajek oglądałeś w weekend jako dziecko?",impostor:"Ile godzin grałeś dziennie jako dziecko?"},
  {category:"Pokémon i nostalgia",main:"Ile kart Pokémon miałeś lub chciałeś mieć?",impostor:"Ile figurek lub kolekcjonerskich rzeczy miałeś jako dziecko?"}
);

otherQuestionPairs.push(
  {category:"Ĺ»ycie codzienne",main:"Ile razy w tygodniu sprzÄ…tasz pokĂłj?",impostor:"Ile razy w tygodniu ogarniasz swoje rzeczy?"},
  {category:"Ĺ»ycie codzienne",main:"Ile minut dziennie spÄ™dzasz w Ĺ‚azience?",impostor:"Ile minut dziennie zajmuje ci ogarniÄ™cie wyglÄ…du?"},
  {category:"Ĺ»ycie codzienne",main:"Ile rzeczy nosisz zwykle w kieszeniach?",impostor:"Ile rzeczy nosisz zwykle w plecaku albo torbie?"},
  {category:"Ĺ»ycie codzienne",main:"Ile budzikĂłw ustawiasz rano?",impostor:"Ile razy zwykle odkĹ‚adasz budzik?"},
  {category:"SzkoĹ‚a",main:"Ile razy zgubiĹ‚eĹ› zeszyt albo kartkÄ™?",impostor:"Ile razy zapomniaĹ‚eĹ› zabraÄ‡ czegoĹ› do szkoĹ‚y?"},
  {category:"SzkoĹ‚a",main:"Ile minut najdĹ‚uĹĽej odpowiadaĹ‚eĹ› przy tablicy?",impostor:"Ile minut najdĹ‚uĹĽej pisaĹ‚eĹ› kartkĂłwkÄ™?"},
  {category:"SzkoĹ‚a",main:"Ile razy udawaĹ‚eĹ›, ĹĽe rozumiesz temat?",impostor:"Ile razy zgadywaĹ‚eĹ› odpowiedĹş na lekcji?"},
  {category:"Internet",main:"Ile kart masz zwykle otwartych w przeglÄ…darce?",impostor:"Ile aplikacji masz zwykle otwartych w tle?"},
  {category:"Internet",main:"Ile razy dziennie wysyĹ‚asz reakcjÄ™ zamiast odpowiedzi?",impostor:"Ile razy dziennie odpowiadasz jednym sĹ‚owem?"},
  {category:"Internet",main:"Ile godzin wytrzymasz bez sprawdzenia powiadomieĹ„?",impostor:"Ile godzin wytrzymasz bez wejĹ›cia na social media?"},
  {category:"Jedzenie",main:"Ile razy w tygodniu jesz coĹ› ostrego?",impostor:"Ile razy w tygodniu jesz coĹ› sĹ‚odkiego?"},
  {category:"Jedzenie",main:"Ile lodĂłw zjesz w wakacyjny dzieĹ„?",impostor:"Ile zimnych napojĂłw wypijesz w upalny dzieĹ„?"},
  {category:"Jedzenie",main:"Ile skĹ‚adnikĂłw powinien mieÄ‡ idealny kebab?",impostor:"Ile dodatkĂłw powinien mieÄ‡ idealny burger?"},
  {category:"Znajomi",main:"Ile osĂłb zaprosiĹ‚byĹ› do wspĂłlnej gry?",impostor:"Ile osĂłb zaprosiĹ‚byĹ› na wspĂłlny film?"},
  {category:"Znajomi",main:"Ile minut spĂłĹşnienia znajomemu wybaczasz?",impostor:"Ile minut czekasz, zanim piszesz gdzie jest?"},
  {category:"Znajomi",main:"Ile osĂłb w ekipie zwykle podejmuje decyzje?",impostor:"Ile osĂłb w ekipie zwykle tylko siÄ™ zgadza?"},
  {category:"Gaming",main:"Ile razy zmieniaĹ‚eĹ› nick w grach?",impostor:"Ile razy zmieniaĹ‚eĹ› skina albo avatar w grze?"},
  {category:"Gaming",main:"Ile misji pobocznych robisz zanim ruszysz fabuĹ‚Ä™?",impostor:"Ile godzin potrafisz zbieraÄ‡ itemy bez celu?"},
  {category:"Gaming",main:"Ile gier masz zaczÄ™tych i nieskoĹ„czonych?",impostor:"Ile gier kupiĹ‚eĹ› i prawie nie odpaliĹ‚eĹ›?"},
  {category:"Muzyka",main:"Ile razy zapÄ™tliĹ‚eĹ› jednÄ… piosenkÄ™ pod rzÄ…d?",impostor:"Ile razy wrĂłciĹ‚eĹ› do starej ulubionej piosenki?"},
  {category:"Muzyka",main:"Ile piosenek masz w gĹ‚Ăłwnej playliĹ›cie?",impostor:"Ile piosenek zwykle pomijasz, zanim trafisz dobrÄ…?"},
  {category:"Muzyka",main:"Ile gatunkĂłw muzyki sĹ‚uchasz regularnie?",impostor:"Ile gatunkĂłw muzyki lubisz tylko czasami?"},
  {category:"Filmy i seriale",main:"Ile razy zasnÄ…Ĺ‚eĹ› podczas filmu?",impostor:"Ile razy przewijaĹ‚eĹ› nudny fragment filmu?"},
  {category:"Filmy i seriale",main:"Ile seriali masz na liĹ›cie do obejrzenia?",impostor:"Ile filmĂłw masz zapisanych na pĂłĹşniej?"},
  {category:"Filmy i seriale",main:"Ile sezonĂłw jednego serialu obejrzysz pod rzÄ…d?",impostor:"Ile filmĂłw jednej serii obejrzysz pod rzÄ…d?"},
  {category:"PodrĂłĹĽe",main:"Ile rzeczy pakujesz na krĂłtki wyjazd?",impostor:"Ile rzeczy zabierasz tylko na wszelki wypadek?"},
  {category:"PodrĂłĹĽe",main:"Ile zdjÄ™Ä‡ robisz na wyjeĹşdzie?",impostor:"Ile filmikĂłw nagrywasz na wyjeĹşdzie?"},
  {category:"PodrĂłĹĽe",main:"Ile minut przed odjazdem jesteĹ› na miejscu?",impostor:"Ile minut przed spotkaniem wychodzisz z domu?"},
  {category:"Dziwne pytania",main:"Ile razy dziennie myĹ›lisz o totalnej gĹ‚upocie?",impostor:"Ile razy dziennie Ĺ›miejesz siÄ™ z niczego?"},
  {category:"Dziwne pytania",main:"Ile rzeczy potrafisz zgubiÄ‡ w swoim pokoju?",impostor:"Ile rzeczy znalazĹ‚eĹ› po dĹ‚ugim czasie w dziwnym miejscu?"},
  {category:"Dziwne pytania",main:"Ile minut patrzysz w lodĂłwkÄ™ zanim coĹ› wybierzesz?",impostor:"Ile minut wybierasz co obejrzeÄ‡ zanim nic nie wĹ‚Ä…czysz?"},
  {category:"Minecraft i Roblox",main:"Ile domĂłw zbudowaĹ‚eĹ› w Minecraft?",impostor:"Ile baz zaczÄ…Ĺ‚eĹ› budowaÄ‡ i nie skoĹ„czyĹ‚eĹ›?"},
  {category:"Minecraft i Roblox",main:"Ile mobĂłw zabiĹ‚eĹ› w jednÄ… noc Minecraft?",impostor:"Ile razy uciekaĹ‚eĹ› przed mobami w Minecraft?"},
  {category:"Minecraft i Roblox",main:"Ile razy graĹ‚eĹ› na serwerze ze znajomymi?",impostor:"Ile razy graĹ‚eĹ› samemu na survivalu?"},
  {category:"YouTube",main:"Ile razy kliknÄ…Ĺ‚eĹ› film przez miniaturkÄ™?",impostor:"Ile razy kliknÄ…Ĺ‚eĹ› film przez tytuĹ‚?"},
  {category:"YouTube",main:"Ile kanaĹ‚Ăłw oglÄ…daĹ‚eĹ› kiedyĹ› codziennie?",impostor:"Ile kanaĹ‚Ăłw juĹĽ prawie wcale nie oglÄ…dasz?"},
  {category:"YouTube",main:"Ile razy zostawiĹ‚eĹ› film wĹ‚Ä…czony w tle?",impostor:"Ile razy zasnÄ…Ĺ‚eĹ› przy filmie albo streamie?"},
  {category:"Relacje",main:"Ile razy napisaĹ‚eĹ› do kogoĹ› po dĹ‚ugiej przerwie?",impostor:"Ile razy ktoĹ› odezwaĹ‚ siÄ™ do ciebie po dĹ‚ugiej przerwie?"},
  {category:"Relacje",main:"Ile razy stresowaĹ‚eĹ› siÄ™ przed spotkaniem?",impostor:"Ile razy stresowaĹ‚eĹ› siÄ™ przed napisaniem wiadomoĹ›ci?"},
  {category:"Relacje",main:"Ile razy pomyliĹ‚eĹ› przyjaĹşĹ„ z flirtem?",impostor:"Ile razy ktoĹ› byĹ‚ dla ciebie podejrzanie miĹ‚y?"},
  {category:"PokĂ©mon i nostalgia",main:"Ile starych gier z dzieciĹ„stwa pamiÄ™tasz?",impostor:"Ile starych bajek z dzieciĹ„stwa pamiÄ™tasz?"},
  {category:"PokĂ©mon i nostalgia",main:"Ile razy wracaĹ‚eĹ› do gry z dzieciĹ„stwa?",impostor:"Ile razy wracaĹ‚eĹ› do bajki z dzieciĹ„stwa?"}
);

export const otherQuestionCategories=[...new Set(otherQuestionPairs.map(item=>item.category))];
