const list = text => text.split("|").map(item => item.trim()).filter(Boolean);
const normalizeKey = value => String(value || "").toLowerCase().trim().normalize("NFD")
  .replace(/[\u0300-\u036f]/g,"").replace(/ł/g,"l")
  .replace(/[^a-z0-9\s-]/gi,"").replace(/\s+/g," ");
const unique = items => [...new Map(items.map(item => [normalizeKey(item),item])).values()];

export const aliases = {
  games:list("csgo|cs:go|cs go|counter strike|counter-strike|counter strike global offensive|cs2|cs 2|counter strike 2|lol|league of legends|gta|gta v|gta 5|grand theft auto v|grand theft auto 5|fifa|ea fc|fc 24|fc 25|cod|call of duty|wow|world of warcraft|rdr2|red dead redemption 2|pubg|playerunknown's battlegrounds|rocket league|rl|valorant|valo|minecraft|mc|fortnite|fn|the sims|sims|pokemon go|pokémon go"),
  internet:list("tiktok|tik tok|youtube|yt|instagram|insta|facebook|fb|messenger|msg|whatsapp|whats app|twitter|x|discord|dc|reddit|twitch|ttv|google meet|meet|chatgpt|chat gpt|stack overflow|stackoverflow"),
  brands:list("mcdonalds|mcdonald's|mc donalds|coca cola|coca-cola|coke|h&m|hm|pull&bear|pull and bear|new balance|newbalance|burger king|bk|playstation|ps|xbox|mercedes|mercedes-benz|volkswagen|vw|louis vuitton|lv|calvin klein|ck|dolce & gabbana|d&g"),
  creators:list("mrbeast|mr beast|ishowspeed|i show speed|speed|dantdm|dan tdm|georgenotfound|george not found|jacksepticeye|jack septic eye|sssniperwolf|ss sniper wolf|young multi|multi|poczciwy krzychu|krzychu|wojan|wojan games|wojan plus|palion|palion games|palion minecraft|friz|karol friz wiśniewski|rezi|rezi style|blowek|blow|wardęga|sylwester wardęga"),
};

const aliasGroups = [
  "pies|psa|pieseł|piesel",
  "kot|kota|kotek",
  "koń|kon|konia",
  "jabłko|jablko|jabłka|jablka",
  "pomarańcza|pomarancza|pomarańcze|pomarancze",
  "truskawka|truskawki",
  "ziemniak|ziemniaki|kartofel|kartofle",
  "pomidor|pomidory",
  "marchewka|marchew|marchewki",
  "piłka nożna|pilka nozna|futbol|football",
  "koszykówka|koszykowka|basket",
  "siatkówka|siatkowka",
  "warszawa|wawa",
  "kraków|krakow",
  "wrocław|wroclaw",
  "poznań|poznan",
  "łódź|lodz",
  "gdańsk|gdansk",
  "harry potter|hp",
  "władca pierścieni|wladca pierscieni|lotr",
  "gwiezdne wojny|star wars|sw",
  "telefon|smartfon|komórka|komorka",
  "komputer|pecet|pc",
  "słuchawki|sluchawki",
  "mcdonalds|mcdonald's|mc donalds",
  "coca cola|coca-cola|coke",
  "h&m|hm",
  "pull&bear|pull and bear",
  "new balance|newbalance",
  "burger king|bk",
  "playstation|ps",
  "mercedes|mercedes-benz",
  "volkswagen|vw",
  "louis vuitton|lv",
  "calvin klein|ck",
  "dolce & gabbana|d&g",
  "csgo|cs:go|cs go|counter strike global offensive",
  "cs2|cs 2|counter strike 2",
  "lol|league of legends",
  "gta v|gta 5|grand theft auto v|grand theft auto 5",
  "fifa|ea fc|fc 24|fc 25",
  "cod|call of duty",
  "wow|world of warcraft",
  "rdr2|red dead redemption 2",
  "pubg|playerunknown's battlegrounds",
  "rocket league|rl",
  "valorant|valo",
  "minecraft|mc",
  "fortnite|fn",
  "the sims|sims",
  "pokemon go|pokémon go",
  "tiktok|tik tok",
  "youtube|yt",
  "instagram|insta",
  "facebook|fb",
  "messenger|msg",
  "whatsapp|whats app",
  "twitter|x",
  "discord|dc",
  "reddit|reddita",
  "twitch|ttv",
  "google meet|meet",
  "chatgpt|chat gpt",
  "stack overflow|stackoverflow",
  "mrbeast|mr beast",
  "ishowspeed|i show speed|speed",
  "dantdm|dan tdm",
  "georgenotfound|george not found",
  "jacksepticeye|jack septic eye",
  "sssniperwolf|ss sniper wolf",
  "young multi|multi",
  "poczciwy krzychu|krzychu",
  "wojan|wojan games|wojan plus",
  "palion|palion games|palion minecraft",
  "friz|karol friz wiśniewski|karol wiśniewski",
  "rezi|rezi style",
  "blowek|blow",
  "wardęga|sylwester wardęga",
  "zombie|zombiak",
  "skeleton|szkielet",
  "spider|pająk",
  "cave spider|pająk jaskiniowy",
  "witch|wiedźma",
  "slime|szlam",
  "blaze|płomyk",
  "villager|wieśniak",
  "iron golem|żelazny golem",
  "snow golem|bałwan|śnieżny golem",
  "sheep|owca",
  "cow|krowa",
  "pig|świnia",
  "chicken|kurczak",
  "wolf|wilk",
  "cat|kot",
  "horse|koń",
  "donkey|osioł",
  "mule|muł",
  "llama|lama",
  "bee|pszczoła",
  "fox|lis",
  "frog|żaba",
  "tadpole|kijanka",
  "axolotl|aksolotl",
  "dolphin|delfin",
  "guardian|strażnik",
  "elder guardian|prastrażnik|starszy strażnik",
  "drowned|utopiec",
  "pillager|rabieżca",
  "evoker|przywoływacz",
  "ravager|dewastator|niszczyciel",
  "silverfish|rybik cukrowy",
  "magma cube|kostka magmy",
  "wither skeleton|mroczny szkielet",
  "zombified piglin|zombifikowany piglin",
  "camel|wielbłąd",
  "sniffer|wąchacz",
  "goat|koza",
  "polar bear|niedźwiedź polarny",
  "parrot|papuga",
  "rabbit|królik",
  "wandering trader|wędrowny handlarz",
  "trader llama|lama handlarza",
  "mooshroom|grzybowa krowa",
  "ender dragon|smok endu|enderdragon",
  "bat|nietoperz",
  "squid|kałamarnica",
  "glow squid|świecąca kałamarnica",
  "turtle|żółw",
  "salmon|łosoś",
  "cod fish|dorsz",
  "pufferfish|rozdymka",
  "tropical fish|ryba tropikalna",
  "husk|posuch",
  "stray|tułacz",
  "phantom|fantom",
  "armadillo|pancernik",
  "warden|nadzorca",
  "breeze|wicher",
  "bogged|bagniak",
  "allay|otuszek",
  "strider|magmołaz",
  "vex|dręczyciel",
  "vindicator|obrońca",
  "creaking|skrzypiący",
  "happy ghast|radosny ghast",
  "ghastling|ghastlątko",
  "game of thrones|gra o tron",
  "the witcher|wiedźmin",
  "money heist|la casa de papel|dom z papieru",
  "the office|biuro",
  "friends|przyjaciele",
  "house|dr house",
  "grey's anatomy|anatomia greya",
  "the handmaid's tale|opowieść podręcznej",
  "black mirror|czarne lustro",
  "lost|zagubieni",
  "succession|sukcesja",
  "how i met your mother|jak poznałem waszą matkę",
  "the big bang theory|big bang theory|teoria wielkiego podrywu",
  "house of the dragon|ród smoka",
  "the walking dead|żywe trupy",
  "star wars|gwiezdne wojny",
  "the lord of the rings|władca pierścieni",
  "pirates of the caribbean|piraci z karaibów",
  "the lion king|król lew",
  "cars|auta",
  "frozen|kraina lodu",
  "despicable me|minionki",
  "how to train your dragon|jak wytresować smoka",
  "finding nemo|gdzie jest nemo",
  "the incredibles|iniemamocni",
  "monsters inc|potwory i spółka",
  "inside out|w głowie się nie mieści",
  "tangled|zaplątani",
  "ratatouille|ratatuj",
  "up|odlot",
  "back to the future|powrót do przyszłości",
  "the godfather|ojciec chrzestny",
  "alien|obcy",
  "inception|incepcja",
  "gravity|grawitacja",
  "dune|diuna",
  "the hunger games|igrzyska śmierci",
  "fantastic beasts|fantastyczne zwierzęta",
  "the green mile|zielona mila",
  "the wolf of wall street|wilk z wall street",
  "spongebob|sponge bob|spongebob kanciastoporty",
  "the simpsons|simpsonowie",
  "adventure time|pora na przygodę",
  "gravity falls|wodogrzmoty małe",
  "avatar the last airbender|avatar legenda aanga|avatar ostatni władca wiatru",
  "moana|vaiana",
  "spider-man into the spider-verse|spider-man uniwersum",
  "zootopia|zwierzogród",
  "ice age|epoka lodowcowa",
  "hotel transylvania|hotel transylwania",
  "paw patrol|psi patrol",
  "captain america|kapitan ameryka",
  "guardians of the galaxy|strażnicy galaktyki",
  "black panther|czarna pantera",
  "the intouchables|nietykalni",
  "the conjuring|obecność",
  "fast and furious|szybcy i wściekli",
  "titanic|tytanic",
  "aladdin|aladyn",
  "beauty and the beast|piękna i bestia",
  "the little mermaid|mała syrenka",
  "turning red|czerwony",
  "soul|co w duszy gra",
  "brave|merida waleczna",
  "megamind|megamocny",
  "rings of power|pierścienie władzy",
  "desperate housewives|gotowe na wszystko",
];
const canonicalAliases = new Map(aliasGroups.flatMap(group => {
  const variants = list(group);
  const canonical = normalizeKey(variants[0]);
  return variants.map(variant => [normalizeKey(variant), canonical]);
}));
export const canonicalAnswerKey = value => canonicalAliases.get(normalizeKey(value)) || normalizeKey(value);

export const expandedPools = {
  countries:list("afganistan|albania|algieria|andora|angola|antigua i barbuda|arabia saudyjska|argentyna|armenia|australia|austria|azerbejdżan|bahamy|bahrajn|bangladesz|barbados|belgia|belize|benin|bhutan|białoruś|boliwia|bośnia i hercegowina|botswana|brazylia|brunei|bułgaria|burkina faso|burundi|chile|chiny|chorwacja|cypr|czad|czarnogóra|czechy|dania|demokratyczna republika konga|dominika|dominikana|dżibuti|egipt|ekwador|erytrea|estonia|eswatini|etiopia|fidżi|filipiny|finlandia|francja|gabon|gambia|ghana|grecja|grenada|gruzja|gujana|gwatemala|gwinea|gwinea bissau|gwinea równikowa|haiti|hiszpania|holandia|honduras|indie|indonezja|irak|iran|irlandia|islandia|izrael|jamajka|japonia|jemen|jordania|kambodża|kamerun|kanada|katar|kazachstan|kenia|kirgistan|kiribati|kolumbia|komory|kongo|korea południowa|korea północna|kostaryka|kuba|kuwejt|laos|lesotho|liban|liberia|libia|liechtenstein|litwa|luksemburg|łotwa|macedonia północna|madagaskar|malawi|malediwy|malezja|mali|malta|maroko|mauretania|mauritius|meksyk|mikronezja|mołdawia|monako|mongolia|mozambik|namibia|nauru|nepal|niemcy|niger|nigeria|nikaragua|norwegia|nowa zelandia|oman|pakistan|palau|palestyna|panama|papua nowa gwinea|paragwaj|peru|polska|portugalia|republika południowej afryki|republika środkowoafrykańska|republika zielonego przylądka|rosja|rumunia|rwanda|saint kitts i nevis|saint lucia|saint vincent i grenadyny|salwador|samoa|san marino|senegal|serbia|seszele|sierra leone|singapur|słowacja|słowenia|somalia|sri lanka|stany zjednoczone|sudan|sudan południowy|surinam|syria|szwajcaria|szwecja|tadżykistan|tajlandia|tanzania|timor wschodni|togo|tonga|trynidad i tobago|tunezja|turcja|turkmenistan|tuvalu|uganda|ukraina|urugwaj|uzbekistan|vanuatu|watykan|wenezuela|węgry|wielka brytania|wietnam|włochy|wybrzeże kości słoniowej|wyspy marshalla|wyspy salomona|wyspy świętego tomasza i książęca|zambia|zimbabwe|zjednoczone emiraty arabskie"),
  cities:list("warszawa|kraków|wrocław|łódź|poznań|gdańsk|szczecin|bydgoszcz|lublin|białystok|katowice|gdynia|częstochowa|radom|sosnowiec|toruń|kielce|rzeszów|gliwice|zabrze|olsztyn|bielsko-biała|bytom|zielona góra|rybnik|ruda śląska|opole|tychy|gorzów wielkopolski|elbląg|płock|wałbrzych|włocławek|tarnów|chorzów|koszalin|kalisz|legnica|grudziądz|słupsk|jaworzno|jastrzębie-zdrój|nowy sącz|jelenia góra|siedlce|konin|piła|inowrocław|lubin|ostrów wielkopolski|suwałki|głogów|gniezno|leszno|zamość|przemyśl|ełk|stalowa wola|tomaszów mazowiecki|chełm|mielec|bełchatów|świdnica|będzin|zgorzelec|zakopane|sopot|londyn|paryż|berlin|madryt|barcelona|rzym|mediolan|wenecja|neapol|lizbona|porto|amsterdam|rotterdam|bruksela|antwerpia|wiedeń|salzburg|praga|brno|bratysława|budapeszt|bukareszt|sofia|ateny|saloniki|belgrad|zagrzeb|sarajewo|podgorica|tirana|skopje|lublana|kijów|lwów|odessa|wilno|ryga|tallinn|helsinki|sztokholm|oslo|kopenhaga|reykjavik|dublin|edynburg|glasgow|manchester|liverpool|birmingham|monachium|hamburg|frankfurt|kolonia|drezno|zurich|genewa|bern|stambuł|ankara|moskwa|sankt petersburg|nowy jork|los angeles|chicago|houston|phoenix|filadelfia|san antonio|san diego|dallas|san jose|austin|jacksonville|san francisco|seattle|boston|miami|las vegas|denver|atlanta|detroit|portland|waszyngton|toronto|montreal|vancouver|ottawa|calgary|edmonton|meksyk|guadalajara|monterrey|hawana|kingston|panama|san jose|bogota|medellin|lima|cusco|quito|caracas|santiago|buenos aires|cordoba|montevideo|rio de janeiro|sao paulo|brasilia|salvador|recife|tokio|kioto|osaka|hiroszima|nagoya|seul|busan|pekin|szanghaj|hongkong|shenzhen|kanton|wuhan|tajpej|bangkok|chiang mai|hanoi|ho chi minh|singapur|kuala lumpur|dżakarta|bali|manila|delhi|mumbaj|bangalore|kalkuta|agra|karaczi|islamabad|katmandu|dubaj|abu zabi|doha|rijad|jeddah|jerozolima|tel awiw|amman|bejrut|teheran|bagdad|kair|aleksandria|marakesz|casablanca|tunis|algier|dakar|akra|lagos|abuja|nairobi|addis abeba|kapsztad|johannesburg|durban|pretoria|sydney|melbourne|brisbane|perth|adelaide|canberra|auckland|wellington|christchurch|honolulu|anchorage|orlando|new orleans|memphis|nashville|salt lake city|minneapolis|cleveland|pittsburgh|baltimore|charlotte|tampa|sacramento|oakland|san juan|quebec|halifax|winnipeg|victoria|belem|manaus|fortaleza|porto alegre|la paz|asuncion|georgetown|paramaribo|guatemala|tegucigalpa|managua|san salvador|quito|valparaiso|ushuaia|cancun|acapulco|tijuana|marrakesz|fez|rabat|tripoli|chartum|kampala|kigali|harare|lusaka|maputo|antananarywa|mogadiszu|windhuk|gaborone|maseru|port louis|luanda|kinshasa|brazzaville|yaounde|bissau|freetown|monrovia|bujumbura|lilongwe|blantyre"),
  games:list("agar.io|age of empires|alan wake|alien isolation|angry birds|anno 1800|ark survival evolved|assassin's creed|assetto corsa|baldur's gate 3|battlefield|bayonetta|beamng drive|bioshock|bloons td|borderlands|brotato|bully|celeste|cities skylines|civilization|club penguin|cookie clicker|crash bandicoot|crusader kings|cyberpunk 2077|darkest dungeon|days gone|dead cells|dead space|death stranding|deep rock galactic|detroit become human|dishonored|don't starve|doom|dota 2|dragon age|dying light|efootball|escape from tarkov|fallout|far cry|fear and hunger|final fantasy|firewatch|flappy bird|football manager|forza motorsport|fruit ninja|garry's mod|god of war|gran turismo|graveyard keeper|guitar hero|halo|hay day|hearthstone|hello neighbor|hitman|hogwarts legacy|horizon zero dawn|hotline miami|house flipper|human fall flat|it takes two|just cause|just dance|kerbal space program|kingdom come deliverance|left 4 dead|lego star wars|lethal company|limbo|little nightmares|mafia|mario party|mass effect|max payne|metro exodus|microsoft flight simulator|mobile legends|mortal kombat|multiversus|my summer car|need for speed|no man's sky|outlast|overcooked|oxygen not included|papers please|path of exile|payday|persona|plants vs zombies|plague inc|pokemon unite|portal 2|project zomboid|raft|rayman|rimworld|risk of rain|roblox|saints row|sea of thieves|sekiro|slay the spire|smite|snowrunner|sonic|spore|starcraft|starfield|star wars battlefront|state of decay|stumble guys|superhot|super mario bros|team fortress 2|tekken|temple run|the binding of isaac|the last of us|the legend of zelda|the long dark|the walking dead|thehunter call of the wild|this war of mine|tomb raider|trackmania|train simulator|two point hospital|unturned|vampire survivors|warcraft|warthunder|watch dogs|world of tanks|world of warships|worms|wwe 2k|yakuza|zuma|8 ball pool|2048|bad ice cream|fireboy and watergirl|happy wheels|moviestarplanet|panfu|transformice|habbo|msp|metin2|tibia|margonem|saper|pasjans|tetris|pac-man|snake|space invaders|brick breaker|doodle jump|jetpack joyride|subway surfers|cut the rope|hill climb racing|crossy road|pou|my talking tom|geometry dash lite|candy crush|homescapes|gardenscapes|township|merge mansion|monopoly go|coin master|pokemon masters|marvel snap|clash mini|squad busters|diablo immortal|raid shadow legends"),
  roblox:list("a dusty trip|a universal time|ability wars|adopt me|airship assault|all star tower defense|anime adventures|anime defenders|anime dimensions|anime fighters simulator|anime last stand|anime race clicker|apeirophobia|arcane odyssey|arsenal|arsenal reloaded|asteroid mining simulator|bad business|bake a cake|banana eats|bedwars|bee swarm simulator|berry avenue|blade ball|block tales|blox fruits|bloxburg|booga booga|break in|break in 2|breaking point|brookhaven|brookhaven rp|build a boat for treasure|build an island|cafeland|catalog avatar creator|combat warriors|creatures of sonaria|dandy's world|da hood|dead rails|death ball|doors|dragon adventures|dress to impress|driving empire|elemental battlegrounds|epic minigames|evade|flee the facility|flicker|football fusion|frontlines|funky friday|gacha online|grace|grand piece online|hide and seek extreme|horrific housing|islands|jailbreak|kaiju universe|king legacy|livetopia|loomian legacy|lumber tycoon 2|mad city|meepcity|mega mansion tycoon|mining simulator|mining simulator 2|monster islands|murder mystery 2|my restaurant|natural disaster survival|nico's nextbots|ninja legends|obby creator|obby but you are on a bike|obby but you're on a bike|pet simulator|pet simulator 99|phantom forces|piggy|plane crazy|pressure|prison life|project slayers|rainbow friends|restaurant tycoon|restaurant tycoon 2|retail tycoon|retail tycoon 2|rivals|royale high|shindo life|slap battles|speed draw|speed run 4|strongest battlegrounds|super bomb survival|survive the killer|survive the disasters|theme park tycoon|theme park tycoon 2|toilet tower defense|tower defense simulator|tower heroes|tower of hell|untitled boxing game|vehicle simulator|welcome to bloxburg|work at a pizza place|your bizarre adventure|3008|99 nights in the forest|forsaken|grow a garden|steal a brainrot|bee swarm simulator|mm2|murderers vs sheriffs duels|pls donate|rate my avatar|roblox high school|sharkbite|sharkbite 2|southwest florida|specter|the mimic|the rake remastered|treasure quest|twilight daycare|war tycoon|warrior cats ultimate edition|waterpark oceanic|zombie attack"),
  minecraft:list("ancient city|bastion|bastion remnant|desert temple|dżunglowa świątynia|jungle temple|leśna posiadłość|woodland mansion|nether fortress|ocean monument|ocean ruins|pillager outpost|ruined portal|shipwreck|stronghold|trial chambers|village|wioska|witch hut|igloo|mineshaft|kopalnia|end city|jaskinia|amethyst geode|biom wiśniowy|cherry grove|desert|pustynia|forest|las|jungle|dżungla|swamp|bagno|mangrove swamp|taiga|savanna|badlands|ocean|deep dark|dripstone caves|lush caves|meadow|plains|równina|snowy plains|mushroom fields|nether wastes|crimson forest|warped forest|soul sand valley|basalt deltas|beach|river|mountains|góry|trial key|mace|maczuga|brush|pędzel|bundle|spyglass|luneta|goat horn|kozi róg|recovery compass|lodestone|respawn anchor|beacon|enchanting table|anvil|kowadło|grindstone|stonecutter|loom|barrel|beczka|hopper|lej|dispenser|dropper|observer|piston|sticky piston|repeater|comparator|lever|button|pressure plate|minecart|boat|chest boat|saddle|name tag|lead|firework|elytra|ender chest|shulker box|dragon egg|nether star|heart of the sea|nautilus shell|breeze|bogged|camel|sniffer|allay|frog|tadpole|goat|panda|polar bear|parrot|rabbit|ocelot|strider|zoglin|vex|vindicator|wandering trader|trader llama|mooshroom|snow golem|iron golem|ender dragon|enderdragon"),
  creators:list("abstrachuje|adin ross|ali-a|amouranth|aphmau|asmongold|avgn|bagi|banshee|beautyvvitch|beta squad|bungee|caseoh|carryminati|charli d'amelio|chunkz|corridor crew|cristiano|coryxkenshin|danny gonzalez|david dobrik|deji|dhar mann|disowskyy|dobre brothers|dr disrespect|dude perfect|emma chamberlain|faZe rug|faze rug|fernanfloo|finnster|flamingo|game theory|grian|gronkh|ibai|jaiden animations|james charles|jelly|jesser|jynxzi|karol friz wiśniewski|karl jacobs|kiza|konopskyy|ksiol|ludwig|luzu|mandzio|marques brownlee|mkbhd|morgz|mortalcio|mrwhosetheboss|natsu|neon|nelson|noobek|penguinz0|penguinz 0|penguinz0|pokimane|prestonplayz|quackity|quaz|rafonix|rezi style|rubius|ryan trahan|saiko|sidemen|smosh|squeezie|stampylonghead|sykkuno|tary|the try guys|theodd1sout|tibo inshape|tromba|t-series|typowy fitnesiak|vikkstar|wersow|wirtualna polska|wujek łuki|xayoo|xqc|zebo|zjednoczeni|zoella|zuzanna borucka|5-minute crafts|alan chikin chow|airrack|bald and bankrupt|beast philanthropy|beluga|brent rivera|cocomelon|collins key|dawid frank|dobrodziej|duolingo|faZe clan|gawr gura|hasanabi|holak|jacksfilms|jesser reacts|lachu|lexy chaplin|linus tech tips|ltt|mark rober|moistcr1tikal|mr nightmare|ninja|nuke's top 5|penguinz0|sam sulek|shane dawson|sophie rain|the sidemen|trymacs|unbox therapy|vanossgaming|vikkstar123|w2s|willyrex|zach king|zoe sugg|wojan|palion|mamiko|kaluch|doknes|enzzi|eniuu|yoshi|gilathissnew|fairout|safemodtv|dealereq|vertez|eleven|skkf|rojson|tivolt|kiszak|isamu|boxdel|naruciak|gimper|wardęga|blowek|stuu|kamerzysta|mini majk|marcin dubiel|karolek|rock alone|rembol|remek|kasix|pago|nitro|tromba|mortalcio|fagata|genzie|ekipa|kushi|sheo|czuux|sitrox|lachu|vito minecraft|przemek best games|bracia malczyńscy|adbuster|mietczynski|karol paciorek|krzysztof gonciarz|planeta faktów|astrofaza|emce kwadrat|naukowy bełkot|scifun|tvgry|nrgeek|zwariowani|rezigiusz|kacper porębski|mandzio|disowskyy|poczciwy krzychu|dejmien|tadzik|loczek|xyro|farell|scrappy|jawor|jaydabrowsky|kacper błoński|team x|werka serducho|stokes twins|like nastya|kids diana show|vlad and niki|ryan's world|unspeakable|kreekcraft|itsfunneh|denis|jelly|slogoman|kwebbelkop|lachlan|typical gamer|sypherpk|muselk|fresh|bajan canadian|popularmmos|captain sparklez|stampy|smallishbeans|ldshadowlady|fundy|badboyhalo|skeppy|antvenom|iballisticsquid|fitmc|skip the tutorial|wisp|camman18|rekrap2|clownpierce|forge labs|mumbo jumbo|goodtimeswithscar|xisumavoid|impulseSV|geminitay|fwhip|pixlriffs|wattles|ibxtoycat|thinknoodles|inquisitormaster|gamingwithkev|pghlfilms|konekokitten|tanqr|bandites|poke|ant|tofu|sketch|sub|denisdaily|parlo|remainings|chad wild clay|vy qwaint|markiplier|pewdiepie|jacksepticeye|mrbeast|ishowspeed|kai cenat|dream|technoblade|tommyinnit|sapnap|tubbo|ranboo|georgenotfound|dantdm|sssniperwolf|logan paul|jake paul|ksi|lazarbeam|preston|captainsparklez"),
  brands:list("abercrombie & fitch|adobe|airbnb|aliexpress|alpine|aston martin|atari|avon|balenciaga|balmain|barilla|beats|ben & jerry's|bentley|bershka|bic|blackberry|booking|bosch|bugatti|burberry|burger king|cadbury|calvin klein|canon|cartier|casio|chanel|chevrolet|cheetos|citroen|colgate|converse|crocs|dacia|danone|dior|disney|dodge|dolce & gabbana|doritos|dr pepper|ebay|electrolux|etihad|etsy|fedex|fiat|fila|ford|fujifilm|garnier|gillette|givenchy|google|gucci|heinz|honda|hot wheels|hugo boss|hyundai|ibm|intel|jaguar|jeep|johnson & johnson|kia|kitkat|kodak|lacoste|lays|levis|loreal|louis vuitton|mazda|microsoft|mini|mitsubishi|msi|mustang|nescafe|nestle|new balance|nikon|nissan|nutella|opel|oracle|oreo|panasonic|paypal|peugeot|philips|pinterest|pringles|pull&bear|ray-ban|red bull|renault|revolut|rolex|rolls-royce|rossmann|samsung|seat|sephora|shell|siemens|skoda|skype|snapchat|snickers|spacex|starbucks|subaru|subway|suzuki|tesco|tiktok|toblerone|tommy hilfiger|toyota|twitch|uber|uniqlo|ups|versace|vinted|visa|vodafone|volvo|walmart|whatsapp|xiaomi|youtube|zalando|zendesk|zoom"),
  tech:list("access point|adapter|adres ip|airpods|akumulator|android|antywirus|api|apple watch|arduino|backup|bateria|bluetooth|browser|cache|captcha|chmura|cloud|cms|cookie|cpu|cyberbezpieczeństwo|domena|ethernet|firewall|firmware|framework|ftp|gps|gpu|hosting|html|http|https|hub usb|ikona|interfejs|javascript|joystick|kernel|kod qr|kompresja|konto|lan|laser|mac address|malware|mechaniczna klawiatura|nas|nfc|oled|open source|optyczna mysz|pamięć ram|panel dotykowy|piksel|pin|port usb|procesor|proxy|qr code|raid|repozytorium|reset|rgb|rom|root|scanner|sieć|sim|smart home|smart tv|ssd|streaming|stylus|tablet graficzny|tcp|touchscreen|transistor|udp|url|vpn|wan|wi-fi|wifi|wtyczka|xml|zip|agregator|alexa|amazon echo|apple tv|bios|bot|cdn|chatbot|c++|css|dysk zewnętrzny|displayport|docker|dyskietka|excel|firefox|google chrome|google drive|kabel ethernet|kabel usb|karta dźwiękowa|karta sieciowa|konsola|kontroler|linux|macbook|machine learning|monitor oled|motherboard|notebook|notion|obs|office|one drive|onedrive|pendrive|php|powerpoint|python|raspberry pi|safari|siri|slack|sql|switch|terminal|typescript|ubuntu|unity|unreal engine|visual studio code|vscode|wordpress"),
  music:list("adele|aerosmith|alan walker|alicia keys|arctic monkeys|avicii|backstreet boys|beastie boys|bee gees|black sabbath|bob marley|bon jovi|britney spears|calvin harris|camila cabello|cardi b|charli xcx|cher|chopin|christina aguilera|daft punk|david bowie|david guetta|depeche mode|dido|dire straits|dj khaled|dua lipa|elton john|elvis presley|fall out boy|fleetwood mac|florence and the machine|foo fighters|green day|guns n' roses|harry styles|hozier|imagine dragons|jennifer lopez|juice wrld|kanye west|katy perry|kendrick lamar|kesha|lana del rey|lil nas x|lil peep|lil wayne|lizzo|lorde|madonna|maroon 5|marshmello|michael jackson|miley cyrus|nicki minaj|one direction|panic at the disco|pink|pitbull|radiohead|rammstein|red hot chili peppers|sabrina carpenter|selena gomez|shakira|sia|skrillex|slipknot|snoop dogg|system of a down|tame impala|tina turner|twenty one pilots|usher|whitney houston|zayn|bedoes|białas|bracia figo fagot|brodka|cleo|daria zawiałow|doda|donatan|feel|grubson|kwiat jabłoni|lanberry|lemon|maryla rodowicz|męskie granie|michał szpak|mrozu|myslovitz|paktofonika|paluch|perfect|sanah|sarsa|sławomir|sokół|t love|vito bambino|young igi|young leosia|young multi|żabson|synthpop|drum and bass|dnb|dubstep|hardstyle|opera|r&b|soul|funk|grunge|alternative|ambient|lofi|lo-fi|soundtrack|musical|orkiestra|chór|wokal|refren|zwrotka|album|singiel|playlista|winyl|kaseta|gramofon|syntezator|tamburyn|klarnet|puzon|kontrabas|mandolina"),
  movies:list("arcane|alien|american horror story|american pie|anatomia greya|andor|anne with an e|ant-man|arrival|asterix i obelix|avatar ostatni władca wiatru|babylon berlin|back to the future|bambi|bee movie|beetlejuice|better call saul|big bang theory|blade runner|bojack horseman|borat|bridgertonowie|brooklyn nine-nine|cars|casino royale|chernobyl|chłopaki nie płaczą|coco|cobra kai|conjuring|cruella|czterej pancerni i pies|dark|deadpool|dexter|diuna|doctor strange|dom z papieru|dr house|dragon ball|dunkierka|encanto|euphoria|fantastyczne zwierzęta|fight club|flinstonowie|forest gump|frozen|furiosa|gambit królowej|garfield|ghostbusters|gladiator|godzilla|good omens|grawitacja|green book|grey's anatomy|grinch|gwiezdne wojny|hannibal|house of cards|hotel transylvania|how i met your mother|igrzyska śmierci|incepcja|inside out|interstellar|invincible|iron man|it|jak poznałem waszą matkę|john wick|joker|jumanji|jurassic world|kapitan bomba|karate kid|kiler|klątwa|kompania braci|korona królów|kraina lodu|król lew|kung fu panda|la casa de papel|loki|lucifer|madagaskar|mandalorian|matrix|minionki|mission impossible|moon knight|mr robot|narcos|nietykalni|obcy|ojciec chrzestny|peaky blinders|pingwiny z madagaskaru|piraci z karaibów|pokemon|potwory i spółka|predator|prison break|psi patrol|punisher|ratatuj|rick and morty|ricky stanicky|rodzina soprano|rozdzieleni|samotny wilk|sherlock|simpsonowie|smile|sonic|south park|sponge bob|squid game|star trek|supernatural|the crown|the last of us|the walking dead|thor|top gun|toy story|transformers|twin peaks|tytanic|umbrella academy|venom|vikings|wakanda forever|wednesday|władca pierścieni|wolf of wall street|x-men|zaplątani|zielona mila|zootopia"),
};

// Kolejna warstwa contentu: dopisujemy szerokie, rozpoznawalne odpowiedzi bez
// naruszania wcześniejszych pul. mergeUnique usuwa powtórzenia po normalizacji.
export const supplementalPools = {
  animals:list("antylopa|bizon|bawół|łoś|renifer|daniel|gazela|gnu|wielbłąd|dromader|osioł|muł|szakal|kojot|ryś|żbik|rosomak|borsuk|łasica|fretka|mangusta|szop|skunks|tapir|mrówkojad|pancernik|leniwiec|kapibara|szynszyla|świnka morska|mysz|szczur|nornica|kret|surykatka|lemur|pawian|makak|mandryl|gibon|kobra|pyton|boa|anakonda|waran|kameleon|gekon|salamandra|traszka|rzekotka|płaszczka|miecznik|tuńczyk|łosoś|karp|sum|szczupak|okoń|węgorz|konik morski|rozgwiazda|jeżowiec|krewetka|langusta|małż|ostryga|kałamarnica|mątwa|pstrąg|mors|albatros|kanarek|łabędź|paw|struś|emu|kiwi|dzięcioł|jaskółka|kos|kukułka|łosoś|ważka|biedronka|modliszka|pasikonik|konik polny|karaluch|termity|stonoga|skorpion|kleszcz"),
  fruits:list("grejpfrut czerwony|mandarynka satsuma|mandarynka klementynka|pomarańcza krwista|pomarańcza|cytron|yuzu|ugli|winogrono czerwone|winogrono zielone|winogrono białe|arbuz żółty|melon galia|melon piel de sapo|melon kantalupa|banan plantan|plantan|graviola|guanabana|mangostan|longan|langsat|salak|owoc chlebowca|jackfruit|karambola|pitaja|smoczy owoc|miechunka|fizalis|kumkwat|tangelo|tamarillo|feijoa|kiwano|acerola|nashi|gruszka azjatycka|dereń|czarny bez|bez czarny|jarzębina|malina moroszka|moroszka|malina czarna|porzeczka czerwona|porzeczka czarna|porzeczka biała|agrest czerwony|winogrono|śliwka węgierka|papierówka|antonówka|ligol|reneta|jonagold|liczi|rambutan|durian|marakuja|gujawa|papaja|kaki|persymona|opuncja|kokos|awokado|aronia|berberys|borówka amerykańska|borówka czarna|brusznica|cherymoja|czerymoja|jabuticaba|jagoda kamczacka|jagoda goji|kalamondyna|limonkwat|malinojeżyna|nektarynka płaska|owoce leśne|pomarańcza bergamotka|poziomka|śliwka renkloda|wiśnia acerola"),
  food:list("barszcz czerwony|barszcz biały|flaki|fasolka po bretońsku|leczo|gulasz|pieczeń|żeberka|kotlet schabowy|kotlet drobiowy|kotlet sojowy|mielony|de volaille|zrazy|kluski śląskie|pyzy|kartacze|łazanki|racuchy|placki|naleśniki|krokiety|kapuśniak|grochówka|chłodnik|zupa dyniowa|zupa grzybowa|zupa cebulowa|zupa krem|risotto|gnocchi|ravioli|tagliatelle|penne|tortellini|pizza margherita|calzone|focaccia|bruschetta|lasagna|kebab box|falafel|shawarma|gyros|pad thai|spring rollsy|sajgonki|pho|udon|miso|tempura|onigiri|nigiri|maki|burger|cheeseburger|nuggetsy|skrzydełka|hot dog|corn dog|quesadilla|enchilada|guacamole|chili con carne|paella|gazpacho|couscous|kuskus|zapiekanka|tost francuski|croissant|bagietka|chałka|bajgiel|precel|muffinka|brownie|tiramisu|makowiec|piernik|karpatka|wuzetka|beza|pavlova|donut|pączek|sorbet|galaretka|kisiel|budyń|nachosy|krakersy|paluszki|orzeszki|pistacje|migdały|granola|płatki kukurydziane|jajko sadzone|jajko na miękko|jajko na twardo"),
  school:list("przedszkole|podstawówka|liceum|technikum|zawodówka|studia|uczelnia|akademik|dziekanat|rektorat|świetlica|sala gimnastyczna|boisko|plac zabaw|pracownia komputerowa|laboratorium|chemik|fizyk|pedagog|psycholog szkolny|wychowawca|woźny|portier|sprzątaczka|korepetycje|lekcja|wykład|ćwiczenia|laboratoria|semestr|rok szkolny|apel|wywiadówka|rada pedagogiczna|konkurs|olimpiada|stypendium|świadectwo|dyplom|certyfikat|zaliczenie|kolokwium|sesja|indeks|legitymacja|mundurek|strój galowy|kapcie|kalkulator|temperówka|zakreślacz|mazak|flamaster|farby|pędzel|blok rysunkowy|klej|nożyczki|zszywacz|spinacz|segregator|teczka|drukarka|projektor|rzutnik|globus|mapa|mikroskop|probówka|atlas|słownik|encyklopedia|lektura|bibliotekarz|autobus szkolny|wagary|spóźnienie|nieobecność|usprawiedliwienie"),
  sport:list("piłkarzyki|futsal|piłka plażowa|siatkówka plażowa|koszykówka 3x3|streetball|unihokej|lacrosse|polo|waterpolo|piłka wodna|kajak polo|żużel|motogp|nascar|drift|karting|bmx|downhill|mountain biking|kolarstwo górskie|kolarstwo szosowe|łyżwiarstwo figurowe|łyżwiarstwo szybkie|short track|saneczkarstwo|bobsleje|skeleton|skialpinizm|snowkiting|windsurfing|kitesurfing|wakeboarding|nurkowanie|skoki do wody|pływanie synchroniczne|wspinaczka sportowa|bouldering|crossfit|trójbój siłowy|podnoszenie ciężarów|armwrestling|strongman|fitness|aerobik|zumba|pilates|joga|cheerleading|akrobatyka|trampolina|breakdance|taniec sportowy|e-sport|ultimate frisbee|frisbee|dodgeball|zbijak|paintball|airsoft|kręgle|bowling|snooker|poker sportowy|brydż|go|scrabble|real madrid|fc barcelona|borussia dortmund|ajax|napoli|roma|atletico madryt|tottenham|newcastle|wisła kraków|widzew łódź|raków częstochowa|jagiellonia białystok"),
  everyday:list("komoda|regał|półka|szuflada|wieszak|stolik|fotel|taboret|materac|kołdra|prześcieradło|poszewka|zasłona|roleta|żaluzja|wycieraczka|odświeżacz powietrza|doniczka|wazon|ramka na zdjęcie|obraz|plakat|świeczka|zapalniczka|zapałki|latarka|przedłużacz|listwa zasilająca|gniazdko|włącznik|żarówka|wentylator|grzejnik|kaloryfer|klimatyzator|młynek|blender|mikser|toster|mikrofalówka|piekarnik|zmywak|gąbka|ścierka|płyn do naczyń|worki na śmieci|folia aluminiowa|papier do pieczenia|rękawiczki|szczotka do włosów|dezodorant|perfumy|krem|balsam|maszynka do golenia|golarka|suszarka|prostownica|lokówka|prysznic|wanna|umywalka|kran|toaleta|szczotka do toalety|kosmetyczka|notes|kalendarz|planer|koperta|znaczek|paczka|nożyczki|taśma klejąca|klej|zszywacz|spinacz|parasolka|peleryna przeciwdeszczowa|szalik|rękawiczki|pasek|zegarek|bransoletka|naszyjnik|kolczyki|walizka|powerbank|adapter|przejściówka|pilot|budzik"),
  vegetables:list("romanesco|kapusta włoska|kapusta czerwona|kapusta biała|kapusta kiszona|rzodkiew|rzodkiew japońska|daikon|marchew żółta|marchew fioletowa|papryka czerwona|papryka zielona|papryka żółta|papryka pomarańczowa|pomidor malinowy|pomidor koktajlowy|pomidorki koktajlowe|ogórek kiszony|ogórek gruntowy|ogórek szklarniowy|cebula czerwona|cebula biała|cebula żółta|czosnek niedźwiedzi|ziemniak|batat|ignam|yam|taro|pasternak|brukiew|fenkuł|koper włoski|endywia|radicchio|mizuna|rukiew wodna|skorzonera|salsefia|cykoria|karczoch|kard|kolendra|bazylia|mięta|oregano|tymianek|majeranek|rozmaryn|lubczyk|szczypiorek|natka pietruszki|kiełki|kiełki fasoli|kiełki rzodkiewki|fasola mung|fasola czerwona|fasola biała|fasola czarna|groszek cukrowy|zielony groszek|soczewica czerwona|soczewica zielona|ciecierzyca|bób|dynia hokkaido|dynia piżmowa|kabaczek|cukinia żółta|bakłażan|kalarepa|kalafior fioletowy|kalafior zielony"),
  internet:list("mastodon|bluesky|vine|clubhouse|quora|medium|patreon|onlyfans|kick|trovo|steam community|itch.io|gamejolt|gog|discord|teamspeak|ventrilo|slack|notion|trello|jira|dropbox|onedrive|google drive|icloud|mega|wetransfer|deepl|google translate|bing|duckduckgo|yahoo|firefox|chrome|opera|safari|edge|brave|tor browser|vimeo|dailymotion|soundcloud|bandcamp|tidal|deezer|apple music|youtube music|prime video|disney plus|hbo max|max|viaplay|canal plus|player|tvp vod|skyshowtime|twitch|kick|ebay|aliexpress|etsy|zalando|empik|ceneo|pepper|inpost|paczkomat|uber eats|wolt|just eat|grubhub|google maps|waze|jakdojade|moovit|endomondo|strava|tinder|bumble|badoo|grindr|duolingo|quizlet|kahoot|wolfram alpha|chatgpt|claude|perplexity|midjourney|dall-e|figma|behance|dribbble|pinterest|snapchat|bereal|threads|linkedin|github|gitlab|bitbucket|codepen|replit"),
  games:list("age of mythology|animal well|anno|arena breakout|asphalt 9|back 4 blood|balatro|banished|batman arkham|black desert online|bloodborne|buckshot roulette|car mechanic simulator|cities skylines 2|company of heroes|content warning|cult of the lamb|dead island|deadlock|deltarune|descenders|devour|don't starve together|dragon ball fighterz|dredge|euro truck simulator 2|factorio|fears to fathom|finals|for honor|fortnite festival|frostpunk|gang beasts|goat simulator|golf with your friends|grounded|gta san andreas|gta vice city|guild wars 2|half life 2|hello kitty island adventure|high on life|hoi4|hearts of iron 4|inscryption|inside|jackbox|just shapes and beats|killing floor|lego fortnite|life is strange|lost ark|manor lords|marvel rivals|metro 2033|minecraft dungeons|minecraft legends|monster hunter|muck|multiversus|nba 2k|osu mania|party animals|pico park|planet zoo|plateup|pokemon scarlet|pokemon violet|powerwash simulator|prison architect|prop hunt|ready or not|resident evil|scrap mechanic|skull and bones|sons of the forest|splitgate|stick fight|supermarket simulator|tabs|totally accurate battle simulator|teardown|the crew|the escapists|the quarry|the stanley parable|the walking dead game|throne and liberty|tiny glade|valorant|v rising|warhammer|wobbly life|wolfenstein|zelda breath of the wild"),
  tech:list("ssd nvme|dysk nvme|m2|m.2|pcie|displayport|thunderbolt|usb-c|usb c|ethernet|kabel sata|sata|radiator|pasta termoprzewodząca|aio|chłodzenie wodne|cooler|wiatrak|monitor ips|monitor va|monitor oled|częstotliwość odświeżania|herce|hz|rozdzielczość|4k|full hd|qhd|touchscreen|ekran dotykowy|czytnik linii papilarnych|face id|nfc|gps|esim|sim|smart home|inteligentny dom|żarówka smart|odkurzacz automatyczny|robot sprzątający|konsola przenośna|steam deck|rog ally|drukarka laserowa|drukarka atramentowa|skaner|projektor|soundbar|kino domowe|głośnik bluetooth|airpods|smartband|opaska fitness|kamera sportowa|gopro|action cam|stabilizator|gimbal|powerbank|ładowanie indukcyjne|ładowarka bezprzewodowa|ethernet|vpn|dns|adres ip|domena|hosting|serwer dedykowany|vps|chmura|cloud|backup|kopia zapasowa|antywirus|menedżer haseł|hasło|kod qr|captcha|firewall|api|frontend|backend|javascript|typescript|react|python|java|c++|docker|git|github|linux|ubuntu|macbook|iphone|pixel|raspberry pi|arduino"),
  music:list("olivia rodrigo|chappell roan|tate mcrae|sza|travis scott|metro boomin|21 savage|future|tyler the creator|frank ocean|the neighbourhood|arctic monkeys|maneskin|måneskin|måneskin|måneskin|måneskin|the beatles|rolling stones|pink floyd|ac dc|ac/dc|system of a down|my chemical romance|bring me the horizon|paramore|limp bizkit|korn|iron maiden|megadeth|pantera|deftones|muse|the killers|gorillaz|gorillaz|stromae|maneskin|måneskin|alan walker|kygo|martin garrix|tiesto|tïesto|avicii|calvin harris|david guetta|swedish house mafia|skrillex|marshmello|fred again|bad bunny|karol g|rosalia|shawn mendes|sam smith|benson boone|laufey|gracie abrams|sabaton|powerwolf|nightwish|epica|kwiat jabłoni|dawid kwiatkowski|margaret|agnieszka chylińska|o.s.t.r.|ostr|pezet|otsochodzi|kizo|szpaku|quequality|que bonafide|quebonafide|okiem|grubson|donatan|cleo|bedoes|white 2115|oliwka brazil|bambi|favst|kubi producent|francis|malik montana|taco hemingway|mata|sanah"),
  movies:list("oppenheimer|barbie|poor things|saltburn|fallout|the bear|shogun|the gentlemen|house of the dragon|rings of power|pierścienie władzy|wandavision|daredevil|hawkeye|echo|agatha all along|falcon i zimowy żołnierz|ms marvel|secret invasion|moon knight|the punisher|jessica jones|iron fist|defenders|flash|arrow|supergirl|gotham|titans|doom patrol|sandman|one piece|naruto|bleach|attack on titan|demon slayer|jujutsu kaisen|death note|fullmetal alchemist|my hero academia|spy x family|chainsaw man|sailor moon|pokemon|digimon|avatar|legenda aanga|korra|gravity falls|pora na przygodę|regular show|gumball|fineasz i ferb|rick and morty|bojack horseman|family guy|american dad|futurama|disenchantment|big mouth|sex education|elite|riverdale|13 reasons why|outer banks|ginny and georgia|emily in paris|you|ozark|mindhunter|true detective|fargo|sukcesja|succession|the white lotus|yellowstone|the handmaid's tale|opowieść podręcznej|czarne lustro|black mirror|lost|zagubieni|prison break|house|dr house|grey's anatomy|anatomia greya|gotowe na wszystko|desperate housewives|modern family|brooklyn nine-nine|community|parks and recreation|seinfeld|biuro|the office|wednesday|stranger things|breaking bad|better call saul"),
  minecraft:list("armadillo|pancernik|creaking|happy ghast|ghastling|zombie villager|husky|stray|cave spider|spider jockey|chicken jockey|skeleton horse|zombie horse|pillager|illusioner|witch|witch hut|trial spawner|vault|ominous vault|ominous bottle|wind charge|heavy core|copper bulb|crafter|decorated pot|suspicous sand|podejrzany piasek|suspicious gravel|podejrzany żwir|sniffer egg|pitcher plant|torchflower|wiśniowe drewno|cherry wood|mangrove wood|bamboo block|blok bambusa|mud|błoto|packed mud|ubite błoto|mud bricks|cegły błotne|calcite|tuff|bazalt|blackstone|czarny kamień|glowstone|jasnogłaz|quartz|kwarc|prismarine|pryzmaryn|sea lantern|latarnia morska|lantern|latarnia|campfire|ognisko|soul campfire|scaffolding|rusztowanie|armor stand|stojak na zbroję|item frame|ramka na przedmiot|painting|obraz|flower pot|doniczka|cauldron|kocioł|brewing stand|statyw alchemiczny|jukebox|szafa grająca|note block|blok dźwiękowy|target|cel|trapped chest|skrzynia pułapka|redstone torch|pochodnia redstone|redstone lamp|lampa redstone|daylight sensor|czujnik światła|tripwire hook|hak na linkę|shears|nożyce|flint and steel|krzesiwo|carrot on a stick|marchewka na patyku|warped fungus on a stick|wypaczony grzyb na patyku|brush|pędzel|spyglass|luneta|goat horn|kozi róg|clock|zegar|compass|kompas|recovery compass|kompas powrotny|mapa|book|książka|enchanted book|zaklęta książka"),
  roblox:list("anime vanguards|anime reborn|anime royale|anime power defense|anime clash|blue lock rivals|jujutsu infinite|fruit battlegrounds|type soul|peroxide|demonfall|demon blade|heroes battlegrounds|the strongest battlegrounds|sorcerer battlegrounds|death ball|blade ball|basketball legends|football legends|volleyball legends|basketball zero|rivals|gunfight arena|counter blox|big paintball|big paintball 2|energy assault|untitled tag game|regretevator|pressure|doors|rooms|interliminality|dead silence|the maze|identity fraud|scary sushi|break in story|break in 2|evade|nico's nextbots|the floor is lava|sharkbite|sharkbite 2|build a boat|plane crazy|jailbreak|mad city|driving empire|car crushers 2|greenville|southwest florida|vehicle legends|pet simulator x|pet simulator 99|pets go|bubble gum simulator|bubble gum simulator infinity|mining simulator 2|restaurant tycoon 2|retail tycoon 2|theme park tycoon 2|lumber tycoon 2|toilet tower defense|tower battles|tower heroes|tds|tower defense simulator|obby creator|obby but you're on a bike|speed run 4|mega easy obby|escape running head|natural disaster survival|work at a pizza place|catalog avatar creator|rate my avatar|pls donate|mic up|epic minigames|flicker|breaking point|total roblox drama|outlaster|islands|bedwars|skywars|lucky block battlegrounds|super league soccer|dandy's world|forsaken|grow a garden|steal a brainrot|99 nights in the forest"),
  creators:list("kacper dworniczak|mniej więcej|bez kanału|matura to bzdura|historia bez cenzury|ciekawehistorie|imponderabilia|radio naukowe|uwaga naukowy bełkot|pasjonaci|polimaty|arhn.eu|tvgrypl|quaz|hed|grzegorz błachnio|marcin banot|bungee|gimper|naruciak|rezi|rezigiusz|friz|wersow|blowek|stuu|izak|izakooo|xayoo|ewron|pasha|pasha gaming|saju|pago|kasix|michu|kubon|poczciwy krzychu|eleven|vertez|dealereq|palion|wojan|doknes|enzzi|eniuu|yoshi|safemodtv|gilathissnew|fairout|kaluch|noobek|rojson|tivolt|kiszak|isamu|lachu|sitrox|czuux|sheo|rembol|mandzio|disowskyy|skkf|karolek|rock alone|vito minecraft|przemek best games|mumbo jumbo|grian|goodtimeswithscar|xisumavoid|geminitay|smallishbeans|ldshadowlady|camman18|rekrap2|clownpierce|forge labs|wisp|fitmc|skip the tutorial|ibxtoycat|dream|technoblade|tommyinnit|sapnap|georgenotfound|ranboo|tubbo|aphmau|dantdm|captainsparklez|popularmmos|stampy|preston|unspeakable|kreekcraft|flamingo|inquisitormaster|gamingwithkev|tanqr|bandites|poke|denisdaily|itsfunneh|parlo"),
  brands:list("action|aldi|auchan|media expert|media markt|rtv euro agd|x-kom|morele|komputronik|empik|decathlon|leroy merlin|castorama|obi|pepco|dealz|hebe|douglas|notino|super-pharm|intermarche|stokrotka|dino|netto|aldi|ikea|jysk|agata meble|black red white|brw|home&you|homla|sinsay|mohito|medicine|4f|ccc|deichmann|eobuwie|zalando|uniqlo|calzedonia|intimissimi|victoria's secret|under armour|the north face|columbia|patagonia|timberland|dr martens|crocs|birkenstock|skechers|asics|mizuno|umbro|lotto|fila|champion|supreme|off-white|carhartt|vinted|olx|temu|shein|aliexpress|ebay|etsy|booking|airbnb|bolt|uber|free now|inpost|dpd|dhl|fedex|ups|orlen|shell|bp|circle k|moya|lotto|lego|hot wheels|barbie|fisher-price|hasbro|mattel|nerf|playmobil|nvidia|amd|intel|razer|logitech|corsair|steelseries|hyperx|msi|gigabyte|palit|seagate|kingston|sandisk|western digital|wd|jbl|bose|marshall|anker|garmin|gopro|canon|nikon|fujifilm|adobe|microsoft|google|meta|openai|amazon|disney|hbo|prime video|twitch|youtube"),
};
supplementalPools.minecraft = unique([...supplementalPools.minecraft,...list("zombie|zombiak|skeleton|szkielet|spider|pająk|cave spider|pająk jaskiniowy|witch|wiedźma|slime|szlam|blaze|płomyk|villager|wieśniak|iron golem|żelazny golem|snow golem|bałwan|śnieżny golem|sheep|owca|cow|krowa|pig|świnia|chicken|kurczak|wolf|wilk|cat|kot|horse|koń|donkey|osioł|mule|muł|bee|pszczoła|fox|lis|frog|żaba|tadpole|kijanka|axolotl|aksolotl|dolphin|delfin|guardian|strażnik|elder guardian|prastrażnik|starszy strażnik|drowned|utopiec|pillager|rabieżca|evoker|przywoływacz|ravager|dewastator|niszczyciel|silverfish|rybik cukrowy|magma cube|kostka magmy|wither skeleton|mroczny szkielet|zombified piglin|zombifikowany piglin|camel|wielbłąd|sniffer|wąchacz|goat|koza|polar bear|niedźwiedź polarny|parrot|papuga|rabbit|królik|wandering trader|wędrowny handlarz|trader llama|lama handlarza|mooshroom|grzybowa krowa|ender dragon|smok endu|bat|nietoperz|squid|kałamarnica|glow squid|świecąca kałamarnica|turtle|żółw|salmon|łosoś|cod fish|dorsz|pufferfish|rozdymka|tropical fish|ryba tropikalna|husk|posuch|stray|tułacz|phantom|fantom|armadillo|pancernik|warden|nadzorca|breeze|wicher|bogged|bagniak")]);
supplementalPools.movies = unique([...supplementalPools.movies,...list("game of thrones|gra o tron|the witcher|wiedźmin|money heist|la casa de papel|dom z papieru|the office|biuro|friends|przyjaciele|house|dr house|grey's anatomy|anatomia greya|the handmaid's tale|opowieść podręcznej|black mirror|czarne lustro|lost|zagubieni|succession|sukcesja|how i met your mother|jak poznałem waszą matkę|the big bang theory|teoria wielkiego podrywu|house of the dragon|ród smoka|the walking dead|żywe trupy|star wars|gwiezdne wojny|the lord of the rings|władca pierścieni|pirates of the caribbean|piraci z karaibów|the lion king|król lew|cars|auta|frozen|kraina lodu|despicable me|minionki|how to train your dragon|jak wytresować smoka|finding nemo|gdzie jest nemo|the incredibles|iniemamocni|monsters inc|potwory i spółka|inside out|w głowie się nie mieści|tangled|zaplątani|ratatouille|ratatuj|up|odlot|back to the future|powrót do przyszłości|the godfather|ojciec chrzestny|alien|obcy|inception|incepcja|gravity|grawitacja|dune|diuna|the hunger games|igrzyska śmierci|fantastic beasts|fantastyczne zwierzęta|the green mile|zielona mila|the wolf of wall street|wilk z wall street|spongebob|sponge bob|spongebob kanciastoporty|the simpsons|simpsonowie|adventure time|pora na przygodę|gravity falls|wodogrzmoty małe|avatar the last airbender|avatar legenda aanga|avatar ostatni władca wiatru|spider-man into the spider-verse|spider-man uniwersum|moana|vaiana|zootopia|zwierzogród|ice age|epoka lodowcowa|hotel transylvania|hotel transylwania|paw patrol|psi patrol|captain america|kapitan ameryka|guardians of the galaxy|strażnicy galaktyki|black panther|czarna pantera|the intouchables|nietykalni|the conjuring|obecność")]);

export const focusedPools = {
  europe:list("albania|andora|austria|belgia|białoruś|bośnia i hercegowina|bułgaria|chorwacja|cypr|czarnogóra|czechy|dania|estonia|finlandia|francja|grecja|hiszpania|holandia|irlandia|islandia|kosowo|liechtenstein|litwa|luksemburg|łotwa|macedonia północna|malta|mołdawia|monako|niemcy|norwegia|polska|portugalia|rosja|rumunia|san marino|serbia|słowacja|słowenia|szwajcaria|szwecja|ukraina|watykan|węgry|wielka brytania|włochy"),
  asia:list("afganistan|arabia saudyjska|armenia|azerbejdżan|bahrajn|bangladesz|bhutan|brunei|chiny|filipiny|gruzja|indie|indonezja|irak|iran|izrael|japonia|jemen|jordania|kambodża|katar|kazachstan|kirgistan|korea południowa|korea północna|kuwejt|laos|liban|malezja|malediwy|mongolia|mjanma|nepal|oman|pakistan|palestyna|singapur|sri lanka|syria|tadżykistan|tajlandia|timor wschodni|turcja|turkmenistan|uzbekistan|wietnam|zjednoczone emiraty arabskie"),
  africa:list("algieria|angola|benin|botswana|burkina faso|burundi|czad|demokratyczna republika konga|dżibuti|egipt|erytrea|eswatini|etiopia|gabon|gambia|ghana|gwinea|gwinea bissau|gwinea równikowa|kamerun|kenia|komory|kongo|lesotho|liberia|libia|madagaskar|malawi|mali|maroko|mauretania|mauritius|mozambik|namibia|niger|nigeria|republika południowej afryki|republika środkowoafrykańska|republika zielonego przylądka|rwanda|senegal|seszele|sierra leone|somalia|sudan|sudan południowy|tanzania|togo|tunezja|uganda|wybrzeże kości słoniowej|wyspy świętego tomasza i książęca|zambia|zimbabwe"),
  usaStates:list("alabama|alaska|arizona|arkansas|kalifornia|kolorado|connecticut|delaware|floryda|georgia|hawaje|idaho|illinois|indiana|iowa|kansas|kentucky|luizjana|maine|maryland|massachusetts|michigan|minnesota|missisipi|missouri|montana|nebraska|nevada|new hampshire|new jersey|nowy meksyk|nowy jork|karolina północna|dakota północna|ohio|oklahoma|oregon|pensylwania|rhode island|karolina południowa|dakota południowa|tennessee|teksas|utah|vermont|wirginia|waszyngton|wirginia zachodnia|wisconsin|wyoming"),
  polishCities:list("warszawa|kraków|wrocław|łódź|poznań|gdańsk|szczecin|bydgoszcz|lublin|białystok|katowice|gdynia|częstochowa|radom|sosnowiec|toruń|kielce|rzeszów|gliwice|zabrze|olsztyn|bielsko-biała|bytom|zielona góra|rybnik|ruda śląska|opole|tychy|gorzów wielkopolski|elbląg|płock|wałbrzych|włocławek|tarnów|chorzów|koszalin|kalisz|legnica|grudziądz|słupsk|jaworzno|jastrzębie-zdrój|nowy sącz|jelenia góra|siedlce|konin|piła|inowrocław|lubin|ostrów wielkopolski|suwałki|głogów|gniezno|leszno|zamość|przemyśl|ełk|stalowa wola|tomaszów mazowiecki|chełm|mielec|bełchatów|świdnica|będzin|zgorzelec|zakopane|sopot|ustka|kołobrzeg|malbork|łeba|ustroń|wisła|krynica-zdrój|augustów|giżycko|mrągowo|ciechanów|ostrołęka|pruszków|legionowo|otwock|piaseczno|starachowice|skierniewice|racibórz|wejherowo|rumia|reda|kościerzyna|tczew|kwidzyn|iława|ostróda|sanok|krosno|jarosław|dębica|puławy|kraśnik"),
  kitchen:list("garnek|patelnia|rondel|czajnik|toster|mikser|blender|lodówka|zamrażarka|piekarnik|mikrofalówka|zmywarka|okap|płyta indukcyjna|kuchenka|ekspres do kawy|frytkownica|air fryer|multicooker|robot kuchenny|waga kuchenna|deska do krojenia|nóż|widelec|łyżka|łyżeczka|chochla|łopatka|trzepaczka|tarka|obieraczka|otwieracz|korkociąg|durszlak|sitko|miska|salaterka|kubek|szklanka|kieliszek|talerz|spodek|półmisek|dzbanek|butelka|termos|pojemnik|słoik|folia aluminiowa|papier do pieczenia|ręcznik papierowy|gąbka|płyn do naczyń|ściereczka|kosz na śmieci|młynek do pieprzu|solniczka|cukiernica|moździerz|wałek|foremka|blacha|naczynie żaroodporne|rękawica kuchenna|fartuch|zegar|timer|krajalnica|wyciskarka|sokowirówka|maszynka do mięsa|praska do czosnku|tłuczek|szczypce|pałeczki|łyżka cedzakowa|łyżka drewniana|szpatułka|miarka|kapsułka do zmywarki|zlew|kran|szafka|szuflada|stół|krzesło|taboret|chlebak|ociekacz|podkładka|serwetka|filiżanka|wok"),
  computerParts:list("procesor|cpu|karta graficzna|gpu|płyta główna|motherboard|ram|pamięć ram|dysk ssd|ssd|dysk hdd|hdd|zasilacz|psu|obudowa|wentylator|wiatrak|chłodzenie|radiator|chłodzenie wodne|aio|pasta termoprzewodząca|monitor|klawiatura|mysz|podkładka|słuchawki|mikrofon|głośniki|kamera|webcam|router|modem|karta sieciowa|karta dźwiękowa|bios|chipset|bateria bios|port usb|usb|hdmi|displayport|dvi|vga|ethernet|lan|wi-fi|wifi|bluetooth|kabel sata|sata|nvme|m.2|pcie|pci express|ram ddr4|ram ddr5|procesor intel|procesor amd|karta nvidia|karta amd|geforce|radeon|cooler|hub usb|kontroler|gamepad|joystick|drukarka|skaner|pendrive|dysk zewnętrzny|napęd dvd|cd-rom|stacja dyskietek|czytnik kart|karta pamięci|touchpad|ekran|matryca|zasilanie|ładowarka|kabel zasilający|listwa|ups|serwer|nas|switch|access point|wtyczka|przejściówka|adapter|dock|stacja dokująca|tablet graficzny|drukarka 3d|vr|gogle vr|smartwatch|telefon|laptop|notebook|komputer|pc|mini pc|raspberry pi|arduino"),
  colors:list("czerwony|niebieski|zielony|żółty|pomarańczowy|fioletowy|różowy|czarny|biały|szary|brązowy|beżowy|granatowy|bordowy|turkusowy|miętowy|oliwkowy|limonkowy|złoty|srebrny|miedziany|kremowy|łososiowy|koralowy|amarantowy|malinowy|purpurowy|lawendowy|liliowy|wrzosowy|indygo|błękitny|lazurowy|cyjan|morski|szmaragdowy|seledynowy|khaki|musztardowy|bursztynowy|morelowy|brzoskwiniowy|grafitowy|antracytowy|kość słoniowa|ecru|magenta|fuksja|czerwień|zieleń|błękit|sepia|ochra|karmazynowy|rubinowy|wiśniowy|ceglasty|piaskowy|czekoladowy|kawowy|waniliowy|neonowy zielony|neonowy różowy|pastelowy różowy|pastelowy niebieski|transparentny|przezroczysty"),
  restaurantChains:list("mcdonalds|mcdonald's|kfc|burger king|subway|starbucks|pizza hut|domino's pizza|dominos pizza|telepizza|da grasso|north fish|pasibus|max premium burgers|popeyes|taco bell|wendy's|five guys|hard rock cafe|costa coffee|green caffe nero|so coffee|grycan|lodomania|bubble tea|berlin döner kebap|salad story|sphinx|pijalnia czekolady wedel|manekin|thai wok|express oriental|bobby burger|mleczarnia jerozolimska|mr hamburger|chinkalnia|ramen people|sushi shop|sushi kushi|kuchnia marche|ikea food|orlen stop cafe|bp wild bean cafe|żabka cafe|cinnabon|dunkin donuts|krispy kreme|tim hortons|pret a manger|panda express|chipotle|little caesars|papa john's|arbys|dairy queen|sonic drive-in|in-n-out burger|chick-fil-a|shake shack|ihop|dunkin|dunkin'|wingstop|jollibee|nando's|cafe nero|boost juice|pizza express|vapiano|hardees|wawa|hooters"),
  carBrands:list("audi|bmw|mercedes|mercedes-benz|volkswagen|vw|toyota|honda|ford|ferrari|lamborghini|porsche|skoda|renault|volvo|opel|peugeot|citroen|fiat|seat|cupra|kia|hyundai|mazda|nissan|mitsubishi|subaru|suzuki|lexus|infiniti|acura|alfa romeo|aston martin|bentley|bugatti|buick|cadillac|chevrolet|chrysler|dacia|daewoo|dodge|ds automobiles|genesis|gmc|hummer|isuzu|jaguar|jeep|lada|land rover|lincoln|lotus|maserati|maybach|mclaren|mini|pagani|polestar|pontiac|ram|rolls-royce|saab|smart|ssangyong|tesla|vauxhall|rivian|lucid|byd|nio|geely|saic|mg|rover|tata|seat|scania|man|iveco|daf|fisker|koenigsegg|rimac|alpine|abarth|holden|proton|skoda auto|great wall|haval|chery|zeekr|xpeng|lancia"),
};

const supplementalFocusedPools = {
  europe:list("wyspy owcze|gibraltar|guernsey|jersey|wyspa man"),
  asia:list("hongkong|makau|tajwan"),
  africa:list("zanzibar|sahara zachodnia"),
  usaStates:list(""),
  polishCities:list("bochnia|brzeg|chojnice|dzierżoniów|głuchołazy|kędzierzyn-koźle|kłodzko|koło|kołobrzeg|kutno|lębork|łomża|mława|mysłowice|nysa|oświęcim|pabianice|polanica-zdrój|polkowice|sandomierz|sochaczew|swarzędz|świnoujście|tarnowskie góry|ustka|wadowice|wieliczka|września|zawiercie|żory|żywiec"),
  kitchen:list("garnek do gotowania na parze|parowar|opiekacz|gofrownica|krajalnica|mandolina kuchenna|wyciskarka do cytrusów|shaker|sitko barmańskie|miarka kuchenna|termometr kuchenny|timer kuchenny|otwieracz do puszek|deska bambusowa|mata silikonowa|papier śniadaniowy|woreczek strunowy|pojemnik na żywność|tacka|patera|łyżka wazowa|łyżka do makaronu|szczypce kuchenne|ubijaczka|tłuczek do ziemniaków|tłuczek do mięsa|szpikulec|obieraczka do warzyw|praska do ziemniaków|sitko do herbaty|zaparzacz|dzbanek filtrujący|filtr do wody|karafka|kubek termiczny|termos obiadowy|czajnik elektryczny|ekspres przelewowy|kawiarka|młynek do kawy|spieniacz do mleka|lodówka turystyczna|kostkarka|zamrażarka|płyta gazowa|płyta ceramiczna|płyta indukcyjna|palnik|ruszt|grill elektryczny|toster|sandwich maker|sous vide|wolnowar|szybkowar|air fryer|frytkownica|sokowirówka|blender kielichowy|blender ręczny|mikser planetarny|robot kuchenny|maszynka do makaronu|maszynka do mielenia|moździerz|sitko|durszlak|miska stalowa|salaterka|półmisek|filiżanka|spodek|kieliszek|szklanka|słoik|butelka|korek|zakrętka"),
  computerParts:list("karta przechwytująca|capture card|kontroler rgb|przewód zasilający|przewód hdmi|przewód displayport|kabel usb-c|kabel usb c|hub rgb|podpórka gpu|termopad|thermal pad|wentylator rgb|obudowa mini tower|obudowa mid tower|obudowa full tower|zatoka dysku|panel boczny|szkło hartowane|filtr przeciwkurzowy|śrubka|dystans płyty głównej|gniazdo procesora|socket|slot ram|gniazdo ram|port sata|port pcie|złącze m.2|złącze m2|złącze eps|złącze atx|złącze molex|przejściówka molex|kabel sata|kabel ethernet|karta wi-fi|karta wifi|antenka wi-fi|antenka wifi|bluetooth dongle|dongle usb|adapter bluetooth|czytnik kart sd|czytnik linii papilarnych|kamerka internetowa|ramię do mikrofonu|pop filtr|mikser audio|interfejs audio|dac|wzmacniacz słuchawkowy|podstawka pod laptopa|podkładka chłodząca|stacja dokująca|switch hdmi|przełącznik usb|ups|zasilacz awaryjny"),
  colors:list("akwamaryna|ametystowy|bananowy|brzoskwiniowy|butelkowa zieleń|ceglany|chabrowy|cytrynowy|denim|fiołkowy|gołębi|hebanowy|herbaciany|jagodowy|kanarkowy|karmelowy|kasztanowy|kobaltowy|lawendowy|mahoniowy|makowy|miodowy|neonowy niebieski|neonowy czerwony|neonowy żółty|neonowy pomarańczowy|neonowy fioletowy|pastelowy zielony|pastelowy żółty|pastelowy fioletowy|pastelowy pomarańczowy|pistacjowy|platynowy|rdzawy|śliwkowy|śnieżnobiały|stalowy|szafirowy|śliwkowy|trawiasty|węglowy|waniliowy|winny|zgaszony róż|zgniła zieleń"),
  restaurantChains:list("amrest|burgermeister|fat bob burger|mcdonald's|mcdonalds|kfc|burger king|subway|starbucks|popeyes|pizza hut|domino's|dominos|telepizza|da grasso|papa john's|taco bell|five guys|wendy's|shake shack|hardee's|carls jr|nando's|chipotle|panda express|dairy queen|chick-fil-a|little caesars|arbys|wingstop|ihop|costa coffee|cafe nero|coffeeheaven|green caffe nero|so coffee|grycan|lodomania|cinnabon|dunkin donuts|krispy kreme|tim hortons|pret a manger|boost juice|bubbleology|salad story|north fish|sphinx|thai wok|express oriental|vapiano|manekin|pasibus|bobby burger|max premium burgers|berlin döner kebap|kuchnia marche|ikea food|orlen stop cafe|bp wild bean cafe|żabka cafe"),
  carBrands:list("acura|aixam|alfa romeo|alpina|alpine|aston martin|audi|bentley|bmw|bugatti|buick|byd|cadillac|chevrolet|chrysler|citroen|cupra|dacia|daewoo|daihatsu|dodge|ds automobiles|ferrari|fiat|ford|genesis|geely|gmc|great wall|haval|holden|honda|hummer|hyundai|infiniti|isuzu|iveco|jaguar|jeep|kia|koenigsegg|lada|lamborghini|lancia|land rover|lexus|lincoln|lotus|lucid|maserati|maybach|mazda|mclaren|mercedes|mercedes-benz|mini|mitsubishi|nio|nissan|opel|pagani|peugeot|polestar|pontiac|porsche|proton|ram|renault|rimac|rivian|rolls-royce|rover|saab|seat|skoda|smart|ssangyong|subaru|suzuki|tata|tesla|toyota|vauxhall|vinfast|volkswagen|volvo|xpeng|zeekr"),
};
Object.entries(supplementalFocusedPools).forEach(([id,answers]) => {
  focusedPools[id] = unique([...(focusedPools[id] || []),...answers]);
});

export const mergeUnique = (...groups) => unique(groups.flat());
