const list = text => text.split("|").map(item => item.trim()).filter(Boolean);
const prompts = first => [first];

export const newCategoryPools = {
  jobs:list("aktor|aktorka|architekt|architektka|astronauta|barista|bibliotekarz|bibliotekarka|bloger|blogerka|budowlaniec|chemik|chirurg|cukiernik|cukierniczka|dekarz|dentysta|dentystka|detektyw|dietetyk|dietetyczka|dziennikarz|dziennikarka|elektryk|farmaceuta|farmaceutka|filmowiec|filozof|fizjoterapeuta|fotograf|fotografka|fryzjer|fryzjerka|geodeta|górnik|grafik|graficzka|hydraulik|informatyk|influencer|influencerka|inżynier|kelner|kelnerka|kierowca|kierowca autobusu|kierowca ciężarówki|kierowca rajdowy|księgowa|księgowy|kucharz|kucharka|kurier|lakiernik|lekarz|lekarka|listonosz|listonoszka|magazynier|malarz|marynarz|masażysta|masażystka|mechanik|meteorolog|model|modelka|monter|muzyk|muzyczka|nauczyciel|nauczycielka|notariusz|notariuszka|operator kamery|opiekun|opiekunka|ortodonta|ortodontka|piekarz|piekarka|pielęgniarka|pielęgniarz|pilot|pisarz|pisarka|piłkarz|piłkarka|policjant|policjantka|polityk|położna|prawnik|prawniczka|programista|programistka|projektant|projektantka|psycholog|psycholożka|ratownik|ratowniczka|recepcjonista|recepcjonistka|reżyser|reżyserka|rolnik|rolniczka|sanitariusz|sekretarka|sędzia|sprzedawca|sprzedawczyni|steward|stewardesa|strażak|strażaczka|stolarz|streamer|streamerka|szewc|taksówkarz|taksówkarka|technik|trener|trenerka|weterynarz|weterynarka|wizażysta|wizażystka|wokalista|wokalistka|wojskowy|youtuber|youtuberka|zegarmistrz|złotnik"),
  transport:list("samochód|auto|autobus|autokar|bus|mikrobus|taksówka|tramwaj|trolejbus|metro|pociąg|kolej|lokomotywa|wagon|pendolino|intercity|skm|pkp|rower|rower górski|rower miejski|rower elektryczny|hulajnoga|hulajnoga elektryczna|deskorolka|longboard|rolki|wrotki|motocykl|motor|skuter|motorower|quad|cross|chopper|ścigacz|samolot|odrzutowiec|awionetka|helikopter|śmigłowiec|szybowiec|balon|sterowiec|paralotnia|spadochron|rakieta|statek kosmiczny|prom kosmiczny|dron|statek|prom|łódź|motorówka|kajak|kanu|żaglówka|jacht|katamaran|tratwa|pontony|ponton|skuter wodny|okręt|łódź podwodna|gondola|wodolot|tanker|kontenerowiec|ciężarówka|tir|dostawczak|furgonetka|van|pickup|suv|kabriolet|limuzyna|sedan|kombi|hatchback|kamper|przyczepa kempingowa|karawan|radiowóz|ambulans|karetka|wóz strażacki|śmieciarka|koparka|spychacz|buldożer|traktor|kombajn|walec|dźwig|betoniarka|wózek widłowy|melex|gokart|bolid|formuła 1|monster truck|czołg|transporter opancerzony|skuter śnieżny|sanie|narty|snowboard|wyciąg narciarski|kolejka linowa|gondola górska|winda|schody ruchome|segway|monocykl|riksza|dorożka|powóz|bryczka|koń|osioł|wielbłąd|deskrolka elektryczna|hoverboard|jetpack"),
  clothes:list("koszulka|t-shirt|bluzka|koszula|polo|top|tank top|crop top|sweter|bluza|hoodie|kardigan|golf|marynarka|kamizelka|kurtka|kurtka jeansowa|kurtka skórzana|ramoneska|wiatrówka|parka|płaszcz|trencz|peleryna|ponczo|futro|spodnie|jeansy|dżinsy|dresy|legginsy|szorty|krótkie spodenki|bojówki|chinosy|spódnica|mini spódniczka|sukienka|kombinezon|garnitur|smoking|piżama|szlafrok|strój kąpielowy|kąpielówki|bikini|bielizna|majtki|bokserki|skarpetki|rajstopy|stanik|biustonosz|buty|trampki|adidasy|sneakersy|tenisówki|sandały|klapki|japonki|szpilki|botki|kozaki|kalosze|kapcie|mokasyny|glany|trapery|czapka|czapka z daszkiem|bejsbolówka|kapelusz|beret|kominiarka|chusta|szalik|apaszka|rękawiczki|mitenki|pasek|szelki|krawat|muszka|naszyjnik|łańcuszek|bransoletka|pierścionek|obrączka|kolczyki|zegarek|okulary|okulary przeciwsłoneczne|torebka|plecak|nerka|torba|walizka|portfel|parasol|spinka|gumka do włosów|opaska|diadem|korona|maska|kask|hełm|ochraniacze|mundur|mundurek|fartuch|kombinezon roboczy|dres|kimono|habit|sari|sombrero|bandana|komin|śniegowce|esparadryle|baleriny|pantofle|lakierki|buty trekkingowe|buty piłkarskie|korki"),
  nature:list("drzewo|krzew|trawa|kwiat|róża|tulipan|stokrotka|słonecznik|fiołek|orchidea|lilia|kaktus|paproć|mech|grzyb|las|dżungla|puszcza|łąka|pole|sad|ogród|park|góry|pagórek|wzgórze|szczyt|klif|skała|kamień|głaz|jaskinia|grota|wąwóz|dolina|pustynia|wydma|oaza|step|sawanna|tundra|tajga|bagno|mokradła|rzeka|strumień|potok|jezioro|staw|morze|ocean|zatoka|cieśnina|wodospad|źródło|plaża|wyspa|półwysep|archipelag|lodowiec|góra lodowa|wulkan|lawa|magma|ziemia|piasek|żwir|glina|błoto|śnieg|lód|deszcz|mżawka|ulewa|grad|rosa|szron|mgła|chmura|burza|piorun|błyskawica|grzmot|wiatr|wichura|huragan|tornado|tęcza|słońce|księżyc|gwiazda|niebo|zmierzch|świt|zachód słońca|wschód słońca|fala|przypływ|odpływ|rafa koralowa|koralowiec|muszla|szyszka|żołądź|kasztan|liść|gałąź|korzeń|pień|kora|igły|nasienie|owoc|warzywo|zioło|koniczyna|bluszcz|bambus|palma|brzoza|dąb|sosna|świerk|jodła|klon|wierzba|topola|buk|modrzew|sekwoja"),
  hobbies:list("czytanie|książki|rysowanie|malowanie|szkicowanie|fotografia|robienie zdjęć|filmowanie|montaż filmów|gotowanie|pieczenie|grillowanie|podróżowanie|zwiedzanie|bieganie|jogging|spacerowanie|trekking|wędrówki|wspinaczka|jazda na rowerze|rolki|wrotki|deskorolka|snowboard|narty|łyżwy|pływanie|nurkowanie|surfing|kajakarstwo|żeglarstwo|wędkarstwo|piłka nożna|koszykówka|siatkówka|tenis|badminton|ping pong|tenis stołowy|szachy|warcaby|gry planszowe|planszówki|gry karciane|karty|puzzle|krzyżówki|sudoku|gaming|granie|gry komputerowe|streamowanie|oglądanie filmów|seriale|anime|słuchanie muzyki|śpiewanie|karaoke|gitara|pianino|perkusja|taniec|breakdance|balet|zumba|fitness|siłownia|crossfit|joga|medytacja|modelarstwo|lego|kolekcjonowanie|monety|znaczki|karty pokemon|karty piłkarskie|ogrodnictwo|rośliny|szydełkowanie|robienie na drutach|szycie|haftowanie|majsterkowanie|stolarstwo|druk 3d|programowanie|kodowanie|tworzenie stron|grafika komputerowa|cosplay|makijaż|moda|fryzjerstwo|ceramika|lepienie z gliny|origami|kaligrafia|pisanie|opowiadania|poezja|blogowanie|vlogowanie|podcast|astronomia|obserwacja gwiazd|historia|geografia|nauka języków|nauka angielskiego|quizy|escape roomy|paintball|airsoft|kemping|biwak|piknik|zbieranie grzybów|spacery z psem|jazda konna|motoryzacja|tuning|gokarty|gotowanie azjatyckie|robienie deserów|baristyka|miksologia|wolontariat"),
  drinks:list("woda|woda gazowana|woda niegazowana|woda mineralna|woda smakowa|kranówka|lemoniada|oranżada|cola|coca-cola|pepsi|sprite|fanta|mirinda|7up|tonik|ginger ale|root beer|ice tea|mrożona herbata|herbata|czarna herbata|zielona herbata|biała herbata|herbata owocowa|herbata z cytryną|earl grey|matcha|yerba mate|kawa|espresso|americano|cappuccino|latte|caffe latte|flat white|macchiato|mocha|frappe|kawa mrożona|kakao|gorąca czekolada|mleko|mleko czekoladowe|mleko roślinne|mleko owsiane|mleko migdałowe|kefir|maślanka|jogurt pitny|koktajl|smoothie|shake|milkshake|sok|sok pomarańczowy|sok jabłkowy|sok grejpfrutowy|sok ananasowy|sok pomidorowy|sok marchwiowy|multiwitamina|nektar|kompot|kisiel pitny|napój energetyczny|energetyk|red bull|monster|black|burn|izotonik|napój izotoniczny|gatorade|powerade|woda kokosowa|kwas chlebowy|kombucha|bubble tea|boba tea|piwo|piwo bezalkoholowe|lager|ipa|porter|cydr|wino|czerwone wino|białe wino|różowe wino|prosecco|szampan|wódka|whisky|whiskey|rum|gin|tequila|brandy|koniak|likier|nalewka|bimber|drinki|drink|mojito|aperol spritz|sex on the beach|piña colada|pina colada|margarita|martini|bloody mary|long island|cosmopolitan|caipirinha|daiquiri|gin z tonikiem|rum z colą|grzane wino|grzaniec|poncz"),
  body:list("głowa|włosy|czoło|skroń|brew|brwi|rzęsy|oko|oczy|powieka|ucho|uszy|nos|nozdrza|policzek|usta|wargi|ząb|zęby|język|dziąsło|podniebienie|broda|szczęka|twarz|szyja|gardło|kark|ramię|bark|pacha|łokieć|przedramię|nadgarstek|dłoń|ręka|palec|kciuk|paznokieć|klatka piersiowa|pierś|plecy|kręgosłup|żebra|brzuch|pępek|biodro|talia|miednica|pośladek|udo|kolano|rzepka|łydka|kostka|pięta|stopa|palec u nogi|skóra|kość|staw|mięsień|ścięgno|więzadło|serce|mózg|płuca|wątroba|nerka|nerki|żołądek|jelito|jelita|jelito cienkie|jelito grube|trzustka|śledziona|pęcherz|krew|żyła|tętnica|naczynie krwionośne|nerw|rdzeń kręgowy|przepona|krtań|tchawica|oskrzela|przełyk|wyrostek robaczkowy|migdałki|szpik kostny|czaszka|żuchwa|obojczyk|łopatka|mostek|kręg|kość udowa|piszczel|strzałka|mózgoczaszka|miednica|rzepka|pięta|biceps|triceps|mięśnie brzucha|abs|czworogłowy uda|pośladki|węzły chłonne|tarczyca|hormony|ślina|łzy|pot|odcisk palca|linie papilarne|źrenica|tęczówka|siatkówka|rogówka|błona bębenkowa"),
  travel:list("polska|niemcy|francja|hiszpania|włochy|grecja|chorwacja|portugalia|turcja|egipt|tunezja|maroko|japonia|chiny|tajlandia|wietnam|indonezja|bali|malediwy|seszele|dubaj|zjednoczone emiraty arabskie|usa|stany zjednoczone|kanada|meksyk|brazylia|argentyna|australia|nowa zelandia|islandia|norwegia|szwecja|finlandia|dania|holandia|belgia|szwajcaria|austria|czechy|słowacja|węgry|rumunia|bułgaria|gruzja|warszawa|kraków|gdańsk|wrocław|zakopane|sopot|kołobrzeg|mazury|tatry|bieszczady|bałtyk|londyn|paryż|rzym|wenecja|mediolan|barcelona|madryt|lizbona|porto|berlin|praga|wiedeń|budapeszt|ateny|stambuł|amsterdam|bruksela|oslo|sztokholm|helsinki|kopenhaga|dublin|edynburg|reykjavik|tokio|kioto|osaka|seul|pekin|szanghaj|bangkok|singapur|kuala lumpur|dżakarta|delhi|mumbaj|dubaj|abu zabi|doha|kair|aleksandria|marakesz|casablanca|nowy jork|los angeles|chicago|miami|las vegas|san francisco|hawaje|floryda|kalifornia|toronto|vancouver|rio de janeiro|buenos aires|sydney|melbourne|auckland|hotel|hostel|apartament|camping|kemping|namiot|kamper|walizka|plecak|paszport|dowód osobisty|bilet|rezerwacja|mapa|przewodnik|lotnisko|samolot|pociąg|autobus|statek|prom|wycieczka|wakacje|urlop|plaża|góry|morze|jezioro|ocean|zwiedzanie|muzeum|zabytek|zamek|pałac|starówka|restauracja|pamiątka|pocztówka|wyjazd"),
};

export const newCategoryPrompts = {
  jobs:prompts("Wymień zawody","Wymień popularne zawody","Wymień profesje, które kojarzysz","Wymień zawody wykonywane przez ludzi","Wymień zawody spotykane na co dzień","Wymień zawody wymagające różnych umiejętności","Wymień zawody biurowe, fizyczne albo kreatywne","Wymień zawody znane z życia lub filmów","Wymień osoby pracujące w różnych branżach","Wymień zawody, o których słyszałeś","Wymień profesje stare lub nowoczesne","Wymień dowolne zawody"),
  transport:prompts("Wymień środki transportu","Wymień pojazdy lub inne sposoby przemieszczania się","Wymień rzeczy, którymi można się przemieszczać","Wymień środki transportu lądowego, wodnego albo powietrznego","Wymień środki komunikacji lub pojazdy","Wymień pojazdy i inne rzeczy związane z transportem","Wymień środki transportu małe lub duże","Wymień sposoby przemieszczania się w mieście albo poza nim","Wymień rzeczy służące do podróżowania","Wymień środki transportu znane z życia lub filmów","Wymień nietypowe środki transportu","Wymień dowolne środki transportu"),
  clothes:prompts("Wymień ubrania lub dodatki","Wymień ubrania, akcesoria albo dodatki","Wymień części garderoby lub akcesoria","Wymień ubrania i dodatki na różne pory roku","Wymień ubrania, buty albo dodatki","Wymień rzeczy spotykane w szafie lub garderobie","Wymień ubrania codzienne, eleganckie albo dodatki","Wymień elementy stroju lub akcesoria","Wymień akcesoria modowe, ubrania albo dodatki","Wymień ubrania i dodatki dla dowolnej osoby","Wymień rzeczy związane z ubiorem lub garderobą","Wymień dowolne ubrania i dodatki"),
  nature:prompts("Wymień rzeczy związane z naturą","Wymień elementy przyrody","Wymień miejsca, rośliny lub zjawiska naturalne","Wymień miejsca lub zjawiska naturalne","Wymień rzeczy kojarzące się z przyrodą","Wymień elementy natury lub krajobrazu","Wymień rośliny, miejsca lub zjawiska naturalne","Wymień rzeczy powstałe naturalnie","Wymień rzeczy kojarzące się z naturą na Ziemi lub w kosmosie","Wymień zjawiska, miejsca albo rośliny","Wymień rzeczy kojarzące się z naturą i planetą Ziemią","Wymień dowolne elementy natury"),
  hobbies:prompts("Wymień hobby","Wymień zainteresowania","Wymień rzeczy robione w wolnym czasie","Wymień popularne sposoby spędzania czasu","Wymień hobby dla jednej osoby albo grupy","Wymień aktywności, które mogą być pasją","Wymień kreatywne lub sportowe hobby","Wymień rzeczy, których ludzie uczą się dla przyjemności","Wymień zajęcia na spokojny albo aktywny wieczór","Wymień zainteresowania znane wśród znajomych","Wymień hobby w domu lub poza domem","Wymień dowolne hobby"),
  drinks:prompts("Wymień napoje","Wymień rzeczy do picia","Wymień napoje zimne albo gorące","Wymień napoje spotykane w sklepie lub kawiarni","Wymień soki, kawy, herbaty albo inne napoje","Wymień napoje bezalkoholowe lub alkoholowe","Wymień popularne napoje","Wymień napoje na imprezę albo spokojny wieczór","Wymień rzeczy, które można zamówić do picia","Wymień napoje, które kojarzysz","Wymień drinki lub zwykłe napoje","Wymień dowolne napoje"),
  body:prompts("Wymień części ciała lub elementy ludzkiego organizmu","Wymień rzeczy związane z ludzkim ciałem","Wymień części ciała widoczne lub wewnętrzne","Wymień narządy, kości albo części ciała","Wymień elementy ludzkiego organizmu","Wymień części ciała i inne elementy anatomii człowieka","Wymień narządy, kończyny lub inne elementy organizmu","Wymień rzeczy kojarzone z anatomią człowieka","Wymień części ciała albo inne elementy organizmu","Wymień elementy ludzkiego ciała","Wymień zewnętrzne albo wewnętrzne części ciała","Wymień dowolne elementy ludzkiego organizmu"),
  travel:prompts("Wymień rzeczy związane z podróżowaniem","Wymień miejsca lub rzeczy kojarzące się z wakacjami","Wymień miejsca albo rzeczy związane z podróżami","Wymień miejsca, przedmioty lub pojęcia przydatne podczas wyjazdu","Wymień kraje, miasta, miejsca albo rzeczy kojarzone z podróżami","Wymień rzeczy spotykane podczas podróży","Wymień wakacyjne kierunki lub przedmioty","Wymień rzeczy związane z urlopem","Wymień miejsca albo rzeczy związane z krótkim lub długim wyjazdem","Wymień rzeczy kojarzące się ze zwiedzaniem","Wymień sposoby, miejsca lub rzeczy związane z podróżowaniem","Wymień dowolne rzeczy związane z podróżami"),
};

export const newCategoryDefinitions = [
  ["jobs","Zawody"],["transport","Transport"],["clothes","Ubrania i dodatki"],["nature","Natura"],
  ["hobbies","Hobby"],["drinks","Napoje"],["body","Ciało człowieka"],["travel","Podróże"],
];
