const list = text => text.split("|").map(item => item.trim()).filter(Boolean);
const task = (id, prompt, answers) => [id, prompt, list(answers)];

// Konkretne pytania z osobnymi pulami. Szerokie pytanie bazowe dla każdej
// kategorii nadal powstaje w categories.js.
export const specificTasks = {
  animals:[
    task("animals_large","Wymień duże zwierzęta","słoń|żyrafa|nosorożec|hipopotam|wieloryb|orka|rekin|niedźwiedź|niedźwiedź polarny|lew|tygrys|gepard|pantera|jaguar|puma|goryl|orangutan|szympans|koń|krowa|żubr|łoś|jeleń|dzik|wielbłąd|lama|alpaka|kangur|krokodyl|aligator|waran|struś|emu|pelikan|flaming|foka|mors|słoń morski|manat|delfin|tuńczyk|marlin|manta|ośmiornica|kałamarnica|pyton|anakonda|zebra|bawół|antylopa|renifer|osioł|muł|hiena|wilk"),
    task("animals_small","Wymień małe zwierzęta","mysz|szczur|chomik|świnka morska|koszatniczka|myszoskoczek|wiewiórka|jeż|kret|ryjówka|łasica|fretka|królik|zając|nietoperz|żaba|ropucha|traszka|jaszczurka|gekko|kameleon|rybka|gupik|danio|neon|biedronka|mrówka|pszczoła|osa|trzmiel|motyl|ćma|komar|mucha|ważka|chrząszcz|konik polny|świerszcz|karaluch|modliszka|patyczak|pająk|skorpion|kleszcz|ślimak|dżdżownica|stonoga|krab|krewetka|wróbel|sikorka|koliber|kanarek|papużka falista"),
    task("animals_water","Wymień zwierzęta wodne","rekin|delfin|wieloryb|orka|foka|mors|słoń morski|manat|wydra morska|ośmiornica|kałamarnica|meduza|krab|homar|krewetka|langusta|rozgwiazda|konik morski|manta|płaszczka|węgorz|tuńczyk|łosoś|dorsz|śledź|makrela|karp|szczupak|sum|okoń|pstrąg|sandacz|pirania|błazenek|miecznik|marlin|murena|żółw morski|krokodyl|aligator|pingwin|pelikan|mewa|bóbr|wydra|żaba|ropucha|aksolotl|gupik|bocja|danio"),
    task("animals_birds","Wymień ptaki","orzeł|sokół|jastrząb|sowa|puchacz|wróbel|sikorka|gołąb|kruk|wrona|kawka|gawron|sroka|bocian|czapla|żuraw|mewa|pelikan|flaming|papuga|ara|kakadu|kanarek|koliber|dzięcioł|kukułka|jaskółka|jerzyk|drozd|gil|bażant|paw|kura|kogut|kaczka|gęś|indyk|przepiórka|struś|emu|pingwin|albatros|tukan|sęp|bielik|łabędź|nandu|rybitwa"),
    task("animals_farm","Wymień zwierzęta gospodarskie lub domowe","pies|kot|koń|kucyk|krowa|byk|cielak|świnia|prosiak|owca|baran|jagnię|koza|kura|kogut|kurczak|kaczka|gęś|indyk|królik|chomik|świnka morska|fretka|papuga|kanarek|rybka|żółw|jaszczurka|alpaka|lama|osioł"),
    task("animals_insects","Wymień owady lub pajęczaki","mrówka|pszczoła|osa|szerszeń|trzmiel|motyl|ćma|komar|mucha|meszka|ważka|biedronka|chrząszcz|żuk|stonka|konik polny|świerszcz|karaluch|modliszka|patyczak|pchła|wesz|pluskwa|termita|szarańcza|skorek|pająk|tarantula|skorpion|kleszcz|roztocz|kosarz"),
  ],
  fruits:[
    task("fruits_citrus","Wymień cytrusy","pomarańcza|mandarynka|cytryna|limonka|grejpfrut|pomelo|klementynka|kumkwat|bergamotka|cytron|tangelo|ugli|limonka kaffir|limonka perska|pomarańcza sewilska|pomarańcza valencia|pomarańcza navel"),
    task("fruits_berries","Wymień owoce jagodowe lub leśne","truskawka|malina|borówka|jagoda|jeżyna|porzeczka|agrest|żurawina|poziomka|aronia|morwa|malina żółta|czarna malina|malina moroszka|jagoda acai|jagoda maqui|jagoda haskap|boysenberry|josta|poziomka leśna|truskawka biała"),
    task("fruits_exotic","Wymień egzotyczne owoce","ananas|mango|papaja|kokos|awokado|marakuja|liczi|pitaja|smoczy owoc|durian|rambutan|karambola|gujawa|jackfruit|chlebowiec|persymona|kaki|kumkwat|opuncja|tamarillo|acerola|granadilla|cherimoya|noni|pepino|ręka buddy|ambarella|bilimbi|bael|mamey"),
    task("fruits_orchard","Wymień owoce rosnące w sadzie","jabłko|gruszka|śliwka|wiśnia|czereśnia|morela|brzoskwinia|nektarynka|mirabelka|renkloda|pigwa|jabłko gala|jabłko golden|jabłko granny smith|jabłko fuji|jabłko idared|jabłko lobo|śliwka japońska|śliwka kalifornijska"),
  ],
  school:[
    task("school_subjects","Wymień przedmioty szkolne","matematyka|język polski|polski|angielski|język angielski|niemiecki|język niemiecki|hiszpański|język hiszpański|francuski|język francuski|historia|geografia|biologia|chemia|fizyka|informatyka|wos|wiedza o społeczeństwie|edb|edukacja dla bezpieczeństwa|wf|wychowanie fizyczne|religia|etyka|plastyka|muzyka|technika|przyroda|podstawy przedsiębiorczości|biznes i zarządzanie|filozofia|łacina"),
    task("school_supplies","Wymień przybory szkolne","zeszyt|podręcznik|ćwiczenia|długopis|pióro|ołówek|gumka|temperówka|linijka|ekierka|kątomierz|cyrkiel|plecak|piórnik|marker|zakreślacz|kredka|mazak|farby|pędzel|blok rysunkowy|brystol|kolorowy papier|nożyczki|klej|taśma|korektor|teczka|segregator|spinacz|zszywacz|kalkulator|kompas|papier milimetrowy|zeszyt w kratkę|zeszyt w linie"),
    task("school_places","Wymień miejsca, które można znaleźć w szkole","sala lekcyjna|klasa|korytarz|szatnia|biblioteka|stołówka|sekretariat|gabinet dyrektora|pokój nauczycielski|sala gimnastyczna|boisko|toaleta|pracownia komputerowa|pracownia chemiczna|świetlica|aula|hala sportowa|basen|parking|plac zabaw|sklepik szkolny|portiernia|schody|winda|piwnica|magazyn|laboratorium"),
    task("chemical_elements","Wymień pierwiastki chemiczne","wodór|hel|lit|beryl|bor|węgiel|azot|tlen|fluor|neon|sód|magnez|glin|krzem|fosfor|siarka|chlor|argon|potas|wapń|skand|tytan|wanad|chrom|mangan|żelazo|kobalt|nikiel|miedź|cynk|gal|german|arsen|selen|brom|krypton|rubid|stront|itr|cyrkon|niob|molibden|technet|ruten|rod|pallad|srebro|kadm|ind|cyna|antymon|tellur|jod|ksenon|cez|bar|lantan|cer|prazeodym|neodym|promet|samar|europ|gadolin|terb|dysproz|holm|erb|tul|iterb|lutet|hafn|tantal|wolfram|ren|osm|iryd|platyna|złoto|rtęć|tal|ołów|bizmut|polon|astat|radon|frans|rad|aktyn|tor|protaktyn|uran|neptun|pluton|ameryk|kiur|berkel|kaliforn|einstein|ferm|mendelew|nobel|lorens|rutherford|dubn|seaborg|bohr|has|meitner|darmsztadt|rentgen|kopernik|nihon|flerow|moskow|liwermor|tenes|oganeson"),
  ],
  pokemon:[
    task("pokemon_starters","Wymień Pokémony starterowe lub ich ewolucje","bulbasaur|ivysaur|venusaur|charmander|charmeleon|charizard|squirtle|wartortle|blastoise|chikorita|bayleef|meganium|cyndaquil|quilava|typhlosion|totodile|croconaw|feraligatr|treecko|grovyle|sceptile|torchic|combusken|blaziken|mudkip|marshtomp|swampert|turtwig|grotle|torterra|chimchar|monferno|infernape|piplup|prinplup|empoleon|snivy|servine|serperior|tepig|pignite|emboar|oshawott|dewott|samurott|chespin|quilladin|chesnaught|fennekin|braixen|delphox|froakie|frogadier|greninja|rowlet|dartrix|decidueye|litten|torracat|incineroar|popplio|brionne|primarina|grookey|thwackey|rillaboom|scorbunny|raboot|cinderace|sobble|drizzile|inteleon|sprigatito|floragato|meowscarada|fuecoco|crocalor|skeledirge|quaxly|quaxwell|quaquaval"),
    task("pokemon_legendary","Wymień legendarne lub mityczne Pokémony","articuno|zapdos|moltres|mewtwo|mew|raikou|entei|suicune|lugia|ho-oh|celebi|regirock|regice|registeel|latias|latios|kyogre|groudon|rayquaza|jirachi|deoxys|uxie|mesprit|azelf|dialga|palkia|heatran|regigigas|giratina|cresselia|phione|manaphy|darkrai|shaymin|arceus|victini|cobalion|terrakion|virizion|tornadus|thundurus|reshiram|zekrom|landorus|kyurem|keldeo|meloetta|genesect|xerneas|yveltal|zygarde|diancie|hoopa|volcanion|tapu-koko|tapu-lele|tapu-bulu|tapu-fini|cosmog|cosmoem|solgaleo|lunala|necrozma|magearna|marshadow|zeraora|meltan|melmetal|zacian|zamazenta|eternatus|kubfu|urshifu|zarude|regieleki|regidrago|glastrier|spectrier|calyrex|enamorus|wo-chien|chien-pao|ting-lu|chi-yu|koraidon|miraidon|walking-wake|iron-leaves|ogerpon|terapagos|pecharunt"),
    task("pokemon_gen1","Wymień Pokémony z pierwszej generacji","bulbasaur|ivysaur|venusaur|charmander|charmeleon|charizard|squirtle|wartortle|blastoise|caterpie|metapod|butterfree|weedle|kakuna|beedrill|pidgey|pidgeotto|pidgeot|rattata|raticate|spearow|fearow|ekans|arbok|pikachu|raichu|sandshrew|sandslash|nidoran|nidorina|nidoqueen|nidorino|nidoking|clefairy|clefable|vulpix|ninetales|jigglypuff|wigglytuff|zubat|golbat|oddish|gloom|vileplume|paras|parasect|venonat|venomoth|diglett|dugtrio|meowth|persian|psyduck|golduck|mankey|primeape|growlithe|arcanine|poliwag|poliwhirl|poliwrath|abra|kadabra|alakazam|machop|machoke|machamp|bellsprout|weepinbell|victreebel|tentacool|tentacruel|geodude|graveler|golem|ponyta|rapidash|slowpoke|slowbro|magnemite|magneton|farfetchd|doduo|dodrio|seel|dewgong|grimer|muk|shellder|cloyster|gastly|haunter|gengar|onix|drowzee|hypno|krabby|kingler|voltorb|electrode|exeggcute|exeggutor|cubone|marowak|hitmonlee|hitmonchan|lickitung|koffing|weezing|rhyhorn|rhydon|chansey|tangela|kangaskhan|horsea|seadra|goldeen|seaking|staryu|starmie|mr-mime|scyther|jynx|electabuzz|magmar|pinsir|tauros|magikarp|gyarados|lapras|ditto|eevee|vaporeon|jolteon|flareon|porygon|omanyte|omastar|kabuto|kabutops|aerodactyl|snorlax|articuno|zapdos|moltres|dratini|dragonair|dragonite|mewtwo|mew"),
    task("pokemon_eevee","Wymień ewolucje Eevee","vaporeon|jolteon|flareon|espeon|umbreon|leafeon|glaceon|sylveon"),
  ],
  minecraft:[
    task("minecraft_mobs","Wymień moby z Minecrafta","creeper|zombie|szkielet|pająk|enderman|wiedźma|slime|ghast|blaze|piglin|hoglin|warden|wieśniak|żelazny golem|bałwan|owca|krowa|świnia|kurczak|wilk|kot|koń|lama|pszczoła|lis|żaba|aksolotl|delfin|guardian|elder guardian|shulker|phantom|drowned|pillager|evoker|ravager|endermite|silverfish|magma cube|wither skeleton|zombified piglin|breeze|bogged|camel|sniffer|allay|goat|panda|polar bear|parrot|rabbit|ocelot|strider|zoglin|vex|vindicator|wandering trader|trader llama|mooshroom|ender dragon|wither"),
    task("minecraft_blocks","Wymień bloki lub surowce z Minecrafta","ziemia|trawa|kamień|bruk|drewno|deski|szkło|piasek|żwir|obsydian|bedrock|diament|węgiel|żelazo|złoto|redstone|lapis|szmaragd|netherrack|soul sand|end stone|wełna|glina|cegły|beton|terakota|miedź|deepslate|sculk|calcite|tuff|bazalt|blackstone|glowstone|kwarc|prismarine|sea lantern|copper bulb|bamboo block|mud|packed mud|mud bricks"),
    task("minecraft_items","Wymień przedmioty z Minecrafta","kilof|miecz|łopata|siekiera|motyka|łuk|kusza|tarcza|wiadro|wędka|pochodnia|kompas|mapa|łóżko|elitra|totem|perła endermana|oko endera|mikstura|trójząb|mace|maczuga|brush|pędzel|bundle|spyglass|luneta|goat horn|kozi róg|recovery compass|clock|zegar|book|książka|enchanted book|zaklęta książka|shears|nożyce|flint and steel|krzesiwo"),
    task("minecraft_structures","Wymień struktury lub miejsca z Minecrafta","village|wioska|ancient city|bastion|bastion remnant|desert temple|dżunglowa świątynia|jungle temple|leśna posiadłość|woodland mansion|nether fortress|ocean monument|ocean ruins|pillager outpost|ruined portal|shipwreck|stronghold|trial chambers|witch hut|igloo|mineshaft|kopalnia|end city|jaskinia|amethyst geode|nether|end|overworld"),
  ],
  food:[
    task("food_polish","Wymień polskie potrawy","pierogi|rosół|pomidorowa|schabowy|gołąbki|bigos|żurek|barszcz|ogórkowa|krupnik|kotlet mielony|kotlet de volaille|kopytka|placki ziemniaczane|naleśniki|kluski śląskie|racuchy|fasolka po bretońsku|kapuśniak|chłodnik|zupa grzybowa|zupa szczawiowa|zupa jarzynowa|flaki|kaszanka|kiełbasa|oscypek|mizeria|sałatka jarzynowa|makowiec|sernik|szarlotka|pączek|drożdżówka|kremówka"),
    task("food_fast","Wymień fast foody","pizza|kebab|burger|hamburger|frytki|hot dog|zapiekanka|tortilla|tacos|burrito|nachos|nuggetsy|skrzydełka|hot wings|kebab rollo|doner kebab|cheeseburger|wrap|panini|frytki belgijskie|pizza pepperoni|pulled pork|fish and chips"),
    task("food_sweets","Wymień słodycze lub desery","lody|czekolada|sernik|szarlotka|pączek|drożdżówka|gofry|budyń|galaretka|popcorn|baton|ciastko|babeczka|beza|tort|kremówka|chałwa|cheesecake|churros|cynamonka|mochi|marcepan|pancakes|tarta|tort bezowy|cukierek|lizak|żelki|ptasie mleczko|piernik|makowiec"),
  ],
  tech:[
    task("tech_devices","Wymień urządzenia elektroniczne","komputer|laptop|telefon|smartfon|tablet|monitor|klawiatura|mysz|słuchawki|mikrofon|głośnik|kamera|drukarka|router|modem|konsola|playstation|xbox|nintendo switch|steam deck|powerbank|ładowarka|pendrive|smartwatch|telewizor|projektor|dron|robot|drukarka 3d|czytnik ebooków|kindle|radio|odtwarzacz mp3|aparat|kamera sportowa"),
    task("tech_systems","Wymień systemy operacyjne, języki lub programy","windows|linux|android|ios|macos|ubuntu|chrome os|html|css|javascript|typescript|python|php|sql|c++|java|visual studio code|vscode|excel|powerpoint|word|office|photoshop|docker|wordpress|unity|unreal engine|firefox|google chrome|safari|obs|notion|slack"),
  ],
  creators:[
    task("creators_polish","Wymień polskich youtuberów lub streamerów","friz|rezi|rezigiusz|blowek|stuu|gimper|izak|izakooo|poczciwy krzychu|mandzio|disowskyy|dealereq|tromba|wersow|mortalcio|karol paciorek|naruciak|wardęga|boxdel|multi|young multi|nitro|rembol|vertez|skkf|eleven|mietczynski|kacper porębski|rojson|remek|kamerzysta|marcin dubiel|mini majk|natsu|fagata|genzie|ekipa|rafonix|kasix|pago|xayoo|ewron|pasha|saju|kubon|wojan|palion|doknes|enzzi|eniuu|yoshi|gilathissnew|fairout|safemodtv|kaluch|noobek|tivolt|kiszak|isamu|lachu|sitrox|czuux|sheo|karolek|rock alone|vito minecraft|przemek best games|matura to bzdura|historia bez cenzury|naukowy bełkot|scifun|tvgry|nrgeek|quaz"),
    task("creators_world","Wymień zagranicznych youtuberów lub streamerów","mrbeast|pewdiepie|markiplier|jacksepticeye|ishowspeed|kai cenat|dream|georgenotfound|tommyinnit|dantdm|preston|lazarbeam|ninja|pokimane|xqc|ksi|logan paul|jake paul|sidemen|technoblade|aphmau|sssniperwolf|sapnap|tubbo|ranboo|stampy|captainsparklez|caseoh|adin ross|asmongold|ludwig|moistcr1tikal|sykkuno|quackity|dude perfect|ryan trahan|mark rober|linus tech tips|mkbhd|mrwhosetheboss|flamingo|kreekcraft|unspeakable|grian|mumbo jumbo|xisumavoid|goodtimeswithscar"),
  ],
  internet:[
    task("internet_social","Wymień serwisy społecznościowe lub komunikatory","facebook|instagram|tiktok|youtube|discord|messenger|whatsapp|snapchat|reddit|twitch|x|twitter|telegram|pinterest|linkedin|threads|signal|bereal|tumblr|wykop|gadu-gadu|gg|teamspeak|skype|meet|google meet|zoom|teams|facetime"),
    task("internet_shopping","Wymień sklepy internetowe lub aplikacje zakupowe","allegro|olx|amazon|temu|shein|vinted|ebay|etsy|zalando|aliexpress|booking|airbnb|pyszne|glovo|uber eats|paypal|revolut|shopify|groupon|facebook marketplace"),
  ],
  brands:[
    task("brands_clothing","Wymień marki odzieżowe lub obuwnicze","nike|adidas|puma|reebok|new balance|vans|converse|zara|h&m|reserved|cropp|house|bershka|pull&bear|stradivarius|uniqlo|calzedonia|intimissimi|victoria's secret|under armour|the north face|columbia|patagonia|timberland|dr martens|crocs|birkenstock|skechers|asics|mizuno|umbro|fila|champion|supreme|off-white|carhartt|lacoste|gucci|dior|chanel|versace"),
    task("brands_tech","Wymień marki technologiczne","apple|samsung|xiaomi|sony|lg|lenovo|asus|acer|hp|dell|huawei|motorola|nokia|microsoft|google|intel|amd|nvidia|razer|logitech|corsair|steelseries|hyperx|msi|gigabyte|jbl|bose|marshall|anker|garmin|gopro|canon|nikon|fujifilm|adobe"),
  ],
  cities:[
    task("cities_capitals","Wymień stolice państw","warszawa|berlin|paryż|madryt|lizbona|rzym|praga|wiedeń|bratysława|budapeszt|bukareszt|sofia|ateny|belgrad|zagrzeb|sarajewo|podgorica|tirana|skopje|lublana|kijów|wilno|ryga|tallinn|helsinki|sztokholm|oslo|kopenhaga|reykjavik|dublin|londyn|moskwa|ankara|waszyngton|ottawa|meksyk|hawana|panama|lima|quito|caracas|santiago|buenos aires|montevideo|brasilia|tokio|seul|pekin|bangkok|hanoi|singapur|kuala lumpur|dżakarta|delhi|islamabad|katmandu|abu zabi|doha|rijad|amman|bejrut|teheran|bagdad|kair|tunis|algier|dakar|akra|abuja|nairobi|addis abeba|pretoria|canberra|wellington"),
  ],
  sport:[
    task("sport_disciplines","Wymień dyscypliny sportowe","piłka nożna|koszykówka|siatkówka|tenis|pływanie|bieganie|lekkoatletyka|skoki narciarskie|narciarstwo|snowboard|boks|mma|judo|karate|gimnastyka|hokej|golf|rugby|kolarstwo|wspinaczka|surfing|badminton|tenis stołowy|ping pong|piłka ręczna|baseball|futbol amerykański|krykiet|szachy|esport|łyżwiarstwo|kajakarstwo|wioślarstwo|żeglarstwo|triathlon|maraton|formuła 1|rajdy|motocross|skateboarding|jazda konna|strzelectwo|łucznictwo|szermierka|zapasy|kickboxing|taekwondo|curling|biathlon|parkour|squash|dart|bilard|padel"),
    task("sport_clubs","Wymień kluby piłkarskie","real madryt|barcelona|arsenal|chelsea|liverpool|manchester city|manchester united|juventus|inter mediolan|ac milan|bayern monachium|psg|legia warszawa|lech poznań|wisła kraków|widzew łódź|raków częstochowa|jagiellonia białystok|borussia dortmund|ajax|fc porto|benfica|sporting|atletico madryt|tottenham|newcastle|roma|lazio|napoli|atalanta|sevilla|valencia|monaco|lyon|marsylia|celtic|rangers"),
  ],
  music:[
    task("music_instruments","Wymień instrumenty muzyczne","gitara|gitara elektryczna|gitara basowa|bas|pianino|fortepian|keyboard|syntezator|perkusja|skrzypce|altówka|wiolonczela|kontrabas|flet|saksofon|trąbka|puzon|tuba|klarnet|obój|fagot|harfa|ukulele|akordeon|harmonijka|tamburyn|marakasy|ksylofon|dzwonki|bęben|banjo|mandolina|lutnia|organy|kalimba"),
    task("music_genres","Wymień gatunki muzyczne","pop|rock|rap|hip hop|metal|jazz|blues|reggae|disco polo|elektroniczna|techno|house|klasyczna|country|indie|k-pop|folk|punk|trap|drill|r&b|soul|funk|disco|dubstep|hardstyle|ambient|lofi|dance|edm|reggaeton|latino|opera|musical"),
  ],
  movies:[
    task("movies_animated","Wymień filmy animowane lub bajki","shrek|król lew|toy story|auta|kraina lodu|minionki|kung fu panda|madagaskar|jak wytresować smoka|grawitacja falls|gravity falls|pora na przygodę|regular show|gumball|fineasz i ferb|rick and morty|simpsonowie|pokemon|digimon|avatar legenda aanga|korra|sailor moon|disenchantment|futurama|bojack horseman|spider-man uniwersum|vaiana|encanto|coco|ratatuj|wall-e|odlot|potwory i spółka|gdzie jest nemo|iniemamocni"),
    task("movies_series","Wymień seriale aktorskie","stranger things|breaking bad|better call saul|wednesday|the office|friends|gra o tron|wiedźmin|squid game|black mirror|peaky blinders|dom z papieru|narcos|dark|chernobyl|the walking dead|cobra kai|lucifer|dexter|dr house|sherlock|the boys|fallout|the bear|shogun|house of the dragon|arrow|flash|gotham|titans|sex education|riverdale|outer banks|you|ozark|mindhunter|true detective|fargo|succession|modern family|brooklyn nine-nine"),
  ],
  vegetables:[
    task("vegetables_root","Wymień warzywa korzeniowe","ziemniak|marchewka|burak|pietruszka|seler|rzodkiewka|rzodkiew|rzepa|batat|pasternak|topinambur|maniok|chrzan|brukiew|skorzonera"),
    task("vegetables_leafy","Wymień warzywa liściaste lub sałaty","sałata|rukola|roszponka|szpinak|jarmuż|cykoria|boćwina|kapusta|kapusta pekińska|pak choi|endywia|radicchio|sałata lodowa|sałata rzymska|sałata masłowa"),
    task("vegetables_green","Wymień zielone warzywa","ogórek|brokuł|cukinia|groszek|fasolka szparagowa|szpinak|jarmuż|sałata|rukola|roszponka|brukselka|szparagi|por|seler naciowy|bób|okra|edamame|kapusta|kalarepa"),
  ],
  games:[
    task("games_mobile","Wymień gry mobilne","brawl stars|clash royale|clash of clans|pokemon go|subway surfers|temple run|angry birds|candy crush|geometry dash|stumble guys|among us|roblox|minecraft|pubg mobile|call of duty mobile|genshin impact|honkai star rail|hay day|plants vs zombies|fruit ninja|jetpack joyride|hill climb racing|the battle cats|plague inc|monopoly go|8 ball pool|crossy road|cut the rope|my talking tom"),
    task("games_multiplayer","Wymień gry multiplayer","minecraft|roblox|fortnite|valorant|league of legends|counter strike|counter strike 2|csgo|among us|rocket league|overwatch|apex legends|fall guys|pubg|dota 2|world of warcraft|dead by daylight|phasmophobia|rust|ark|rainbow six siege|destiny|warframe|helldivers|gta online|sea of thieves|palworld|terraria|stardew valley|team fortress 2|war thunder|world of tanks|fifa|ea fc|mario kart|super smash bros|splatoon"),
    task("games_classics","Wymień klasyczne gry komputerowe lub konsolowe","tetris|pac-man|pong|snake|super mario|mario kart|zelda|doom|quake|diablo|warcraft|starcraft|half-life|portal|the sims|counter strike|gta|gta san andreas|minecraft|terraria|skyrim|need for speed|heroes 3|worms|age of empires|simcity|rollercoaster tycoon|mortal kombat|tekken|street fighter|sonic|pokemon|metroid|castlevania"),
  ],
  roblox:[
    task("roblox_horror","Wymień straszne gry na Robloxie","doors|pressure|piggy|apeirophobia|rainbow friends|the mimic|flee the facility|dead silence|bear alpha|breaking point|murder mystery 2|3008|evade|nico's nextbots|specter|identity fraud|the maze|cheese escape|short creepy stories|forgotten memories|residence massacre|dandy's world"),
    task("roblox_roleplay","Wymień gry roleplay lub symulatory na Robloxie","brookhaven|adopt me|bloxburg|welcome to bloxburg|livetopia|berry avenue|meepcity|royale high|work at a pizza place|restaurant tycoon 2|theme park tycoon 2|pet simulator 99|pet simulator x|bee swarm simulator|vehicle simulator|driving empire|greenville|jailbreak|mad city|dress to impress|fisch"),
    task("roblox_action","Wymień gry akcji lub zręcznościowe na Robloxie","arsenal|bedwars|tower of hell|obby but you're on a bike|natural disaster survival|blade ball|blox fruits|anime adventures|the strongest battlegrounds|combat warriors|phantom forces|frontlines|jailbreak|mad city|murder mystery 2|evade|obby creator|speed run 4|epic minigames|super bomb survival"),
  ],
  everyday:[
    task("everyday_bathroom","Wymień rzeczy, które można znaleźć w łazience","ręcznik|szczoteczka do zębów|pasta do zębów|mydło|szampon|odżywka|żel pod prysznic|papier toaletowy|pralka|kosz na pranie|lustro|umywalka|wanna|prysznic|toaleta|sedes|szczotka do toalety|gąbka|grzebień|szczotka|suszarka|maszynka do golenia|dezodorant|perfumy|płyn do płukania ust|nić dentystyczna|waciki|patyczki kosmetyczne"),
    task("everyday_bedroom","Wymień rzeczy, które można znaleźć w sypialni","łóżko|poduszka|kołdra|koc|prześcieradło|szafa|komoda|stolik nocny|lampka|budzik|lustro|dywan|zasłona|firanka|wieszak|biurko|krzesło|książka|telefon|ładowarka|kapcie|ubrania|kosz na pranie|roślina|obraz|plakat|półka"),
  ],
  transport:[
    task("transport_land","Wymień środki transportu poruszające się po lądzie","samochód|autobus|tramwaj|pociąg|metro|rower|motocykl|skuter|hulajnoga|taksówka|ciężarówka|tir|furgonetka|kamper|quad|traktor|kombajn|limuzyna|karetka|radiowóz|wóz strażacki|autokar|trolejbus|kolejka linowa|segway|deskorolka|rolki"),
    task("transport_air_water","Wymień środki transportu wodnego lub powietrznego","samolot|helikopter|śmigłowiec|balon|sterowiec|szybowiec|odrzutowiec|rakieta|statek|prom|łódź|motorówka|kajak|żaglówka|jacht|tratwa|gondola|katamaran|skuter wodny|okręt|łódź podwodna|poduszkowiec"),
  ],
  clothes:[
    task("clothes_footwear","Wymień rodzaje obuwia","buty|trampki|adidasy|sneakersy|kozaki|botki|kalosze|sandały|klapki|japonki|kapcie|szpilki|mokasyny|półbuty|glany|martensy|korki|łyżwy|rolki|buty trekkingowe"),
    task("clothes_accessories","Wymień dodatki do ubioru","czapka|kapelusz|szalik|rękawiczki|pasek|krawat|muszka|zegarek|bransoletka|naszyjnik|kolczyki|pierścionek|okulary|okulary przeciwsłoneczne|torebka|plecak|portfel|parasolka|opaska|spinka|gumka do włosów|apaszka|beret"),
  ],
  nature:[
    task("nature_weather","Wymień zjawiska pogodowe","deszcz|śnieg|grad|burza|piorun|grzmot|tęcza|mgła|wiatr|wichura|huragan|tornado|trąba powietrzna|zamieć|mżawka|ulewa|szron|rosa|gołoledź|upał|susza|przymrozek|lawina|chmura"),
    task("nature_plants","Wymień drzewa, kwiaty lub inne rośliny","dąb|brzoza|sosna|świerk|jodła|klon|kasztanowiec|wierzba|topola|buk|lipa|jarzębina|róża|tulipan|stokrotka|słonecznik|fiołek|konwalia|lawenda|orchidea|kaktus|paproć|mech|trawa|bluszcz|bambus|aloes|monstera"),
  ],
  drinks:[
    task("drinks_hot","Wymień ciepłe napoje","herbata|kawa|espresso|americano|cappuccino|latte|macchiato|flat white|kakao|gorąca czekolada|grzane wino|grzaniec|yerba mate|matcha|chai latte|napar|rumianek|mięta"),
    task("drinks_cold","Wymień zimne napoje bezalkoholowe","woda|woda gazowana|lemoniada|cola|pepsi|sprite|fanta|oranżada|sok|nektar|ice tea|mrożona herbata|mrożona kawa|shake|koktajl|smoothie|energetyk|izotonik|tonik|kwas chlebowy|kompot"),
  ],
  body:[
    task("body_organs","Wymień narządy człowieka","serce|mózg|płuca|wątroba|nerki|żołądek|jelito|jelito cienkie|jelito grube|trzustka|śledziona|pęcherz|skóra|oko|ucho|język|gardło|tarczyca|wyrostek robaczkowy|przepona"),
    task("body_bones","Wymień kości lub części szkieletu człowieka","czaszka|kręgosłup|żebro|miednica|łopatka|obojczyk|mostek|kość ramienna|kość promieniowa|kość łokciowa|kość udowa|rzepka|piszczel|strzałka|żuchwa|szczęka|paliczek|kość ogonowa|kość krzyżowa"),
  ],
};
