// Dopisuj pytania do grupy kategorii. Trzeci argument true oznacza opcjonalne lekkie spicy.
const group = (category, questions, spicy = false) => questions.map(text => ({ category, text, spicy }));
export const friendshipQuestions = [
  ...group("Muzyka", ["Jaki jest twój ulubiony artysta?", "Jaką piosenkę znasz prawie na pamięć?", "Jaki koncert chcesz zobaczyć na żywo?", "Jaki utwór zawsze poprawia ci humor?", "Jakiego gatunku muzyki słuchasz najczęściej?", "Jaka piosenka najbardziej kojarzy ci się z wakacjami?"]),
  ...group("Jedzenie", ["Jakiego jedzenia nigdy nie odmówisz?", "Jaki jest twój ulubiony fast food?", "Co potrafisz ugotować najlepiej?", "Jaki smak lodów wybierasz najczęściej?", "Jakiej potrawy nie tkniesz nawet za nagrodę?", "Jaka przekąska znika u ciebie najszybciej?"]),
  ...group("Szkoła", ["Który przedmiot szkolny lubisz najbardziej?", "Czego najbardziej nie lubisz w szkole?", "Na jakiej lekcji najłatwiej odpływasz myślami?", "Jaki był twój ulubiony szkolny wyjazd?", "Z którego przedmiotu najchętniej pozbyłbyś się sprawdzianów?", "Gdzie najczęściej siadasz w sali?"]),
  ...group("Gaming", ["Jaka jest twoja ulubiona gra?", "W jakiej grze masz najwięcej godzin?", "Jaką grę możesz przechodzić wiele razy?", "Jaki typ gier wybierasz najczęściej?", "Która gra najbardziej cię kiedyś wciągnęła?", "Jaką grę poleciłbyś całej ekipie?"]),
  ...group("Dzieciństwo", ["Jaka bajka była twoją ulubioną?", "Kim chciałeś zostać jako dziecko?", "Jaka zabawka była dla ciebie najważniejsza?", "Jakie wspomnienie z dzieciństwa najbardziej cię bawi?", "Jaki smak kojarzy ci się z dzieciństwem?", "W co najczęściej bawiłeś się po szkole?"]),
  ...group("Internet", ["Jaka aplikacja zabiera ci najwięcej czasu?", "Jaki typ filmików możesz oglądać godzinami?", "Z jakiej aplikacji najtrudniej byłoby ci zrezygnować?", "Jaki mem ostatnio najbardziej cię rozbawił?", "Jak często sprawdzasz telefon zaraz po przebudzeniu?", "Jaki kanał lub twórcę najchętniej polecasz?"]),
  ...group("Osobowość", ["Jaki jest twój najdziwniejszy nawyk?", "Co najszybciej poprawia ci humor?", "Czego uczysz się szybciej niż większość osób?", "Co najbardziej cię stresuje?", "Jaki komplement pamiętasz najdłużej?", "Jaka cecha najlepiej cię opisuje?"]),
  ...group("Wybory", ["Dokąd pojedziesz, jeśli dostaniesz darmowy bilet?", "Na co wydasz niespodziewane 500 zł?", "Wolisz góry, morze czy miasto?", "Jaką supermoc wybierzesz?", "Jaki dzień tygodnia lubisz najbardziej?", "Z jakiej codziennej rzeczy najtrudniej byłoby ci zrezygnować?"]),
  ...group("Znajomi", ["Co najbardziej cenisz w znajomych?", "Jaki wspólny plan brzmi dla ciebie idealnie?", "Kto zwykle pierwszy pisze po dłuższej ciszy?", "Jak wygląda twój idealny wieczór z ekipą?", "Jaki prezent od znajomych ucieszyłby cię najbardziej?", "W jakiej sytuacji zawsze można na ciebie liczyć?"]),
  ...group("Śmieszne", ["Jaka jest twoja najbardziej bezużyteczna umiejętność?", "Co najdziwniejszego masz teraz w pobliżu?", "Jakie słowo zdarza ci się przekręcać?", "Jaką rzecz najczęściej gubisz?", "Jaki zakup był kompletnie niepotrzebny, ale udany?", "Jakie jedzenie łączysz w sposób, którego inni nie rozumieją?"]),
  ...group("Lekkie spicy", ["Jaki typ osoby zwraca twoją uwagę jako pierwszy?", "Co jest dla ciebie największym green flagiem?", "Jaki jest twój najbardziej niewinny celebrity crush?", "Wolisz pierwszą randkę spontaniczną czy zaplanowaną?", "Jaki komplement działa na ciebie najlepiej?", "Kto powinien napisać pierwszy po udanej randce?"], true),
  ...group("Minecraft i Roblox", ["Jaki mob z Minecrafta jest twoim ulubionym?", "Co najpierw budujesz w nowym świecie Minecraft?", "Wolisz survival czy creative?", "Jaka gra na Roblox najbardziej cię wciągnęła?", "Jaki skin lub avatar wybrałbyś bez limitu?", "Z kim z ekipy najchętniej zagrałbyś nocny maraton?", "Jaki przedmiot z Minecrafta chciałbyś mieć naprawdę?", "Co robisz po znalezieniu pierwszych diamentów?"]),
  ...group("YouTube i internet", ["Którego twórcę oglądałeś najczęściej jako dziecko?", "Jaki kanał możesz oglądać godzinami?", "Jaki film z YouTube ostatnio naprawdę cię rozbawił?", "Wolisz streamy czy krótkie filmy?", "Którego twórcę chciałbyś spotkać?", "Jaki typ contentu sam mógłbyś nagrywać?", "Jaką aplikację otwierasz automatycznie?", "Jaki internetowy trend pamiętasz najlepiej?"]),
  ...group("Więcej o ekipie", ["Kto z ekipy najlepiej organizuje wspólne plany?", "Jaka wspólna historia zawsze cię śmieszy?", "Co najchętniej robisz podczas spotkania ze znajomymi?", "Jaki wspólny wyjazd byłby idealny?", "W jakiej grze twoja ekipa dogaduje się najlepiej?", "Kto najczęściej ratuje sytuację?", "Jak wyglądałby idealny wieczór bez żadnych ograniczeń?", "Jaki inside joke ekipy pamiętasz najlepiej?"]),
];
friendshipQuestions.push(
  ...group("Filmy i seriale", ["Jaki film możesz oglądać wiele razy?", "Który serial poleciłbyś całej ekipie?", "W jakim filmowym świecie chciałbyś zamieszkać?", "Wolisz Marvela, Harry'ego Pottera czy Shreka?", "Jaki bohater filmowy najbardziej do ciebie pasuje?", "Jaki film zawsze poprawia ci humor?", "Czy wybierzesz kino czy domowy maraton?", "Jaki serial ostatnio naprawdę cię wciągnął?"]),
  ...group("Podróże", ["Jaki kraj najbardziej chcesz odwiedzić?", "Wolisz spontaniczny wyjazd czy planowanie z wyprzedzeniem?", "Co zawsze zabierasz na wyjazd?", "Wolisz góry, morze czy zwiedzanie miasta?", "Z kim z ekipy najłatwiej byłoby ci podróżować?", "Jak długa podróż samochodem zaczyna cię męczyć?", "Jakie jedzenie najchętniej spróbowałbyś za granicą?", "Jaki był twój najlepszy dotychczasowy wyjazd?"]),
  ...group("Pokémon i nostalgia", ["Którego Pokémona wybrałbyś jako kompana?", "Jaka bajka najbardziej kojarzy ci się z dzieciństwem?", "Jaką grę z dzieciństwa chętnie odpalisz ponownie?", "Czy jako startera wybierzesz Charmandera, Squirtle'a czy Bulbasaura?", "Jaką rzecz kiedyś kolekcjonowałeś?", "Jaka stara piosenka lub czołówka bajki od razu poprawia ci humor?", "Która zabawka była kiedyś twoim marzeniem?", "Czy bardziej pamiętasz Pokémony, Minecraft czy stare gry przeglądarkowe?"]),
  ...group("Jedzenie", ["Jakie jedzenie zamawiasz najczęściej?", "Wolisz pizzę, kebab czy sushi?", "Jakiego jedzenia nigdy nie odmówisz?", "Jaki jest twój ulubiony smak lodów?", "Jaką potrawę umiesz przygotować najlepiej?", "Czy dzielisz się ostatnim kawałkiem pizzy?", "Jakie przekąski wybierasz na maraton gier?", "Jaki dziwny zestaw jedzenia naprawdę ci smakuje?"]),
  ...group("Gaming", ["W jaką grę możesz grać godzinami?", "Wolisz Minecraft, Roblox czy Fortnite?", "Jaka gra najbardziej cię kiedyś wciągnęła?", "Czy w grach wybierasz rywalizację czy spokojną zabawę?", "Jaki przedmiot z gry chciałbyś mieć naprawdę?", "Z kim z ekipy najlepiej gra ci się online?", "Która przegrana w grze najbardziej cię bawi po czasie?", "Jak wyglądałaby twoja idealna wspólna sesja grania?"]),
  ...group("Internet", ["Którą aplikację otwierasz bez zastanowienia?", "Czy częściej wysyłasz memy, rolki czy shorty?", "Którego twórcę internetowego oglądasz najdłużej?", "Jakiego trendu internetowego zupełnie nie rozumiesz?", "Czy wolisz TikTok, YouTube czy Discord?", "Jaki mem najlepiej opisuje twój humor?", "Czy mógłbyś wytrzymać tydzień bez social mediów?", "Jak wygląda twój idealny wieczór online ze znajomymi?"]),
  ...group("Muzyka", ["Jakiej piosenki znasz cały tekst?", "Którego artystę najchętniej zobaczysz na żywo?", "Wolisz słuchać muzyki w słuchawkach czy na głośniku?", "Jakiej piosenki słuchasz dla poprawy humoru?", "Jaki gatunek muzyki wybierasz najczęściej?", "Czy masz playlistę do grania?", "Która piosenka kojarzy ci się z wakacjami?", "Czy umiesz grać lub chcesz nauczyć się grać na instrumencie?"]),
  ...group("Więcej o ekipie", ["Kto z ekipy najczęściej wysyła najlepsze memy?", "Jaki wspólny plan zawsze by cię przekonał?", "Kto z ekipy najlepiej uspokaja konflikty?", "Jaki wspólny moment chciałbyś przeżyć jeszcze raz?", "Kto najczęściej inicjuje rozmowę na grupie?", "W czym twoja ekipa jest naprawdę dobra?", "Jaki nowy wspólny zwyczaj warto wprowadzić?", "Jaką planszówkę lub grę imprezową najchętniej przeniósłbyś do internetu?"]),
  ...group("Lekkie spicy", ["Co szybciej zwraca twoją uwagę: humor czy wygląd?", "Jaki jest najbardziej oczywisty green flag?", "Wolisz spontaniczną wiadomość czy zaplanowaną randkę?", "Czy łatwiej ci napisać pierwszemu czy czekać?", "Jaki komplement najbardziej zapada w pamięć?", "Czy znajomi dobrze zgadliby twój typ?", "Wolisz romantyczny gest czy wspólny żart?", "Jaka randka brzmi najlepiej: kino, spacer czy jedzenie?"], true)
);

const uniqueFriendshipQuestions = new Map(friendshipQuestions.map(item => [`${item.category}|${item.text}|${item.spicy}`, item]));
friendshipQuestions.splice(0, friendshipQuestions.length, ...uniqueFriendshipQuestions.values());

export const friendshipCategories = [...new Set(friendshipQuestions.filter(item => !item.spicy).map(item => item.category))];
